### ISSUE TITLE
NPE while adding Trust Relationship

### ISSUE THREAD

**Issue by bradmesserle** [GluuFederation/oxTrust#1006]
I am a newbie of your software.. So i am sure the problem is 5 feet from keyboard. 

But i am getting this error while adding a Trust Relationship.  I have not downloaded the code yet to see what is null.. 

thx

Caused by: java.lang.NullPointerException
        at org.gluu.oxtrust.ldap.service.Shibboleth3ConfService.generateSpMetadataFileContent(Shibboleth3ConfService.java:837) ~[classes/:?]
        at org.gluu.oxtrust.ldap.service.Shibboleth3ConfService.generateSpMetadataFile(Shibboleth3ConfService.java:818) ~[classes/:?]
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction.generateSpMetaDataFileImpl(UpdateTrustRelationshipAction.java:856) ~[classes/:?]
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction.generateSpMetaDataFile(UpdateTrustRelationshipAction.java:835) ~[classes/:?]
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction.saveImpl(UpdateTrustRelationshipAction.java:325) ~[classes/:?]
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction$Proxy$_$$_WeldSubclass.saveImpl(Unknown Source) ~[classes/:?]
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction.save(UpdateTrustRelationshipAction.java:287) ~[classes/:?]
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction$Proxy$_$$_WeldSubclass.save$$super(Unknown Source) ~[classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) ~[weld-core-impl-3.0.1.Final.jar:3.0.1.Final]

**Comment by bradmesserle** [comment]
Sorry version is the new 3.1.3 CE .. centos 7.

**Comment by mzico** [comment]
@bradmesserle : Please use Gluu Support Portal ( https://support.gluu.org ) for any kind of support related issue.
