### ISSUE TITLE
All file upload features in Gluu 3.1.3 don't works

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1007]
# Description

Due some library update in gluu server 3.1.3 all places where the file uploader is been use is throwing an error like this : 
```
2018-06-11 08:44:58,612 ERROR [qtp1744347043-15] [com.sun.faces.application.view.FaceletViewHandlingStrategy] (FaceletViewHandlingStrategy.java:1233) - Error Rendering View[/person/personImport.xhtml]
java.lang.IllegalArgumentException: Unrecognized Content Type.
	at com.sun.faces.renderkit.RenderKitImpl.createResponseWriter(RenderKitImpl.java:276) ~[jsf-impl-2.2.17.jar:2.2.17]
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.createResponseWriter(FaceletViewHandlingStrategy.java:1191) [jsf-impl-2.2.17.jar:2.2.17]

```

# Steps to reproduce

1. Log into gluu admin UI
1. Navigate to **Organization** > **Organization configuration**
1. Select the **OxTrust Settings** tab
1. Upload a new logo and see what happen

Other scenario are **Attributes import**, **Person import**

**Comment by merpdotcom** [comment]
Is there a workaround until this is available in 3.1.4?

**Comment by syntrydy** [comment]
@merpdotcom there is a workaround in faq section

**Comment by syntrydy** [comment]
https://gluu.org/docs/ce/3.1.3/operation/faq/#how-to-fix-imagefiles-upload-issue-in-gluu-313

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45080907-dc9fd480-b0ed-11e8-8889-1aed36f2dbba.png)

**Comment by syntrydy** [comment]
I don't know why it don't work for you.
