### ISSUE TITLE
Not able to add user

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1172]
Go to Add User screen, provide valid values and hit submit

![image](https://user-images.githubusercontent.com/21104811/45002519-28228780-aff5-11e8-907d-a85c1c31f508.png)

oxtrust Logs

Caused by: LDAPSearchException(resultCode=32 (no such object), numEntries=0, numReferences=0, errorMessage='Failed to scroll to specified startIndex')
        at org.gluu.site.ldap.OperationsFacade.search(OperationsFacade.java:329)
        at org.gluu.site.ldap.persistence.LdapEntryManager.findEntries(LdapEntryManager.java:399)
        ... 21 more
Caused by: LDAPSearchException(resultCode=32 (no such object), numEntries=0, numReferences=0, errorMessage='The search base entry 'ou=resetPasswordRequests,inum=@!2926.2038.CF8B.82E6!0002!C54D.6BD9,ou=appliances,o=gluu' does not exist', matchedDN='inum=@!2926.2038.CF8B.82E6!0002!C54D.6BD9,ou=appliances,o=gluu')
        at com.unboundid.ldap.sdk.LDAPConnection.search(LDAPConnection.java:3650)
        at org.gluu.site.ldap.OperationsFacade.search(OperationsFacade.java:300)
        ... 22 more
2018-09-03 22:14:15,074 INFO  [qtp1744347043-12] [org.gluu.oxtrust.util.ServiceUtil] (ServiceUtil.java:383) -  IN Utils.syncEmailReverse()...
2018-09-03 22:14:15,090 INFO  [qtp1744347043-12] [org.gluu.oxtrust.util.ServiceUtil] (ServiceUtil.java:437) -  LEAVING Utils.syncEmailReverse()...
2018-09-03 22:14:15,097 ERROR [qtp1744347043-12] [org.gluu.oxtrust.action.UpdatePersonAction] (UpdatePersonAction.java:451) - Failed to add new person @!2926.2038.CF8B.82E6!0001!F046.AB28!0000!A724.4286.0B8A.95E9
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to persist entry: inum=@!2926.2038.CF8B.82E6!0001!F046.AB28!0000!A724.4286.0B8A.95E9,ou=people,o=@!2926.2038.CF8B.82E6!0001!F046.AB28,o=gluu
        at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:124) ~[oxcore-ldap-3.1.4-SNAPSHOT.jar:?]
        at org.gluu.site.ldap.persistence.AbstractEntryManager.persist(AbstractEntryManager.java:90) ~[oxcore-ldap-3.1.4-SNAPSHOT.jar:?]
        at org.gluu.site.ldap.persistence.LdapEntryManager$Proxy$_$$_WeldClientProxy.persist(Unknown Source) ~[oxcore-ldap-3.1.4-SNAPSHOT.jar:?]
        at org.gluu.oxtrust.ldap.service.PersonService.addPerson(PersonService.java:109) ~[classes/:?]
        at org.gluu.oxtrust.action.UpdatePersonAction.save(UpdatePersonAction.java:443) [classes/:?]
        at org.gluu.oxtrust.action.UpdatePersonAction$Proxy$_$$_WeldSubclass.save$$super(Unknown Source) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
        at org.xdi.service.security.SecurityInterceptor.invoke(SecurityInterceptor.java:55) [oxcore-service-3.1.4-SNAPSHOT.jar:?]

Caused by: com.unboundid.ldap.sdk.LDAPException: Entry inum=@!2926.2038.CF8B.82E6!0001!F046.AB28!0000!A724.4286.0B8A.95E9,ou=people,o=@!2926.2038.CF8B.82E6!0001!F046.AB28,o=gluu violates the Directory Server schema configuration because it contains an unknown objectclass eduPerson

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/45051588-6ca53600-b07c-11e8-9f62-425a1bca69bc.png)


Not reproducible.

**Comment by mbaser** [comment]
commit https://github.com/GluuFederation/community-edition-setup/commit/b1634c845dbe0f1687dcedf80049e5bab49b6918 closed this issue
