### ISSUE TITLE
Automatic end session call on oxTrust session end not working

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#127]
2015-10-13 20:04:46,208 ERROR [org.gluu.oxtrust.service.AuthenticationSessionService] Exception happened at oxAuth logout. User: 'admin'
java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1234)
	at java.util.regex.Matcher.reset(Matcher.java:308)
	at java.util.regex.Matcher.<init>(Matcher.java:228)
	at java.util.regex.Pattern.matcher(Pattern.java:1088)
	at org.jboss.resteasy.specimpl.UriBuilderImpl.uriTemplate(UriBuilderImpl.java:84)
	at org.jboss.resteasy.client.ClientRequest.getBuilder(ClientRequest.java:151)
	at org.jboss.resteasy.client.ClientRequest.<init>(ClientRequest.java:102)
	at org.jboss.resteasy.client.ClientRequest.<init>(ClientRequest.java:97)
	at org.xdi.oxauth.client.BaseClient.initClientRequest(BaseClient.java:227)
	at org.xdi.oxauth.client.EndSessionClient.exec(EndSessionClient.java:96)
	at org.gluu.oxtrust.service.AuthenticationSessionService.sessionDestroyed(AuthenticationSessionService.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
	at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
	at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	at org.jboss.seam.core.SynchronizationInterceptor.aroundInvoke(SynchronizationInterceptor.java:35)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
	at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196)
	at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114)
	at org.gluu.oxtrust.service.AuthenticationSessionService_$$_javassist_seam_50.sessionDestroyed(AuthenticationSessionService_$$_javassist_seam_50.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
	at org.jboss.seam.util.Reflections.invokeAndWrap(Reflections.java:144)
	at org.jboss.seam.Component.callComponentMethod(Component.java:2313)
	at org.jboss.seam.Component.callDestroyMethod(Component.java:2244)
	at org.jboss.seam.Component.destroy(Component.java:1476)
	at org.jboss.seam.contexts.Contexts.destroy(Contexts.java:290)
	at org.jboss.seam.contexts.Lifecycle.endSession(Lifecycle.java:295)
	at org.jboss.seam.contexts.ServletLifecycle.endSession(ServletLifecycle.java:187)
	at org.jboss.seam.servlet.SeamListener.sessionDestroyed(SeamListener.java:59)
	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:809)
	at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:657)
	at org.apache.catalina.session.ManagerBase.processExpires(ManagerBase.java:581)
	at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:566)
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1352)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1546)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1556)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1556)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1524)

**Comment by yurem** [comment]
This problem caused by invalid local configuration. The end_session URL is missing as result application can't call end session endpoint.
