### ISSUE TITLE
OxTrust throws error few seconds after the first login.

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1295]
# Description

Using then Gluu docker edition, after installation, oxtrust throw the below error after few seconds:

```
UMA passport authentication is disabled
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to find entries with baseDN: ou=resetPasswordRequests,inum=@!5B5C.5C39.7630.6B6A!0002!1D73.BB6C,ou=appliances,o=gluu, filter: (&(&(objectClass=top)(objectClass=gluuPasswordResetRequest))(creationDate<=20181005221311.213Z))
	at org.gluu.site.ldap.persistence.LdapEntryManager.findEntries(LdapEntryManager.java:405)
	at org.gluu.site.ldap.persistence.LdapEntryManager$Proxy$_$$_WeldClientProxy.findEntries(Unknown Source)
	at org.gluu.oxtrust.service.PasswordResetService$1.getChunkOrNull(PasswordResetService.java:162)
	at org.gluu.site.ldap.persistence.BatchOperation.iterateAllByChunks(BatchOperation.java:47)
	at org.gluu.oxtrust.service.PasswordResetService.cleanup(PasswordResetService.java:181)
	at org.gluu.oxtrust.service.CleanerTimer.processPasswordReset(CleanerTimer.java:102)
```

**Comment by syntrydy** [comment]
@iromli, @afroDC issue fixed

**Comment by iromli** [comment]
Thanks @syntrydy

**Comment by sphereict** [comment]
hey guys I am getting the same issue. How can the below be resolved

Failed to find entries with baseDN: ou=resetPasswordRequests,inum=@!4A5D.C0F9.C614.6A20!0002!C524.C86E,ou=appliances,o=gluu, filter: (&(&(objectClass=top)(objectClass=gluuPasswordResetRequest))(creationDate<=20181024105248.385Z))
        at org.gluu.site.ldap.persistence.LdapEntryManager.findEntries(LdapEntryManager.java:405)
        at org.gluu.site.ldap.persistence.LdapEntryManager$Proxy$_$$_WeldClientProxy.findEntries(Unknown Source)
        at org.gluu.oxtrust.service.PasswordResetService$1.getChunkOrNull(PasswordResetService.java:162)
        at org.gluu.site.ldap.persistence.BatchOperation.iterateAllByChunks(BatchOperation.java:47)
        at org.gluu.oxtrust.service.PasswordResetService.cleanup(PasswordResetService.java:181)
        at org.gluu.oxtrust.service.CleanerTimer.processPasswordReset(CleanerTimer.java:102)
        at org.gluu.oxtrust.service.CleanerTimer$Proxy$_$$_WeldSubclass.processPasswordReset(Unknown Source)
        at org.gluu.oxtrust.service.CleanerTimer.process(CleanerTimer.java:90)
        at org.gluu.oxtrust.service.CleanerTimer$Proxy$_$$_WeldSubclass.process$$super(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor376.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51)
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78)

**Comment by rouing** [comment]
I also am having the same issue as @sphereict
