### ISSUE TITLE
Random dashboard statistics in Gluu Server cluster

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxTrust#1331]
According to [this ticket](https://support.gluu.org/feature-request/6200/dashboard-statistics/#at40735), and confirmed by 3-day tests, a cluster of 2+ Gluu Servers displays random statistics of incorrect authorization requests:

- day 1:
<img width="1440" alt="gluucluster_07 11 18" src="https://user-images.githubusercontent.com/38302725/48259947-cefc2780-e46d-11e8-9a0e-6758485c0c39.png">

- day 2:
<img width="1438" alt="gluucluster_08 11 2019" src="https://user-images.githubusercontent.com/38302725/48259963-dd4a4380-e46d-11e8-8c8a-f1deea1c17c0.png">

- day 3:
<img width="1437" alt="gluucluster_09 11 19" src="https://user-images.githubusercontent.com/38302725/48259989-f0f5aa00-e46d-11e8-80d6-f619b67c5ca6.png">

The count of successful logins has been ok. 
**The number of TOTAL AUTHENTICATION REQUESTS and TOTAL FAILED LOGINS has risen dramatically, and I have only logged in several times.**

There are errors in logs:

`org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to find entries with baseDN: ou=resetPasswordRequests,inum=@!C40F.DE5B.EC0B.69EA!0002!70A3.A184,ou=appliances,o=gluu, filter: (&(&(objectClass=top)(objectClass=gluuPasswordResetRequest))(creationDate<=20181106234536.036Z))
        at org.gluu.site.ldap.persistence.LdapEntryManager.findEntries(LdapEntryManager.java:405)
        at org.gluu.site.ldap.persistence.LdapEntryManager$Proxy$_$$_WeldClientProxy.findEntries(Unknown Source)
        at org.gluu.oxtrust.service.PasswordResetService$1.getChunkOrNull(PasswordResetService.java:162)
        at org.gluu.site.ldap.persistence.BatchOperation.iterateAllByChunks(BatchOperation.java:47)
        at org.gluu.oxtrust.service.PasswordResetService.cleanup(PasswordResetService.java:181)
        at org.gluu.oxtrust.service.CleanerTimer.processPasswordReset(CleanerTimer.java:102)
        at org.gluu.oxtrust.service.CleanerTimer$Proxy$_$$_WeldSubclass.processPasswordReset(Unknown Source)
        at org.gluu.oxtrust.service.CleanerTimer.process(CleanerTimer.java:90)
        at org.gluu.oxtrust.service.CleanerTimer$Proxy$_$$_WeldSubclass.process$$super(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor264.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51)
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78)
        at org.xdi.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:36)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.lang.Thread.run(Thread.java:748)
Caused by: LDAPSearchException(resultCode=32 (no such object), numEntries=0, numReferences=0, errorMessage='Failed to scroll to specified startIndex')
        at org.gluu.site.ldap.OperationsFacade.search(OperationsFacade.java:329)
        at org.gluu.site.ldap.persistence.LdapEntryManager.findEntries(LdapEntryManager.java:399)
        ... 16 more
Caused by: LDAPSearchException(resultCode=32 (no such object), numEntries=0, numReferences=0, errorMessage='The search base entry 'ou=resetPasswordRequests,inum=@!C40F.DE5B.EC0B.69EA!0002!70A3.A184,ou=appliances,o=gluu' does not exist', matchedDN='inum=@!C40F.DE5B.EC0B.69EA!0002!70A3.A184,ou=appliances,o=gluu')
        at com.unboundid.ldap.sdk.LDAPConnection.search(LDAPConnection.java:3650)
        at org.gluu.site.ldap.OperationsFacade.search(OperationsFacade.java:300)
        ... 17 more`

[EntryPersistenceException1.docx](https://github.com/GluuFederation/oxTrust/files/2565671/EntryPersistenceException1.docx)

**Connected with #1034, I believe.**

**Comment by syntrydy** [comment]
@natt-tester 
`
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to find entries with baseDN: ou=resetPasswordRequests,inum=@!C40F.DE5B.EC0B.69EA!0002!70A3.A184,ou=appliances,o=gluu, filter: (&(&(objectClass=top)(objectClass=gluuPasswordResetRequest))(creationDate<=20181106234536.036Z)) at ...
`
is related to something else and that is already fixed.

About the graph showing random statistics in clustered environment, that is due to replication, in clustered env, servers connect to each other to sync data. It seems that these extra connection from one server to another are also count in the graph.

I'm going to look for a solution and also discuss with @yurem @afroDC and @mbaser about it

**Comment by yurem** [comment]
yes, it's expected in 3.1.4 because we are using cluster here. Replication mix ou=metric from 2 servers. As result oxTrust code build wrong graph. In 3.1.5 we will move metric to separate backend. Data from it will be not replicated. As result oxTrust will use data from specific node only and show actual data from it.

But to get total statistic admin should log into both nodes. Bigger changes not fit into 3.1.5 timeline.

I offer to return back to this issue in 4.0. We need to find one way how to build unique persistance server identifier. This key we can add to metric entries to allow show specific server or total statistic from each node.. @afroDC do you have ideas how to make this GUID which can be good for CE, DE?
