### ISSUE TITLE
NPE when checking Certificates management view

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1393]
```
 refresh() CertificateManagement call
2018-12-10 13:51:48,697 ERROR [qtp804611486-9] [org.gluu.oxtrust.action.CertificateManagementAction] (CertificateManagementAction.java:140) - Load Asimba keystore configuration exception
java.lang.NullPointerException: null
	at org.gluu.oxtrust.action.CertificateManagementAction.updateTableView(CertificateManagementAction.java:135) [classes/:?]
	at org.gluu.oxtrust.action.CertificateManagementAction.refresh(CertificateManagementAction.java:99) [classes/:?]
	at org.gluu.oxtrust.action.CertificateManagementAction$Proxy$_$$_WeldSubclass.refresh$$super(Unknown Source) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
	at org.xdi.service.security.SecurityInterceptor.invoke(SecurityInterceptor.java:55) [oxcore-service-3.1.5-SNAPSHOT.jar:?]
	at sun.reflect.GeneratedMethodAccessor115.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) [weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
```

**Comment by natt-tester** [comment]
Can't reproduce the original issue, I believe it's DONE.
