### ISSUE TITLE
Some error related to recaptcha.

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1395]
```
2018-12-10 12:38:31,900 ERROR [qtp804611486-2709] [org.gluu.oxtrust.util.RecaptchaUtil] (RecaptchaUtil.java:98) - Exception happened while verifying recaptcha 
org.codehaus.jackson.map.JsonMappingException: Can not deserialize instance of java.lang.String out of START_ARRAY token
 at [Source: java.io.ByteArrayInputStream@6a22ddea; line: 2, column: 19]
	at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:163) ~[jackson-mapper-asl-1.9.11.jar:1.9.11]
	at org.codehaus.jackson.map.deser.StdDeserializationContext.mappingException(StdDeserializationContext.java:219) ~[jackson-mapper-asl-1.9.11.jar:1.9.11]
	at org.codehaus.jackson.map.deser.std.StringDeserializer.deserialize(StringDeserializer.java:44) ~[jackson-mapper-asl-1.9.11.jar:1.9.11]
	at org.codehaus.jackson.map.deser.std.StringDeserializer.deserialize(StringDeserializer.java:13) ~[jackson-mapper-asl-1.9.11.jar:1.9.11]
	at org.codehaus.jackson.map.deser.std.MapDeserializer._readAndBind(MapDeserializer.java:319) ~[jackson-mapper-asl-1.9.11.jar:1.9.11]
	at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:249) ~[jackson-mapper-asl-1.9.11.jar:1.9.11]
	at org.codehaus.jackson.map.deser.std.MapDeserializer.deserialize(MapDeserializer.java:33) ~[jackson-mapper-asl-1.9.11.jar:1.9.11]
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2732) ~[jackson-mapper-asl-1.9.11.jar:1.9.11]
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1916) ~[jackson-mapper-asl-1.9.11.jar:1.9.11]
	at org.gluu.oxtrust.util.RecaptchaUtil.verifyGoogleRecaptcha(RecaptchaUtil.java:92) [classes/:?]
```

**Comment by natt-tester** [comment]
Can't reproduce it in beta v.3.1.5_4. I believe it's DONE.
