### ISSUE TITLE
[org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:216) - Can not download ssl certificate

### ISSUE THREAD

**Issue by cukal** [GluuFederation/oxTrust#1402]
Setting up cache-refresh with ActiveDirectory over 389 works. 
Changing to 636 SSL generates: 

```2018-12-11 13:20:04,976 ERROR [ForkJoinPool.commonPool-worker-0] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:216) - Can not download ssl certificate
javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative names present
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[?:1.8.0_181]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964) ~[?:1.8.0_181]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328) ~[?:1.8.0_181]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322) ~[?:1.8.0_181]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614) ~[?:1.8.0_181]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:1.8.0_181]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052) ~[?:1.8.0_181]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987) ~[?:1.8.0_181]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072) ~[?:1.8.0_181]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385) ~[?:1.8.0_181]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413) ~[?:1.8.0_181]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397) ~[?:1.8.0_181]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:1.8.0_181]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_181]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162) ~[?:1.8.0_181]
	at org.gluu.oxtrust.ldap.service.StatusCheckerTimer.setCertificateExpiryAttributes(StatusCheckerTimer.java:204) [classes/:?]
	at org.gluu.oxtrust.ldap.service.StatusCheckerTimer.processInt(StatusCheckerTimer.java:162) [classes/:?]
	at org.gluu.oxtrust.ldap.service.StatusCheckerTimer.process(StatusCheckerTimer.java:129) [classes/:?]
	at org.gluu.oxtrust.ldap.service.StatusCheckerTimer$Proxy$_$$_WeldSubclass.process$$super(Unknown Source) [classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
	at org.xdi.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:36) [oxcore-service-3.1.4.Final.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_181]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) [?:1.8.0_181]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_181]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_181]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_181]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_181]
Caused by: java.security.cert.CertificateException: No subject alternative names present
	at sun.security.util.HostnameChecker.matchIP(HostnameChecker.java:145) ~[?:1.8.0_181]
	at sun.security.util.HostnameChecker.match(HostnameChecker.java:94) ~[?:1.8.0_181]
	at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455) ~[?:1.8.0_181]
	at sun.security.ssl.AbstractTrustManagerWrapper.checkAdditionalTrust(SSLContextImpl.java:1026) ~[?:1.8.0_181]
	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:993) ~[?:1.8.0_181]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596) ~[?:1.8.0_181]
```

openssl shows the certificate contains: 
```
#8: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  DNSName: DPP-AD-DC1
  IPAddress: 192.168.20.91
  DNSName: DPP-AD-DC1.DPP-AD.intra.domain.com
]
```

Authenticating however continues to work. 

Setting up a new (empty) Gluu environment with ActiveDirectory remote ldap over 636 SSL enabled from the start generates the same message but the cache-refresh does work, users are pulled in the local backend ldap.

**Comment by yurem** [comment]
Your 636 SSL uses sef signed certificate. To trust it you can import this cert into java cacerts.
```
> echo |openssl s_client -connect server:636>&1 |sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p'

Cupy and paste the certificate (including BEGIN and END lines) into a local file server.pem

sudo keytool -import -alias ALIAS_OF_CERTIFICATE -keystore $PATH_TO_JAVA_HOME/jre/lib/security/cacerts -file server.pem

The default keystore password is: changeit
```

**Comment by cukal** [comment]
Hello Yurem, 

Thanks for your reply. 

I added the cert to /opt/jdk1.8.0_181/jre/lib/security/cacerts using key tool inside the Gluu ch root.
Tried using the ip adress, the FQDN, or the hostname as alias for the jks but it still continues to throw the error about no subject alternatives names preset whenever the cacherefresh runs.

Thx!
L

**Comment by cukal** [comment]
I've found out that cache-refresh uses a different store hence why it throws the error. 

Check this: https://support.gluu.org/authentication/5131/external-ldap-authentication-test-failed-pkix-path-building-failed/ 

When I comment out these lines it works. 

```
#ssl.trustStoreFile: /etc/certs/openldap.pkcs12
#ssl.trustStorePin: <>
#ssl.trustStoreFormat: pkcs12
```

But it seems nobody knows the password used for /etc/certs/openldap.pkcs12 to update it.

**Comment by afroDC** [comment]
>#ssl.trustStorePin: <>

This pin can be decoded by using `/opt/gluu/bin/encode.py -D $TRUSTSTOREPIN`

**Comment by cukal** [comment]
Hi AfroDC

Thanks for that one.

Adding the ldap ssl cert to the ```/etc/certs/openldap.pkcs12``` store still throws the same error. 
And I still have to put those lines in comment before the authorization actually works. 
I guess that is the workaround for the time being, albeit with a error in the log file each time the refresh runs. 

Thx,
L

**Comment by mbaser** [comment]
This is still persists on 3.1.5:
```
2019-01-03 17:45:17,006 ERROR [ForkJoinPool.commonPool-worker-5] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:216) - Can not download ssl certificate
java.net.ConnectException: Connection refused (Connection refused)
    at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_181]
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_181]
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_181]
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_181]
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_181]
    at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_181]
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673) ~[?:1.8.0_181]
    at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173) ~[?:1.8.0_181]
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[?:1.8.0_181]
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_181]
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_181]
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[?:1.8.0_181]
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[?:1.8.0_181]
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[?:1.8.0_181]
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[?:1.8.0_181]
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_181]
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[?:1.8.0_181]
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162) ~[?:1.8.0_181]
    at org.gluu.oxtrust.ldap.service.StatusCheckerTimer.setCertificateExpiryAttributes(StatusCheckerTimer.java:204) [classes/:?]
    at org.gluu.oxtrust.ldap.service.StatusCheckerTimer.processInt(StatusCheckerTimer.java:162) [classes/:?]
    at org.gluu.oxtrust.ldap.service.StatusCheckerTimer.process(StatusCheckerTimer.java:129) [classes/:?]
    at org.gluu.oxtrust.ldap.service.StatusCheckerTimer$Proxy$_$$_WeldSubclass.process$$super(Unknown Source) [classes/:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
```

**Comment by proofy** [comment]
So what is the solution to this issue or why was the bug closed?
