### ISSUE TITLE
Error in oxtrust logs on creating new TR

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1403]
Seeing following error in oxtrust logs on creating a TR.
1. SAML > Add TR > Metadata: File
Attributes released - Email, Email Verified
Check - Configure Relying Party
Even though status show Active

2018-12-13 02:04:49,787 INFO  [qtp804611486-14] [org.gluu.oxtrust.ldap.service.Shibboleth3ConfService] (Shibboleth3ConfService.java:510) - add ShibbolethCASProtocolConfiguration parameters
2018-12-13 02:04:49,793 ERROR [qtp804611486-14] [org.gluu.oxtrust.ldap.service.TemplateService] (TemplateService.java:56) - Failed to load velocity template 'metadata-providers.xml'
org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'metadata-providers.xml.vm'
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:462) ~[velocity-engine-core-2.0.jar:2.0]
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:343) ~[velocity-engine-core-2.0.jar:2.0]
        at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1554) ~[velocity-engine-core-2.0.jar:2.0]
        at org.apache.velocity.runtime.RuntimeSingleton.getTemplate(RuntimeSingleton.java:293) ~[velocity-engine-core-2.0.jar:2.0]
        at org.apache.velocity.app.Velocity.mergeTemplate(Velocity.java:258) ~[velocity-engine-core-2.0.jar:2.0]
        at org.gluu.oxtrust.ldap.service.TemplateService.generateConfFile(TemplateService.java:54) [classes/:?]
        at org.gluu.oxtrust.ldap.service.TemplateService$Proxy$_$$_WeldClientProxy.generateConfFile(Unknown Source) [classes/:?]
        at org.gluu.oxtrust.ldap.service.Shibboleth3ConfService.generateConfigurationFiles(Shibboleth3ConfService.java:205) [classes/:?]
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction.updateShibboleth3Configuration(UpdateTrustRelationshipAction.java:756) [classes/:?]
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction.saveImpl(UpdateTrustRelationshipAction.java:432) [classes/:?]
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction$Proxy$_$$_WeldSubclass.saveImpl(Unknown Source) [classes/:?]
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction.save(UpdateTrustRelationshipAction.java:284) [classes/:?]
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction$Proxy$_$$_WeldSubclass.save$$super(Unknown Source) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
        at org.xdi.service.security.SecurityInterceptor.invoke(SecurityInterceptor.java:55) [oxcore-service-3.1.5-SNAPSHOT.jar:?]
        at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) [weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84) [weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72) [weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56) [weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79) [weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68) [weld-core-impl-3.0.5.Final.jar:3.0.5.Final]
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction$Proxy$_$$_WeldSubclass.save(Unknown Source) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.apache.el.parser.AstValue.invoke(AstValue.java:247) [org.mortbay.jasper.apache-el-8.5.24.2.jar:8.5.24]
        at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267) [org.mortbay.jasper.apache-el-8.5.24.2.jar:8.5.24]
        at org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40) [weld-web-3.0.5.Final.jar:3.0.5.Final]
        at org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50) [weld-web-3.0.5.Final.jar:3.0.5.Final]
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105) [javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87) [javax.faces-2.2.16.jar:2.2.16]
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102) [javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.component.UICommand.broadcast(UICommand.java:315) [javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790) [javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282) [javax.faces-2.2.16.jar:2.2.16]
        at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81) [javax.faces-2.2.16.jar:2.2.16]
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [javax.faces-2.2.16.jar:2.2.16]
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198) [javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658) [javax.faces-2.2.16.jar:2.2.16]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226) [rewrite-servlet-3.4.2.Final.jar:3.4.2.Final]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) [jetty-security-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]

**Comment by sahiliamsso** [comment]
2018-12-13 02:04:49,831 ERROR [qtp804611486-14] [org.gluu.oxtrust.action.UpdateTrustRelationshipAction] (UpdateTrustRelationshipAction.java:758) - Failed to update Shibboleth v3 configuration
2018-12-13 02:06:04,405 ERROR [ForkJoinPool.commonPool-worker-1] [org.gluu.oxtrust.ldap.service.TemplateService] (TemplateService.java:56) - Failed to load velocity template 'metadata-providers.xml'
2018-12-13 02:06:04,407 ERROR [ForkJoinPool.commonPool-worker-1] [org.gluu.oxtrust.ldap.service.TemplateService] (TemplateService.java:56) - Failed to load velocity template 'attribute-resolver.xml'
2018-12-13 02:06:04,409 ERROR [ForkJoinPool.commonPool-worker-1] [org.gluu.oxtrust.ldap.service.TemplateService] (TemplateService.java:56) - Failed to load velocity template 'attribute-filter.xml'
2018-12-13 02:06:04,410 ERROR [ForkJoinPool.commonPool-worker-1] [org.gluu.oxtrust.ldap.service.TemplateService] (TemplateService.java:56) - Failed to load velocity template 'relying-party.xml'
2018-12-13 02:06:04,412 ERROR [ForkJoinPool.commonPool-worker-1] [org.gluu.oxtrust.ldap.service.TemplateService] (TemplateService.java:56) - Failed to load velocity template 'cas-protocol.xml'
2018-12-13 02:06:04,414 ERROR [ForkJoinPool.commonPool-worker-1] [org.gluu.oxtrust.ldap.service.TemplateService] (TemplateService.java:56) - Failed to load velocity template 'shibboleth2.xml'
2018-12-13 02:06:04,416 ERROR [ForkJoinPool.commonPool-worker-1] [org.gluu.oxtrust.ldap.service.TemplateService] (TemplateService.java:56) - Failed to load velocity template 'saml-nameid.xml'
