### ISSUE TITLE
Exception when oxOTPDevices is set. Prevents users' edition

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1476]
Parsing of extra info for OTP devices is throwing exceptions like this:

```
2019-01-18 20:24:38,915 ERROR [qtp804611486-1067] [org.gluu.oxtrust.action.SearchPersonAction] (SearchPersonAction.java:79) - Failed to find persons
org.gluu.site.ldap.persistence.exception.MappingException: Failed to convert json value '{"devices":[{"nickName":"Will's Google Authenticator","addedOn":1513356709934,"id":-1446127981},{"nickName":"wills autrhw]emntizor","addedOn":1513379736935,"id":-1096318736},{"nickName":"iOS FreeOTP","addedOn":1515194736557,"id":955771149},{"nickName":"iOS Authy","addedOn":1515194974032,"id":-1687078274},{"nickName":"Pixel2 Smart Authenticator","addedOn":1538580407629,"id":-799738797,"soft":true},{"nickName":"Will's Google Authenticator Pixel 2","addedOn":1538621976956,"id":1306191736,"soft":true},{"nickName":"Yuriy's Google OTP","addedOn":1539264391897,"id":787102439,"soft":true},{"nickName":"Nat's Duo","addedOn":1541552496457,"id":-2070827088,"soft":true},{"nickName":"admin","addedOn":1542207561080,"id":-806460768,"soft":true}]}' to object
	at org.gluu.site.ldap.persistence.AbstractEntryManager.convertStringToJson(AbstractEntryManager.java:1115) ~[oxcore-ldap-3.1.5.Final.jar:?]
	at org.gluu.site.ldap.persistence.AbstractEntryManager.setPropertyValue(AbstractEntryManager.java:1100) ~[oxcore-ldap-3.1.5.Final.jar:?]
	at org.gluu.site.ldap.persistence.AbstractEntryManager.createEntities(AbstractEntryManager.java:655) ~[oxcore-ldap-3.1.5.Final.jar:?]
	at org.gluu.site.ldap.persistence.AbstractEntryManager.createEntities(AbstractEntryManager.java:588) ~[oxcore-ldap-3.1.5.Final.jar:?]
	at org.gluu.site.ldap.persistence.LdapEntryManager.createEntities(LdapEntryManager.java:595) ~[oxcore-ldap-3.1.5.Final.jar:?]
	at org.gluu.site.ldap.persistence.LdapEntryManager.findEntries(LdapEntryManager.java:413) ~[oxcore-ldap-3.1.5.Final.jar:?]
	at org.gluu.site.ldap.persistence.LdapEntryManager.findEntries(LdapEntryManager.java:373) ~[oxcore-ldap-3.1.5.Final.jar:?]
	at org.gluu.site.ldap.persistence.LdapEntryManager.findEntries(LdapEntryManager.java:369) ~[oxcore-ldap-3.1.5.Final.jar:?]
	at org.gluu.site.ldap.persistence.LdapEntryManager.findEntries(LdapEntryManager.java:353) ~[oxcore-ldap-3.1.5.Final.jar:?]
	at org.gluu.site.ldap.persistence.LdapEntryManager$Proxy$_$$_WeldClientProxy.findEntries(Unknown Source) ~[oxcore-ldap-3.1.5.Final.jar:?]
	at org.gluu.oxtrust.ldap.service.PersonService.searchPersons(PersonService.java:188) ~[classes/:?]
	at org.gluu.oxtrust.action.SearchPersonAction.search(SearchPersonAction.java:74) [classes/:?]
	at org.gluu.oxtrust.action.SearchPersonAction$Proxy$_$$_WeldSubclass.search$$super(Unknown Source) [classes/:?]
```

This occurs when supplying a search string in the "manage people" form, if any of the potential candidates to be displayed has the *optional* attribute `oxOTPDevices` set. This attribute is used by Casa to attach extra information to the `oxExternalUid` when the enrollment is an OTP device (ie. `oxExternalUid` starts with `hotp:` or `totp:`).

In this case the user is bumped to the home page so there is no way to edit the user(s):

![error_after_search](https://user-images.githubusercontent.com/5444180/51476988-0bdd7800-1d55-11e9-9744-a692d50cf00b.png)

Here is an example of how `oxOTPDevices` looks like for a user:

```
{"devices":[
{"nickName":"Will's Google Authenticator","addedOn":1544651679614,"id":607491823,"soft":true},
{"nickName":"Will's pink keyfob","addedOn":1544651679634,"id":607491829,"soft":false}
]}
```

`addedOn` is a time stamp relative to unix epoch
`soft` indicates whether this is a soft or hard token (the type of OTP credential)
`id` is obtained from the following operation:

```
            String str = uid.replaceFirst("hotp:", "").replaceFirst("totp:", "");
            int idx = str.indexOf(";");
            if (idx > 0) {
                str = str.substring(0, idx);
            }
            id = str.hashCode();
```

where `uid` is the value of `oxExternalUid` attribute.

Overall, it's similar to how `oxMobileDevices` is handled....

When there is no `oxOTPDevices` set, and there is still value in `oxExternalUId`, something like this is shown:
![creds_otp_simple](https://user-images.githubusercontent.com/5444180/51477590-ebaeb880-1d56-11e9-9b63-5b1d33096d8a.png)

"Modality"  shows "passport" which is not appropriate. "passport" should be used when `oxExternalUid` starts with `passport-`.  In the case of the image above there should be no nickname (as in date added), and the modality should be "totp".

**Comment by jgomer2001** [comment]
@syntrydy I still don't see the improvements discussed:

1. I'd prefer the key displayed, not the hash
![key](https://user-images.githubusercontent.com/5444180/51608911-c650b480-1ee6-11e9-8d1f-79ab8d0bd226.png)

1. You are still treating `oxExternalUid` and `oxOTPDevices` as separate entities when it has to do with HOTP/TOTP:
![duplicated](https://user-images.githubusercontent.com/5444180/51608932-d49ed080-1ee6-11e9-9316-e49dd5357a40.png)


(*-1505838864* is twice in this example). Also, what's the idea of the link in the last row?, when clicked, it takes to the oops page...

Account wrt to oxOTPDevices:

> This attribute is used by Casa to attach extra information to the oxExternalUid when the enrollment is an OTP device 

Please login to oxTrust in dc host and check how the admin user is looking for instance... it lists 18 enrollments of this kind, that's not right.

**Comment by syntrydy** [comment]
@jgomer2001 this is too confusing, i can work on something that i don't understand  how it works.
