### ISSUE TITLE
4.0 QA: Error in User Registration 

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1594]
## Describe the issue
User Registration page is not opening

## Steps To Reproduce
1. Enable User Registration Script (Configuration > Manage Custom scripts > user_registration
2. Go to https://{host}/identity/register

## Expected behavior
Registration page should be disaplayed
## Actual behavior
User is redirected to login page

## Desktop (please complete the following information):
 - OS: Ubuntu18
 - Gluu version(If applicable): 4.0

Script Logs
## Additional context
org.xdi.exception.PythonException: Failed to load python file 'java.io.ByteArrayInputStream@60d0247a'
	at org.xdi.service.PythonService.loadPythonScript(PythonService.java:184)
	at org.xdi.service.PythonService$Proxy$_$$_WeldClientProxy.loadPythonScript(Unknown Source)
	at org.xdi.service.custom.script.CustomScriptManager.createExternalTypeFromStringWithPythonException(CustomScriptManager.java:382)
	at org.xdi.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.createExternalTypeFromStringWithPythonException(Unknown Source)
	at org.xdi.service.custom.script.CustomScriptManager.createExternalType(CustomScriptManager.java:350)
	at org.xdi.service.custom.script.CustomScriptManager.reloadCustomScriptConfigurations(CustomScriptManager.java:260)
	at org.xdi.service.custom.script.CustomScriptManager.reloadImpl(CustomScriptManager.java:157)
	at org.xdi.service.custom.script.CustomScriptManager.reload(CustomScriptManager.java:144)
	at org.xdi.service.custom.script.CustomScriptManager.reloadTimerEvent(CustomScriptManager.java:120)
	at org.xdi.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.reloadTimerEvent(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor147.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:159)
	at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:632)
	at org.jboss.weld.util.ForwardingBeanManager.fireEvent(ForwardingBeanManager.java:104)
	at org.xdi.service.timer.TimerJob.execute(TimerJob.java:39)
	at org.xdi.service.timer.JobExecutionDelegate.execute(JobExecutionDelegate.java:31)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: Traceback (most recent call last):
  File "user_registration.py", line 8, in <module>
ImportError: No module named ldap

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/55379915-74e02980-5516-11e9-8c09-05ffc2d92603.png)

**Comment by syntrydy** [comment]
@sahiliamsso with the latest 3.1.6, i can't reproduce the issue.

**Comment by willow9886** [comment]
@syntrydy 

> Gluu version(If applicable): 4.0

I just updated the title of the issue to make it more clear. @sahiliamsso i think we should include `version QA` in the title of similar tickets.

**Comment by syntrydy** [comment]
@sahiliamsso please wait the next 4.0 build and test again.  I test it on my side after few changes in code and evrything is okay.

Note that all custom scripts are kind of broken in current 4.0. The next build will fix it.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/55478411-97a43800-5613-11e9-9979-dc1103bf96c4.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/55478488-bc001480-5613-11e9-94ff-966070e4d0af.png)

**Comment by MohitMaliFtechiz** [comment]
Steps to reproduce the behavior:

    1) Enable User Registration Script (Configuration > Manage Custom scripts > user_registration
    2) Go to https://{host}/identity/register

It gives an 404 error message.
![Screenshot from 2019-06-03 22-03-09](https://user-images.githubusercontent.com/34593983/58894378-82c94b00-870f-11e9-8cc1-40d2d76b0074.png)

**Comment by syntrydy** [comment]
@MohitMaliFtechiz  step 2 is Go to https://{host}/identity/register.htm
