### ISSUE TITLE
can't add a user on couchbase

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1634]
2019-05-06 17:58:55,362 TRACE [qtp804611486-1240] [org.gluu.oxtrust.exception.GlobalExceptionHandler] (GlobalExceptionHandler.java:58) - //opt/jetty-9.4/temp/jetty-localhost-8082-identity.war-_identity-any-7144300125304534974.dir/webapp/WEB-INF/incl/person/userForm.xhtml @324,29 rendered="#{_custAttr.adminCanEdit and _custAttr.metadata.oxMultivaluedAttribute.value and _valueIdx == 0}": Property [value] not found on type [java.lang.Boolean]
javax.el.PropertyNotFoundException: //opt/jetty-9.4/temp/jetty-localhost-8082-identity.war-_identity-any-7144300125304534974.dir/webapp/WEB-INF/incl/person/userForm.xhtml @324,29 rendered="#{_custAttr.adminCanEdit and _custAttr.metadata.oxMultivaluedAttribute.value and _valueIdx == 0}": Property [value] not found on type [java.lang.Boolean]
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:111) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.component.UIComponentBase.isRendered(UIComponentBase.java:458) ~[javax.faces-2.2.16.jar:2.2.16]
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:297) ~[javax.faces-2.2.16.jar:2.2.16]
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[javax.faces-2.2.16.jar:2.2.16]
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304) ~[javax.faces-2.2.16.jar:2.2.16]
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[javax.faces-2.2.16.jar:2.2.16]
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304) ~[javax.faces-2.2.16.jar:2.2.16]
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856) ~[javax.faces-2.2.16.jar:2.2.16]
	at com.sun.faces.renderkit.html_basic.CompositeRenderer.encodeChildren(CompositeRenderer.java:78) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856) ~[javax.faces-2.2.16.jar:2.2.16]
	at org.richfaces.renderkit.html.RepeatRenderer$1.process(RepeatRenderer.java:57) ~[richfaces-a4j-4.5.17-gluu.Final.jar:4.5.17-gluu.Final]
	at org.ajax4jsf.model.SequenceDataModel.walk(SequenceDataModel.java:66) ~[richfaces-core-4.5.17-gluu.Final.jar:4.5.17-gluu.Final]
	at org.richfaces.component.UIDataAdaptor.walk(UIDataAdaptor.java:817) ~[richfaces-a4j-4.5.17-gluu.Final.jar:4.5.17-gluu.Final]
	at org.richfaces.renderkit.html.RepeatRenderer.encodeChildren(RepeatRenderer.java:70) ~[richfaces-a4j-4.5.17-gluu.Final.jar:4.5.17-gluu.Final]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[javax.faces-2.2.16.jar:2.2.16]
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304) ~[javax.faces-2.2.16.jar:2.2.16]
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856) ~[javax.faces-2.2.16.jar:2.2.16]
	at org.richfaces.renderkit.html.RepeatRenderer$1.process(RepeatRenderer.java:57) ~[richfaces-a4j-4.5.17-gluu.Final.jar:4.5.17-gluu.Final]
	at org.ajax4jsf.model.SequenceDataModel.walk(SequenceDataModel.java:66) ~[richfaces-core-4.5.17-gluu.Final.jar:4.5.17-gluu.Final]
	at org.richfaces.component.UIDataAdaptor.walk(UIDataAdaptor.java:817) ~[richfaces-a4j-4.5.17-gluu.Final.jar:4.5.17-gluu.Final]
	at org.richfaces.renderkit.html.RepeatRenderer.encodeChildren(RepeatRenderer.java:70) ~[richfaces-a4j-4.5.17-gluu.Final.jar:4.5.17-gluu.Final]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[javax.faces-2.2.16.jar:2.2.16]
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304) ~[javax.faces-2.2.16.jar:2.2.16]
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:176) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[javax.faces-2.2.16.jar:2.2.16]
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304) ~[javax.faces-2.2.16.jar:2.2.16]
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859) ~[javax.faces-2.2.16.jar:2.2.16]
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:456) ~[javax.faces-2.2.16.jar:2.2.16]
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134) ~[javax.faces-2.2.16.jar:2.2.16]
	at org.ocpsoft.rewrite.faces.RewriteViewHandler.renderView(RewriteViewHandler.java:196) ~[rewrite-integration-faces-3.4.2.Final.jar:3.4.2.Final]
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337) ~[javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337) ~[javax.faces-2.2.16.jar:2.2.16]
	at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:119) ~[omnifaces-2.6.9.jar:2.6.9]
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120) ~[javax.faces-2.2.16.jar:2.2.16]
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [javax.faces-2.2.16.jar:2.2.16]
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219) [javax.faces-2.2.16.jar:2.2.16]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659) [javax.faces-2.2.16.jar:2.2.16]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226) [rewrite-servlet-3.4.2.Final.jar:3.4.2.Final]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) [jetty-security-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:203) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:73) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.ocpsoft.rewrite.servlet.impl.HttpRewriteResultHandler.handleResult(HttpRewriteResultHandler.java:42) [rewrite-servlet-3.4.2.Final.jar:3.4.2.Final]
	at org.ocpsoft.rewrite.servlet.RewriteFilter.rewrite(RewriteFilter.java:297) [rewrite-servlet-3.4.2.Final.jar:3.4.2.Final]
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:198) [rewrite-servlet-3.4.2.Final.jar:3.4.2.Final]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.Server.handle(Server.java:503) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: javax.el.PropertyNotFoundException: Property [value] not found on type [java.lang.Boolean]
	at javax.el.BeanELResolver$BeanProperties.get(BeanELResolver.java:260) ~[org.mortbay.jasper.apache-el-8.5.24.2.jar:8.5.24]
	at javax.el.BeanELResolver$BeanProperties.access$300(BeanELResolver.java:212) ~[org.mortbay.jasper.apache-el-8.5.24.2.jar:8.5.24]
	at javax.el.BeanELResolver.property(BeanELResolver.java:347) ~[org.mortbay.jasper.apache-el-8.5.24.2.jar:8.5.24]
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:92) ~[org.mortbay.jasper.apache-el-8.5.24.2.jar:8.5.24]
	at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176) ~[javax.faces-2.2.16.jar:2.2.16]
	at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203) ~[javax.faces-2.2.16.jar:2.2.16]
	at org.apache.el.parser.AstValue.getValue(AstValue.java:169) ~[org.mortbay.jasper.apache-el-8.5.24.2.jar:8.5.24]
	at org.apache.el.parser.AstAnd.getValue(AstAnd.java:42) ~[org.mortbay.jasper.apache-el-8.5.24.2.jar:8.5.24]
	at org.apache.el.parser.AstAnd.getValue(AstAnd.java:37) ~[org.mortbay.jasper.apache-el-8.5.24.2.jar:8.5.24]
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184) ~[org.mortbay.jasper.apache-el-8.5.24.2.jar:8.5.24]
	at org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50) ~[weld-web-3.0.5.Final.jar:3.0.5.Final]
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109) ~[javax.faces-2.2.16.jar:2.2.16]
	... 108 more

**Comment by mbaser** [comment]
On CentOS7, build 36, I have no issues adding users
![Screenshot_2019-05-06_20-53-55](https://user-images.githubusercontent.com/6398752/57244486-222bed00-7041-11e9-9ed9-c8cd674b3270.png)

**Comment by syntrydy** [comment]
That is because you don't have the latest code.  In latest code oxMultivalueAttribute is now a Boolean
