### ISSUE TITLE
Missing saml-nameid.properties.vm template

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#1660]
On latest build we get:
```
2019-05-21 19:47:34,963 ERROR [ForkJoinPool.commonPool-worker-4] [org.gluu.oxtrust.ldap.service.TemplateService] (TemplateService.java:56) - Failed to load velocity template 'saml-nameid.properties'
org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'saml-nameid.properties.vm'
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:462) ~[velocity-engine-core-2.0.jar:2.0]
	at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:343) ~[velocity-engine-core-2.0.jar:2.0]
	at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1554) ~[velocity-engine-core-2.0.jar:2.0]
	at org.apache.velocity.runtime.RuntimeSingleton.getTemplate(RuntimeSingleton.java:293) ~[velocity-engine-core-2.0.jar:2.0]
	at org.apache.velocity.app.Velocity.mergeTemplate(Velocity.java:258) ~[velocity-engine-core-2.0.jar:2.0]
	at org.gluu.oxtrust.ldap.service.TemplateService.generateConfFile(TemplateService.java:54) [classes/:?]
	at org.gluu.oxtrust.ldap.service.TemplateService$Proxy$_$$_WeldClientProxy.generateConfFile(Unknown Source) [classes/:?]
	at org.gluu.oxtrust.ldap.service.Shibboleth3ConfService.generateConfigurationFiles(Shibboleth3ConfService.java:214) [classes/:?]
	at org.gluu.oxtrust.ldap.service.MetadataValidationTimer.regenerateConfigurationFiles(MetadataValidationTimer.java:146) [classes/:?]
```

**Comment by malotian** [comment]
It's already there
https://github.com/GluuFederation/oxTrust/blob/master/configuration/template/shibboleth3/idp/saml-nameid.properties.vm
