### ISSUE TITLE
Unable to Update/Delete Trust relationships

### ISSUE THREAD

**Issue by malotian** [GluuFederation/oxTrust#1710]
## Describe the issue
Unable to Update/Delete/Deactivate Trust Relationship (once created)

## Steps To Reproduce
install latest from repo (like I did gluu-server-4.0_1-55~bionic+Ub18.04_amd64.deb )
create TR
try Update/Delete/Deactivate

## Stacktrace
2019-07-07 21:33:27,416 INFO  [qtp985655350-18] [org.gluu.oxtrust.action.UpdateTrustRelationshipAction] (UpdateTrustRelationshipAction.java:393) - Download metadata for TR samltest.id  : result   :  true
2019-07-07 21:33:27,434 ERROR [qtp985655350-18] [org.gluu.oxtrust.action.UpdateTrustRelationshipAction] (UpdateTrustRelationshipAction.java:365) - Failed to update trust relationship 03f89f19-97a1-4803-8dde-d2c553e67803
org.gluu.persist.exception.EntryPersistenceException: Failed to persist entry: inum=03f89f19-97a1-4803-8dde-d2c553e67803,ou=trustRelationships,o=gluu
        at org.gluu.persist.ldap.impl.LdapEntryManager.persist(LdapEntryManager.java:185) ~[oxcore-persistence-ldap-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.persist.impl.BaseEntryManager.persist(BaseEntryManager.java:98) ~[oxcore-persistence-core-4.0.0-SNAPSHOT.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.gluu.persist.EntityManager$PersistenceEntryManager$479440844$Proxy$_$$_WeldClientProxy.persist(Unknown Source) ~[weld-core-impl-3.1.1.Final.jar:?]
        at org.gluu.oxtrust.ldap.service.TrustService.updateTrustRelationship(TrustService.java:104) ~[classes/:?]
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction.saveTR(UpdateTrustRelationshipAction.java:544) ~[classes/:?]
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction.saveImpl(UpdateTrustRelationshipAction.java:363) [classes/:?]
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction$Proxy$_$$_WeldSubclass.saveImpl(Unknown Source) [classes/:?]
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction.save(UpdateTrustRelationshipAction.java:265) [classes/:?]
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction$Proxy$_$$_WeldSubclass.save$$super(Unknown Source) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.gluu.service.security.SecurityInterceptor.invoke(SecurityInterceptor.java:55) [oxcore-service-4.0.0-SNAPSHOT.jar:?]
        at sun.reflect.GeneratedMethodAccessor100.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) [weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84) [weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72) [weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56) [weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79) [weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68) [weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.gluu.oxtrust.action.UpdateTrustRelationshipAction$Proxy$_$$_WeldSubclass.save(Unknown Source) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.apache.el.parser.AstValue.invoke(AstValue.java:247) [org.mortbay.jasper.apache-el-8.5.24.2.jar:8.5.24]
        at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267) [org.mortbay.jasper.apache-el-8.5.24.2.jar:8.5.24]
        at org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40) [weld-web-3.1.1.Final.jar:3.1.1.Final]
        at org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50) [weld-web-3.1.1.Final.jar:3.1.1.Final]
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105) [javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87) [javax.faces-2.2.16.jar:2.2.16]
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102) [javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.component.UICommand.broadcast(UICommand.java:315) [javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790) [javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282) [javax.faces-2.2.16.jar:2.2.16]
        at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81) [javax.faces-2.2.16.jar:2.2.16]
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [javax.faces-2.2.16.jar:2.2.16]
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198) [javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658) [javax.faces-2.2.16.jar:2.2.16]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215) [websocket-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.Server.handle(Server.java:503) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: org.gluu.persist.exception.operation.DuplicateEntryException: Entry already exists
        at org.gluu.persist.ldap.operation.impl.LdapOperationsServiceImpl.addEntryImpl(LdapOperationsServiceImpl.java:717) ~[oxcore-persistence-ldap-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.persist.ldap.operation.impl.LdapOperationsServiceImpl.addEntry(LdapOperationsServiceImpl.java:700) ~[oxcore-persistence-ldap-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.persist.ldap.impl.LdapEntryManager.persist(LdapEntryManager.java:178) ~[oxcore-persistence-ldap-4.0.0-SNAPSHOT.jar:?]
        ... 84 more
2019-07-07 21:34:08,339 ERROR [qtp985655350-13627] [org.gluu.oxtrust.action.UpdateTrustRelationshipAction] (UpdateTrustRelationshipAction.java:724) - Failed to remove federation trust relationship 03f89f19-97a1-4803-8dde-d2c553e67803, there are still active federated Trust Relationships left.
2019-07-07 21:34:08,355 INFO  [qtp985655350-13627] [org.gluu.oxtrust.ldap.service.Shibboleth3ConfService] (Shibboleth3ConfService.java:171) - >>>>>>>>>> IN Shibboleth3ConfService.generateConfigurationFiles()...
2019-07-07 21:34:08,423 INFO  [qtp985655350-13627] [org.gluu.oxtrust.ldap.service.CASService] (CASService.java:53) - loadCASConfiguration() call
2019-07-07 21:34:08,642 INFO  [qtp985655350-13627] [org.gluu.oxtrust.ldap.service.Shibboleth3ConfService] (Shibboleth3ConfService.java:254) - >>>>>>>>>> LEAVING Shibboleth3ConfService.generateConfigurationFiles()...
2019-07-07 21:34:20,178 ERROR [Thread-6744] [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] (MetadataValidationTimer.java:105) - Exception happened while reloading application configuration
org.gluu.persist.exception.EntryPersistenceException: Failed to persist entry: inum=03f89f19-97a1-4803-8dde-d2c553e67803,ou=trustRelationships,o=gluu
        at org.gluu.persist.ldap.impl.LdapEntryManager.persist(LdapEntryManager.java:185) ~[oxcore-persistence-ldap-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.persist.impl.BaseEntryManager.persist(BaseEntryManager.java:98) ~[oxcore-persistence-core-4.0.0-SNAPSHOT.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.gluu.persist.EntityManager$PersistenceEntryManager$479440844$Proxy$_$$_WeldClientProxy.persist(Unknown Source) ~[weld-core-impl-3.1.1.Final.jar:?]
        at org.gluu.oxtrust.ldap.service.TrustService.updateTrustRelationship(TrustService.java:104) ~[classes/:?]
        at org.gluu.oxtrust.ldap.service.MetadataValidationTimer.validateMetadata(MetadataValidationTimer.java:179) ~[classes/:?]
        at org.gluu.oxtrust.ldap.service.MetadataValidationTimer.procesMetadataValidation(MetadataValidationTimer.java:113) ~[classes/:?]
        at org.gluu.oxtrust.ldap.service.MetadataValidationTimer.processMetadataValidationTimerEvent(MetadataValidationTimer.java:103) [classes/:?]
        at org.gluu.oxtrust.ldap.service.MetadataValidationTimer$Proxy$_$$_WeldSubclass.processMetadataValidationTimerEvent$$super(Unknown Source) [classes/:?]
        at sun.reflect.GeneratedMethodAccessor503.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.gluu.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:36) [oxcore-service-4.0.0-SNAPSHOT.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: org.gluu.persist.exception.operation.DuplicateEntryException: Entry already exists
        at org.gluu.persist.ldap.operation.impl.LdapOperationsServiceImpl.addEntryImpl(LdapOperationsServiceImpl.java:717) ~[oxcore-persistence-ldap-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.persist.ldap.operation.impl.LdapOperationsServiceImpl.addEntry(LdapOperationsServiceImpl.java:700) ~[oxcore-persistence-ldap-4.0.0-SNAPSHOT.jar:?]
        at org.gluu.persist.ldap.impl.LdapEntryManager.persist(LdapEntryManager.java:178) ~[oxcore-persistence-ldap-4.0.0-SNAPSHOT.jar:?]
        ... 21 more

**Comment by malotian** [comment]
Just as additional info - issue seems to be here(oxTrust\server\src\main\java\org\gluu\oxtrust\ldap\service\TrustService.java),
instead of if block, control is it is going to else block.

```
	public void updateTrustRelationship(GluuSAMLTrustRelationship trustRelationship) {
		log.debug("Updating TR: {}", trustRelationship.getInum());
		String dn = trustRelationship.getDn();

		if (containsTrustRelationship(dn)) {
			log.trace("Updating TR: {}", dn);
			ldapEntryManager.merge(trustRelationship);
		} else {
			log.trace("Adding TR: {}", dn);
			ldapEntryManager.persist(trustRelationship);
		}
	}
```

**Comment by sahiliamsso** [comment]
@mlotian - Please try deleting after deactivating it.  @syntrydy to add a warning/info message.

**Comment by malotian** [comment]
@sahiliamsso actually deactivating is also like update only, so you won't be able to do that even.

**Comment by cybersei** [comment]
I've done a QA run of the latest build (July 10) on RHEL 7 and the Shibboleth files generated by the template are empty after activating the provider, so it does not work at all except the UI shows it's active and SP metadata file is saved.

**Comment by nynymike** [comment]
We don't actually support code before it's released.

**Comment by cybersei** [comment]
I know but I thought I would let you know since I am QAing it ... I do not
expect support since I commented on the GitHub Issue instead

- Pawel

**Comment by syntrydy** [comment]
@cybersei thanks for reporting.

This is actually related to something else. This issue is about adding/update/delete TR, not metadata generation.
Closing this now. As @nynymike said, We don't actually support code before it's released.

Thanks!
