### ISSUE TITLE
Gluu 4.0 QA: Supplied key (null) is not a RSAPrivateKey instance

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1744]
## Describe the issue
response_type=token+id_token returns blank page and "Supplied key (null) is not a RSAPrivateKey instance" error in oxauth logs 

## Steps To Reproduce
Register openid client to use token and id_token and access URL
https://{host}/oxauth/restv1/authorize?scope=openid+profile+email&response_type=token+id_token&session_id=5e8a568f-6be1-4e84-96f6-3d9f69d2ed71&redirect_uri=https%3A%2F%2Flocalhost%2Fopenid%2Fjavascript-sample%2Flogin-callback.html&state=1ua27zh&nonce=1brf5ah&client_id={client_id}

## Expected behavior
User should redirect to redirect_url
## Actual behavior
Blank page appears

## Desktop (please complete the following information):
 - OS: CentOS7.3
 - Gluu version(If applicable) : 4.0 Beta2
 - Casa version(If applicable)

Oxauth logs
```
2019-07-29 12:37:53,264 ERROR [qtp1749186397-4142] [org.gluu.oxauth.model.common.AuthorizationGrant] (AuthorizationGrant.java:266) - Supplied key (null) is not a RSAPrivateKey instance
java.security.InvalidKeyException: Supplied key (null) is not a RSAPrivateKey instance
        at org.bouncycastle.jcajce.provider.asymmetric.rsa.DigestSignatureSpi.engineInitSign(Unknown Source) ~[bcprov-jdk15on-1.54.jar:1.54.0]
        at java.security.Signature$Delegate.engineInitSign(Signature.java:1177) ~[?:1.8.0_221]
        at java.security.Signature.initSign(Signature.java:530) ~[?:1.8.0_221]
        at org.gluu.oxauth.model.crypto.OxAuthCryptoProvider.sign(OxAuthCryptoProvider.java:217) ~[oxauth-model-4.0.b1.jar:?]
        at org.gluu.oxauth.model.crypto.AbstractCryptoProvider$Proxy$_$$_WeldClientProxy.sign(Unknown Source) ~[oxauth-model-4.0.b1.jar:?]
        at org.gluu.oxauth.model.token.JwtSigner.sign(JwtSigner.java:86) ~[classes/:?]
        at org.gluu.oxauth.model.token.IdTokenFactory.generateSignedIdToken(IdTokenFactory.java:288) ~[classes/:?]
        at org.gluu.oxauth.model.token.IdTokenFactory.createJwr(IdTokenFactory.java:530) ~[classes/:?]
        at org.gluu.oxauth.model.common.AuthorizationGrant.createIdToken(AuthorizationGrant.java:96) ~[classes/:?]
        at org.gluu.oxauth.model.common.AuthorizationGrant.createIdToken(AuthorizationGrant.java:251) ~[classes/:?]
        at org.gluu.oxauth.authorize.ws.rs.AuthorizeRestWebServiceImpl.requestAuthorization(AuthorizeRestWebServiceImpl.java:596) ~[classes/:?]
        at org.gluu.oxauth.authorize.ws.rs.AuthorizeRestWebServiceImpl
```

**Comment by yuriyz** [comment]
Issue appears because on ce-dev4 by default keys were not re-generated by oxauth (Mustafa corrected it already and it should be available in next build). For now as discussed in chat, please update your keystore file and persistence as described here:
https://github.com/GluuFederation/support-docs/blob/master/troubleshooting/oxAuth/oxAuth_key_regeneration.md
