### ISSUE TITLE
Gluu 4.0 QA - Error opening Federation TR

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1768]
## Describe the issue
Unable to open Federation TR which is created using incommon metadata

## Steps To Reproduce
1. Go to SAML > Add Trust Relationships
2. Create TR of Entity Type "Federation/Aggregate" and upload incommon metadata
3. Click Add button
4. Wait for the TR activation
5. Click on Trust Relationship

## Expected behavior
It should open TR

## Actual behavior
Getting OOPS error page

## Screenshots
![TRIssue](https://user-images.githubusercontent.com/21104811/62989436-e8c00600-be15-11e9-9490-8f202ddec307.gif)

Also, TR validation Status is **"Validation Failed"** but Status shows **Active**

## Desktop (please complete the following information):
 - OS: Ubuntu1804
 - Gluu version 4.0 Beta2

Oxtrust logs
```
2019-08-14 01:47:22,588 TRACE [qtp105704967-16] [org.gluu.oxtrust.service.PermissionService] (PermissionService.java:73) - Checking permissions for target 'trust' an 'action'. Identity: access
2019-08-14 01:47:22,602 TRACE [qtp105704967-16] [org.gluu.oxtrust.exception.GlobalExceptionHandler] (GlobalExceptionHandler.java:58) - Argument Error: Parameter text is null
java.lang.NullPointerException: Argument Error: Parameter text is null
        at com.sun.faces.renderkit.html_basic.HtmlResponseWriter.writeText(HtmlResponseWriter.java:949) ~[javax.faces-2.2.16.jar:2.2.16]
        at net.bootsfaces.component.tabView.TabViewRenderer.encodeTabAnchorTag(TabViewRenderer.java:585) ~[bootsfaces-1.4.1.jar:1.4.1]
        at net.bootsfaces.component.tabView.TabViewRenderer.encodeTab(TabViewRenderer.java:547) ~[bootsfaces-1.4.1.jar:1.4.1]
        at net.bootsfaces.component.tabView.TabViewRenderer.access$200(TabViewRenderer.java:43) ~[bootsfaces-1.4.1.jar:1.4.1]
        at net.bootsfaces.component.tabView.TabViewRenderer$2.run(TabViewRenderer.java:479) ~[bootsfaces-1.4.1.jar:1.4.1]
        at net.bootsfaces.component.tabView.TabViewRenderer.encodeTabs(TabViewRenderer.java:490) ~[bootsfaces-1.4.1.jar:1.4.1]
        at net.bootsfaces.component.tabView.TabViewRenderer.encodeTabLinks(TabViewRenderer.java:323) ~[bootsfaces-1.4.1.jar:1.4.1]
        at net.bootsfaces.component.tabView.TabViewRenderer.encodeBegin(TabViewRenderer.java:185) ~[bootsfaces-1.4.1.jar:1.4.1]
        at javax.faces.component.UIComponentBase.encodeBegin(UIComponentBase.java:865) ~[javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1854) ~[javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859) ~[javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.render.Renderer.encodeChildren(Renderer.java:176) ~[javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856) ~[javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859) ~[javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859) ~[javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1859) ~[javax.faces-2.2.16.jar:2.2.16]
        at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:456) ~[javax.faces-2.2.16.jar:2.2.16]
        at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134) ~[javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337) ~[javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337) ~[javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337) ~[javax.faces-2.2.16.jar:2.2.16]
        at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:119) ~[omnifaces-2.6.9.jar:2.6.9]
        at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120) ~[javax.faces-2.2.16.jar:2.2.16]
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [javax.faces-2.2.16.jar:2.2.16]
        at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219) [javax.faces-2.2.16.jar:2.2.16]
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659) [javax.faces-2.2.16.jar:2.2.16]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:868) [jetty-servlet-9.4.19.v20190610.jar:9.4.19.v20190610]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623) [jetty-servlet-9.4.19.v20190610.jar:9.4.19.v20190610]
```

**Comment by syntrydy** [comment]
@sahiliamsso the gif added to this issue is somehow useless. We need gif showing the whole process meaning (from adding TR to error).

**Comment by sahiliamsso** [comment]
updated
![TRIssue_1](https://user-images.githubusercontent.com/21104811/63024146-9feb6a00-be74-11e9-8c39-a8a9c790cf52.gif)

**Comment by syntrydy** [comment]
@sahiliamsso this is fixed
