### ISSUE TITLE
Some issue with federation metadata periodic re-validation.

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#1840]
gluu-server-4.0-82.rc1.centos7 (Backend: OpendDJ)

## Description
As far as I can tell, updated metadata isn't picked up by oxTrust.

## Steps To Reproduce

1. Create a federation TR using some not very heavy federation metadata. I would suggest using combined Samltest metadata available [here](https://samltest.id/saml/providers), as it's formatted as federation metadata and is very light. To stay close to real-world use case, use "URI" method while supplying the metadata

2. Wait until metadata is fully validated, and dump this TR's LDAP entry to use as a reference in the future; if it's the only fed TR you have in your setup, this filter will help: `'&(objectclass=gluusamlconfig)(gluuisfederation=true)'`

3. Manually download some other, **completely different** (to make comparison easier later on) fed metadata into the container; I would suggest to use Carsi, as it's lighter than InCommon, here is [direct link](https://www.carsi.edu.cn/carsimetadata/carsifed-metadata.xml)

4. Under `/opt/shibboleth-idp/metadata/` find the metadata of your current fed TR created on step 1); copy it to back up location if needed, then overwrite it with the new metadata you got on step 3)

5. Change "loggingLevel" to DEBUG for oxTrust, then tail its log and wait for re-validation event(s): `# tail -F /opt/gluu/jetty/identity/logs/oxtrust.log | grep -i validat`

6. Search for your fed LDAP entry again using the same filter as before; try to create some child TR based on this fed TR, so you could check a list of entities associated with this fed TR

## Expected behavior

In Gluu Server, when metadata is supplied by URI, "FileBackedHTTPMetadataProvider" element is pushed to `metadata-providers.xml`, comparing to "FilesystemMetadataProvider" element pushed for cases where File method is used. That element instructs IDP to re-fresh metadata with a certain interval.

oxTrust should also check all SAML TR's metadata files on disk, re-validating them, and if changes were found (due to the fact IDP fetched a new metadata), they need to be accordingly mirrored in corresponding LDAP entries by it. That is particularly important for fed TRs, as new metadata may come with list of participating entities changed, and if oxTrust won't pickup those changes, web UI will allow to create child TRs for non-existing entities, or use wrong `entityid`-s of existing ones (in case they've been changed recently).

## Actual behavior

After metadata is substituted on step 4), oxTrust never picks up that change. If the same LDAP search is executed for the federation TR's entry that was done on step 2), it will contain the same set of `gluuEntityId` attributes the initial federation had. Restarting "identity" doesn't make it to parse the new metadata either. In 3.1.6 there is no such issue, and new metadata is picked up by oxTrust.

In addition, strange log records appear in `oxtrust.log`:
```
2019-09-20 11:00:40,863 DEBUG [Thread-5258] [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] (MetadataValidationTimer.java:113) - Starting metadata validation
2019-09-20 11:00:40,863 DEBUG [Thread-5258] [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] (MetadataValidationTimer.java:119) - Metadata validation finished with result: 'false'
```
It's always "false" result, though all TRs are active and working. The only time it's "true" is when the TR is created and validated initially. I also see it constantly returns "false" in 3.1.6 too, though the issue described here doesn't happen there. So it makes me wonder what purpose does this log message serve? We may need to review it and make it correlate with actual validation results.

**Comment by aliaksander-samuseu** [comment]
@syntrydy 
It's not only about fed TRs, but also affects single SP TRs.

**Comment by aliaksander-samuseu** [comment]
@syntrydy 

I've tried to test it with the snapshot WAR, but so far no luck. When I substituted original Shibtest metadat with Carsi metadata, no changes can be observed for this fed TR neither in web UI, nor in its LDAP entry. In `oxtrust.log` there was an error message soon after I did the substitution:
```
2019-09-23 18:57:12,420 ERROR [Thread-536] [org.gluu.oxtrust.ldap.service.EntityIDMonitoringService] (EntityIDMonitoringService.java:92) - Exc
eption happened while monitoring EntityId
java.lang.NullPointerException: null
        at java.util.TreeMap.getEntry(TreeMap.java:347) ~[?:1.8.0_222]
        at java.util.TreeMap.containsKey(TreeMap.java:232) ~[?:1.8.0_222]
        at java.util.TreeSet.contains(TreeSet.java:234) ~[?:1.8.0_222]
        at org.gluu.oxtrust.ldap.service.EntityIDMonitoringService.process(EntityIDMonitoringService.java:126) ~[classes/:?]
        at org.gluu.oxtrust.ldap.service.EntityIDMonitoringService$Proxy$_$$_WeldSubclass.process(Unknown Source) ~[classes/:?]
        at org.gluu.oxtrust.ldap.service.EntityIDMonitoringService.processMetadataValidationTimerEvent(EntityIDMonitoringService.java:90) [cla
sses/:?]
        at org.gluu.oxtrust.ldap.service.EntityIDMonitoringService$Proxy$_$$_WeldSubclass.processMetadataValidationTimerEvent$$super(Unknown S
ource) [classes/:?]
        at sun.reflect.GeneratedMethodAccessor663.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:5
1) [weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.1.1
.Final.jar:3.1.1.Final]
        at org.gluu.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:36) [oxcore-service-4.0.0-SNAPSHOT.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_222]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
2019-09-23 18:57:12,453 DEBUG [oxTrustScheduler_Worker-4] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:53) - Bound req
uest started
```
No idea whether it's related.

Also, I still see this message popping up in logs after each validation attempt:
```
2019-09-23 18:45:12,397 DEBUG [Thread-397] [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] (MetadataValidationTimer.java:119) - Metadata validation finished with result: 'false'
2019-09-23 18:46:12,396 DEBUG [oxTrustScheduler_Worker-5] [org.gluu.service.timer.TimerJob] (TimerJob.java:36) - Fire timer event [org.gluu.oxtrust.service.cdi.event.MetadataValidationEvent] with qualifiers [@org.gluu.service.cdi.event.Scheduled()] from instance 911465105
2019-09-23 18:46:12,397 DEBUG [Thread-411] [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] (MetadataValidationTimer.java:113) - Starting metadata validation
2019-09-23 18:46:12,397 DEBUG [Thread-411] [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] (MetadataValidationTimer.java:119) - Metadata validation finished with result: 'false'
2019-09-23 18:47:12,395 DEBUG [oxTrustScheduler_Worker-1] [org.gluu.service.timer.TimerJob] (TimerJob.java:36) - Fire timer event [org.gluu.oxtrust.service.cdi.event.MetadataValidationEvent] with qualifiers [@org.gluu.service.cdi.event.Scheduled()] from instance 651284413
2019-09-23 18:47:12,396 DEBUG [Thread-421] [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] (MetadataValidationTimer.java:113) - Starting metadata validation
```
That's from before I did the substitution, after the original metadata was successfully validated, and TR was functional. It doesn't make much sense to me. Why is it always "false"? Is it broken? It doesn't help to assess the validation process.
