### ISSUE TITLE
Gluu 4.0 QA | Unable to display admin user

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1852]
!!! Note 
Unable to display admin user

## Steps To Reproduce
1. Go to Manage Users
2. Search for "Admin"
3. Click on Admin username to display attributes

## Expected behavior
Detailed page should be displayed

## Actual behavior
Nothing appears on the screen

## Screenshots
![user](https://user-images.githubusercontent.com/21104811/65737160-9f690480-e0ab-11e9-9be2-a3f5d942f13a.gif)

Build 4.0-90.rc2.centos7 on CentOS 7.5

Oxtrust logs
```
2019-09-27 02:01:03,701 WARN  [qtp105704967-15] [org.gluu.oxtrust.ldap.service.AttributeService] (AttributeService.java:471) - Failed to find attribute 'oxLastLogonTime' metadata
2019-09-27 02:01:03,712 ERROR [qtp105704967-15] [org.gluu.oxtrust.action.UpdatePersonAction] (UpdatePersonAction.java:286) - null
java.lang.NullPointerException: null
        at org.gluu.oxtrust.action.UpdatePersonAction.addFidoDevices(UpdatePersonAction.java:416) ~[classes/:?]
        at org.gluu.oxtrust.action.UpdatePersonAction.update(UpdatePersonAction.java:281) [classes/:?]
        at org.gluu.oxtrust.action.UpdatePersonAction$Proxy$_$$_WeldSubclass.update$$super(Unknown Source) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.gluu.service.security.SecurityInterceptor.invoke(SecurityInterceptor.java:55) [oxcore-service-4.0.rc2.jar:?]
        at sun.reflect.GeneratedMethodAccessor311.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) [weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84) [weld-core-impl-3.1.1.Final.jar:3.1.1.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72) [weld-core-impl-3.1.1.Final.jar:3.1.1.Final]

```

**Comment by sahiliamsso** [comment]
to add, this happens after using U2F token for the user
