### ISSUE TITLE
Cannot remove oxExternalUid in UpdatePersonAction

### ISSUE THREAD

**Issue by rkondratenko** [GluuFederation/oxTrust#1856]
When removing oxExternalUid via updatePerson web page the following exception happens:

`2019-10-02 09:17:27,355 ERROR [qtp105704967-13] [org.gluu.oxtrust.action.UpdatePersonAction] (UpdatePersonAction.java:799) - Failed to remove device 
java.lang.UnsupportedOperationException: null
        at java.util.AbstractList.remove(AbstractList.java:161) ~[?:1.8.0_222]
        at java.util.AbstractList$Itr.remove(AbstractList.java:374) ~[?:1.8.0_222]
        at java.util.AbstractCollection.remove(AbstractCollection.java:293) ~[?:1.8.0_222]
        at org.gluu.oxtrust.action.UpdatePersonAction.removeOxExternalUid(UpdatePersonAction.java:809) ~[classes/:?]
        at org.gluu.oxtrust.action.UpdatePersonAction.removeDevice(UpdatePersonAction.java:795) [classes/:?]
        at org.gluu.oxtrust.action.UpdatePersonAction$Proxy$_$$_WeldSubclass.removeDevice$$super(Unknown Source) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
...
`
The attribute is removed from the web page but stays in LDAP. On page reload it reappears.
The LDAP record is:
`
dn: inum=3944fffa-74f4-4f6c-9c9b-86207161bca8,ou=people,o=gluu
objectClass: top
objectClass: eduPerson
objectClass: gluuCustomPerson
objectClass: gluuPerson
inum: 3944fffa-74f4-4f6c-9c9b-86207161bca8
oxLastLogonTime: 20191002090811.785Z
updatedAt: 20191002085347.569Z
oxExternalUid: wwpass:87c00ab7322a375d8fcda669bd5f4303
oxExternalUid: wwpass:9e46779cff72bb50e17a66f361737be8
zoneinfo: America/Los_Angeles
phoneNumberVerified: true
gluuSLAManager: true
userPassword: {SSHA}WdMhcdVPe5BK+u7XwuDZsuBb92exI4LR
mail: admin@iam.wwpass.net
givenName: Admin
telephoneNumber: 555-1212
emailVerified: true
website: https://www.gluu.org/
birthdate: 20170907000000.000Z
gender: male
preferredUsername: admin
oxTrustEmail: {"value":"admin@iam.wwpass.net","display":null,"type":null,"primary":false}
memberOf: inum=60B7,ou=groups,o=gluu
picture: https://www.gluu.org/wp-content/themes/gluu/images/gl.png
displayName: Default Admin User
profile: https://www.facebook.com/gluufederation/
c: US
gluuStatus: active
sn: User
nickname: Admin
middleName: Admin
uid: admin
`
Also accessing this attribute generete other exceptions in:  `org.gluu.oxtrust.ldap.service.Fido2DeviceService.removeFido2` and `org.gluu.oxtrust.ldap.service.Fido2DeviceService.findAllFido2Devices` as relevant entries with `ou=fido2_register` are not in LDAP. These exceptions do not cause any apparent problems, though.

**Comment by syntrydy** [comment]
@rkondratenko closing this issue because it doesn't follow the issue creation template.
Thanks!

**Comment by willow9886** [comment]
Please open on https://support.gluu.org

**Comment by rkondratenko** [comment]
@willow9886 Done that already. And it appears to be fixed between RC1 and RC2 already. Thank you!
