### ISSUE TITLE
Gluu 4.1 QA - Cache Refresh throwing exception with hybrid backend

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#1899]
##Describe the issue
Cache Refresh throwing exception with hybrid backend

##Pre-req
Install 4.1 with couchbase as backend db and store default in wrends
```
Install Local WrenDS Server? [Yes] :
Enter Password for LDAP Admin (cn=directory manager) [xxxxx] : xxxxx
Install Local Couchbase Server? [Yes] :
Enter Password for Couchbase admin user [xxxxx] :
  Please note that you have to update your firewall configuration to
  allow connections to the following ports:
  4369, 28091 to 28094, 9100 to 9105, 9998, 9999, 11207, 11209 to 11211,
  11214, 11215, 18091 to 18093, and from 21100 to 21299.
By using Couchbase Server you agree to the End User License Agreement.
See /opt/couchbase/LICENSE.txt.

Use WrenDS to store (1) default (2) user (3) cache (4) site (5) token : 1
```
## Steps To Reproduce
1. Enable Cache Refresh
 
## Expected behavior
Users from backend should be imported to Gluu db
## Actual behavior
Throws exception in logs

OS: CentOS 7.4
Gluu version(If applicable):4.1 with hybrid (couchbase and wrends)

oxtrust_cache_refresh.log
```
2020-01-03 16:53:22,022 ERROR [ForkJoinPool.commonPool-worker-3] [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (CacheRefreshTimer.java:204) - Exception happened while executing cache refresh synchronization
org.gluu.persist.exception.EntryPersistenceException: Failed to find entries with baseDN: ou=cache-refresh,o=site, filter: (&(&(objectClass=gluuInumMap))(&(objectClass=gluuInumMap)(!(gluuStatus=inactive))))
        at org.gluu.persist.ldap.impl.LdapEntryManager.findEntries(LdapEntryManager.java:442) ~[oxcore-persistence-ldap-4.1.0.Final.jar:?]
        at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.loadInumServerEntries(CacheRefreshTimer.java:851) ~[classes/:?]
        at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.detectChangedEntries(CacheRefreshTimer.java:371) ~[classes/:?]
        at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.processImpl(CacheRefreshTimer.java:300) ~[classes/:?]
        at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.processInt(CacheRefreshTimer.java:199) [classes/:?]
        at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer$Proxy$_$$_WeldSubclass.processInt(Unknown Source) [classes/:?]
        at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.process(CacheRefreshTimer.java:183) [classes/:?]
        at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer$Proxy$_$$_WeldSubclass.process$$super(Unknown Source) [classes/:?]
        at sun.reflect.GeneratedMethodAccessor1010.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.1.2.Final.jar:3.1.2.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.1.2.Final.jar:3.1.2.Final]
        at org.gluu.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:36) [oxcore-service-4.1.0.Final.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_222]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) [?:1.8.0_222]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_222]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_222]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_222]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_222]
Caused by: org.gluu.persist.exception.operation.SearchException: Failed to scroll to specified start
        at org.gluu.persist.ldap.operation.impl.LdapOperationsServiceImpl.searchImpl(LdapOperationsServiceImpl.java:412) ~[oxcore-persistence-ldap-4.1.0.Final.jar:?]
        at org.gluu.persist.ldap.operation.impl.LdapOperationsServiceImpl.search(LdapOperationsServiceImpl.java:305) ~[oxcore-persistence-ldap-4.1.0.Final.jar:?]
        at org.gluu.persist.ldap.impl.LdapEntryManager.findEntries(LdapEntryManager.java:439) ~[oxcore-persistence-ldap-4.1.0.Final.jar:?]
        ... 19 more
Caused by: com.unboundid.ldap.sdk.LDAPSearchException: The entry ou=cache-refresh,o=site specified as the search base does not exist in the Directory Server
        at com.unboundid.ldap.sdk.LDAPConnection.search(LDAPConnection.java:3803) ~[unboundid-ldapsdk-4.0.14.jar:4.0.14]
        at org.gluu.persist.ldap.operation.impl.LdapOperationsServiceImpl.searchImpl(LdapOperationsServiceImpl.java:382) ~[oxcore-persistence-ldap-4.1.0.Final.jar:?]
        at org.gluu.persist.ldap.operation.impl.LdapOperationsServiceImpl.search(LdapOperationsServiceImpl.java:305) ~[oxcore-persistence-ldap-4.1.0.Final.jar:?]
        at org.gluu.persist.ldap.impl.LdapEntryManager.findEntries(LdapEntryManager.java:439) ~[oxcore-persistence-ldap-4.1.0.Final.jar:?]
        ... 19 more
```

**Comment by syntrydy** [comment]
@sahiliamsso I think this is configuration issue.

**Comment by yurem** [comment]
@sahiliamsso you used next options to install CE:
```
Use WrenDS to store (1) default (2) user (3) cache (4) site (5) token : 1
```

This means that installer put `o=site` into Couchbase. Hence CR log right error messages.
In this case you need to use `Default Inum Server` on `Inum LDAP server` tab. This will instruct CR to use internal (Couchbase) to store o=site. Or you can use LDAP, but you need to import [base ](https://github.com/GluuFederation/community-edition-setup/blob/version_4.1.0/static/cache-refresh/o_site.ldif) nodes manually into it.

**Comment by yurem** [comment]
@syntrydy can you rename tab label `Inum LDAP server` to `Inum DB server` ?

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/71895649-e7d79a00-3151-11ea-9e42-253dbd8536b3.png)
