### ISSUE TITLE
Break out SCIM into a separate service

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxTrust#1930]
Take scim server impl out of oxTrust. Make SCIM a new component of Gluu

**Comment by jgomer2001** [comment]
https://github.com/GluuFederation/scim/commit/50c3f0cc8b3fe5b23d903476d19ee3613d4b8942
https://github.com/GluuFederation/scim/commit/f867b990e38442db612bd822dc8603b57554c54e
https://github.com/GluuFederation/scim/commit/f01edd31383fbdc5dac5307cbb64e3671b89ff61

**Comment by yurem** [comment]
Can we close it?

**Comment by jgomer2001** [comment]
no

**Comment by jgomer2001** [comment]
Stuck at this point @yurem , I'm giving up:

```
02-06 21:32:40.347 INFO  [qtp407697359-15] oxtrust.auth.uma.UmaPermissionService UmaPermissionService.java:123- ##### Getting UMA metadata ...
02-06 21:32:41.051 INFO  [qtp407697359-15] oxtrust.auth.uma.UmaPermissionService UmaPermissionService.java:133- ##### Getting UMA metadata ... DONE
02-06 21:32:41.976 INFO  [qtp407697359-15] oxtrust.auth.uma.ScimUmaProtectionService ScimUmaProtectionService.java:115- SCIM is protected by UMA
02-06 21:32:41.991 ERROR [qtp407697359-15] oxtrust.auth.uma.ScimUmaProtectionService ScimUmaProtectionService.java:124- null
java.lang.NullPointerException: null
	at org.gluu.oxtrust.auth.uma.UmaPermissionService.registerResourcePermission(UmaPermissionService.java:236) ~[oxtrust-service-4.2.0-SNAPSHOT.jar:?]
	at org.gluu.oxtrust.auth.uma.UmaPermissionService.prepareRegisterPermissionsResponse(UmaPermissionService.java:245) ~[oxtrust-service-4.2.0-SNAPSHOT.jar:?]
	at org.gluu.oxtrust.auth.uma.UmaPermissionService.validateRptToken(UmaPermissionService.java:200) ~[oxtrust-service-4.2.0-SNAPSHOT.jar:?]
	at org.gluu.oxtrust.auth.uma.UmaPermissionService.validateRptToken(UmaPermissionService.java:159) ~[oxtrust-service-4.2.0-SNAPSHOT.jar:?]
	at org.gluu.oxtrust.auth.uma.UmaPermissionService$Proxy$_$$_WeldClientProxy.validateRptToken(Unknown Source) ~[oxtrust-service-4.2.0-SNAPSHOT.jar:?]
	at org.gluu.oxtrust.auth.uma.BaseUmaProtectionService.processUmaAuthorization(BaseUmaProtectionService.java:168) ~[oxtrust-service-4.2.0-SNAPSHOT.jar:?]
	at org.gluu.oxtrust.auth.uma.ScimUmaProtectionService.processAuthorization(ScimUmaProtectionService.java:116) ~[oxtrust-service-4.2.0-SNAPSHOT.jar:?]
```

**Comment by jgomer2001** [comment]
Added the 2 commits above so that I can continue working on this issue
