### ISSUE TITLE
Issue starting identity service in 4.2

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#1943]
# Description

With the current oxtrust 4.2 code, the identity service is unable to start with the following error:
**java.lang.OutOfMemoryError: Java heap space**
The client executor is executed too many times, that leads to memory issue:
**2020-04-13 19:11:24,140 INFO  [qtp1590550415-13] [org.gluu.oxtrust.auth.uma.UmaPermissionService] (UmaPermissionService.java:81) - ##### Ini
tializing custom ClientExecutor...
2020-04-13 19:11:24,142 INFO  [qtp1590550415-13] [org.gluu.oxtrust.auth.uma.UmaPermissionService] (UmaPermissionService.java:92) - ##### Ini
tializing custom ClientExecutor DONE
2020-04-13 19:11:24,146 INFO  [qtp1590550415-13] [org.gluu.oxtrust.auth.uma.UmaPermissionService] (UmaPermissionService.java:81) - ##### Ini
tializing custom ClientExecutor...
2020-04-13 19:11:24,148 INFO  [qtp1590550415-13] [org.gluu.oxtrust.auth.uma.UmaPermissionService] (UmaPermissionService.java:92) - ##### Ini
tializing custom ClientExecutor DONE
2020-04-13 19:11:24,152 INFO  [qtp1590550415-13] [org.gluu.oxtrust.auth.uma.UmaPermissionService] (UmaPermissionService.java:81) - ##### Ini
tializing custom ClientExecutor...
2020-04-13 19:11:24,154 INFO  [qtp1590550415-13] [org.gluu.oxtrust.auth.uma.UmaPermissionService] (UmaPermissionService.java:92) - ##### Ini
tializing custom ClientExecutor DONE
2020-04-13 19:11:24,158 INFO  [qtp1590550415-13] [org.gluu.oxtrust.auth.uma.UmaPermissionService] (UmaPermissionService.java:81) - ##### Ini
tializing custom ClientExecutor...
2020-04-13 19:11:24,160 INFO  [qtp1590550415-13] [org.gluu.oxtrust.auth.uma.UmaPermissionService] (UmaPermissionService.java:92) - ##### Ini
tializing custom ClientExecutor DONE
2020-04-13 19:11:24,164 INFO  [qtp1590550415-13] [org.gluu.oxtrust.auth.uma.UmaPermissionService] (UmaPermissionService.java:81) - ##### Ini
tializing custom ClientExecutor...
2020-04-13 19:11:24,165 INFO  [qtp1590550415-13] [org.gluu.oxtrust.auth.uma.UmaPermissionService] (UmaPermissionService.java:92) - ##### Ini
tializing custom ClientExecutor DONE**

# logs
**java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
        at java.lang.StringBuilder.append(StringBuilder.java:136)
        at org.apache.logging.log4j.core.pattern.PlainTextRenderer.render(PlainTextRenderer.java:32)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatEntry(ThrowableProxyRenderer.java:148)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatElements(ThrowableProxyRenderer.java:92)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatThrowableProxy(ThrowableProxyRenderer.java:71)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatCause(ThrowableProxyRenderer.java:57)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatThrowableProxy(ThrowableProxyRenderer.java:74)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatCause(ThrowableProxyRenderer.java:57)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatThrowableProxy(ThrowableProxyRenderer.java:74)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatCause(ThrowableProxyRenderer.java:57)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatThrowableProxy(ThrowableProxyRenderer.java:74)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatCause(ThrowableProxyRenderer.java:57)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatThrowableProxy(ThrowableProxyRenderer.java:74)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatCause(ThrowableProxyRenderer.java:57)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatThrowableProxy(ThrowableProxyRenderer.java:74)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatCause(ThrowableProxyRenderer.java:57)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatThrowableProxy(ThrowableProxyRenderer.java:74)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatCause(ThrowableProxyRenderer.java:57)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatThrowableProxy(ThrowableProxyRenderer.java:74)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatCause(ThrowableProxyRenderer.java:57)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatThrowableProxy(ThrowableProxyRenderer.java:74)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatCause(ThrowableProxyRenderer.java:57)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatThrowableProxy(ThrowableProxyRenderer.java:74)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatCause(ThrowableProxyRenderer.java:57)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatThrowableProxy(ThrowableProxyRenderer.java:74)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatCause(ThrowableProxyRenderer.java:57)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatThrowableProxy(ThrowableProxyRenderer.java:74)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatCause(ThrowableProxyRenderer.java:57)
        at org.apache.logging.log4j.core.impl.ThrowableProxyRenderer.formatThrowableProxy(ThrowableProxyRenderer.java:74)**

**Comment by yuriyz** [comment]
@syntrydy does it work with `rptConnectionPoolUseConnectionPooling=false` ?

**Comment by syntrydy** [comment]
Fixed by @yurem.
