### ISSUE TITLE
Unable to add users after updating Java amazon-corretto-11.0.7.10.1-linux-x64 on 3.1.7

### ISSUE THREAD

**Issue by sahilarora2020** [GluuFederation/oxTrust#1981]
## Describe the issue
Unable to add users through SCIM or UI after updating Java amazon-corretto-11.0.7.10.1-linux-x64 on 3.1.7

## Steps To Reproduce
1. Create 3.1.7 setup
2. Add users manually via Oxtrust UI or SCIM Client
3. Users are added successfully
3. Follow [this ](https://gist.github.com/mzico/571ea0343b1473cd128d14af78299f5a) to update Java to amazon-corretto-11.0.7.10.1-linux-x64 
4. Try to add users via SCIM or Oxtrust UI

## Expected behavior
Users should be added successfully

## Actual behavior
Error - `Failed to add user` via Oxtrust UI
`java.lang.AssertionError: expected [201] but found [500]` via SCIM client

## Screenshots

Version 3.1.7

oxtrust 

2020-06-24 15:35:37,058 ERROR [qtp331418503-1007] [org.gluu.oxtrust.action.UpdatePersonAction] (UpdatePersonAction.java:559) - Failed to add new person @!0A92.7195.8048.7F1B!0001!3D8B.1964!0000!0F89.2F7B.30F1.ABF9
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to persist entry: inum=@!0A92.7195.8048.7F1B!0001!3D8B.1964!0000!0F89.2F7B.30F1.ABF9,ou=people,o=@!0A92.7195.8048.7F1B!0001!3D8B.1964,o=gluu
        at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:124) ~[oxcore-ldap-3.1.7.Final.jar:?]
        at org.gluu.site.ldap.persistence.AbstractEntryManager.persist(AbstractEntryManager.java:90) ~[oxcore-ldap-3.1.7.Final.jar:?]
        at org.gluu.site.ldap.persistence.LdapEntryManager$Proxy$_$$_WeldClientProxy.persist(Unknown Source) ~[oxcore-ldap-3.1.7.Final.jar:?]
        at org.gluu.oxtrust.ldap.service.PersonService.addPerson(PersonService.java:111) ~[classes/:?]
        at org.gluu.oxtrust.action.UpdatePersonAction.save(UpdatePersonAction.java:550) [classes/:?]
        at org.gluu.oxtrust.action.UpdatePersonAction$Proxy$_$$_WeldSubclass.save$$super(Unknown Source) [classes/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.0.6.Final.jar:3.0.6.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.0.6.Final.jar:3.0.6.Final]
        at org.xdi.service.security.SecurityInterceptor.invoke(SecurityInterceptor.java:55) [oxcore-service-3.1.7.Final.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor318.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) [weld-core-impl-3.0.6.Final.jar:3.0.6.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84) [weld-core-impl-3.0.6.Final.jar:3.0.6.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72) [weld-core-impl-3.0.6.Final.jar:3.0.6.Final]
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56) [weld-core-impl-3.0.6.Final.jar:3.0.6.Final]
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79) [weld-core-impl-3.0.6.Final.jar:3.0.6.Final]
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68) [weld-core-impl-3.0.6.Final.jar:3.0.6.Final]
        at org.gluu.oxtrust.action.UpdatePersonAction$Proxy$_$$_WeldSubclass.save(Unknown Source) [classes/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.apache.el.parser.AstValue.invoke(AstValue.java:247) [org.mortbay.jasper.apache-el-8.5.24.2.jar:8.5.24]
        at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267) [org.mortbay.jasper.apache-el-8.5.24.2.jar:8.5.24]

**Comment by syntrydy** [comment]
@sahilarora2020 why are you using amazon corretto 11 on 3.1.x installation?
Java 11 is only supported for version 4.2.x

**Comment by mzico** [comment]
@syntrydy : customer trying to use corretto 11 in 3.1.7. ( grinning )

**Comment by syntrydy** [comment]
okay, please let them know that we only support Java 11 from Gluu version 4.2.x.

**Comment by syntrydy** [comment]
Closing this
