### ISSUE TITLE
Gluu 4.2 QA | user_confirm_registration is throwing error

### ISSUE THREAD

**Issue by sahilarora2020** [GluuFederation/oxTrust#1983]
## Describe the issue
Enabling 'user_confirm_registration' custom script is throwing error

## Steps To Reproduce
1. Go to  Configuration > Other Custom scripts  > User Registration
2. Click on Enable and save it

Error
```
org.gluu.exception.PythonException: Failed to load python file 'java.io.ByteArrayInputStream@657d4587'
	at org.gluu.service.PythonService.loadPythonScript(PythonService.java:187)
	at org.gluu.service.PythonService$Proxy$_$$_WeldClientProxy.loadPythonScript(Unknown Source)
	at org.gluu.service.custom.script.CustomScriptManager.createExternalTypeFromStringWithPythonException(CustomScriptManager.java:406)
	at org.gluu.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.createExternalTypeFromStringWithPythonException(Unknown Source)
	at org.gluu.service.custom.script.CustomScriptManager.createExternalType(CustomScriptManager.java:374)
	at org.gluu.service.custom.script.CustomScriptManager.reloadCustomScriptConfigurations(CustomScriptManager.java:282)
	at org.gluu.service.custom.script.CustomScriptManager.reloadImpl(CustomScriptManager.java:170)
	at org.gluu.service.custom.script.CustomScriptManager.reload(CustomScriptManager.java:148)
	at org.gluu.service.custom.script.CustomScriptManager.reloadTimerEvent(CustomScriptManager.java:124)
	at org.gluu.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.reloadTimerEvent(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor915.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
	at org.jboss.weld.util.Observers.notify(Observers.java:166)
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177)
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:159)
	at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:632)
	at org.jboss.weld.util.ForwardingBeanManager.fireEvent(ForwardingBeanManager.java:104)
	at org.gluu.service.timer.TimerJob.execute(TimerJob.java:39)
	at org.gluu.service.timer.JobExecutionDelegate.execute(JobExecutionDelegate.java:31)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: Traceback (most recent call last):
  File "user_confirm_registration.py", line 8, in <module>
ImportError: No module named service

	at org.python.core.Py.ImportError(Py.java:334)
	at org.python.core.imp.import_logic(imp.java:913)
	at org.python.core.imp.import_module_level(imp.java:970)
	at org.python.core.imp.importName(imp.java:1057)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:450)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1149)
	at org.python.core.imp.importFrom(imp.java:1124)
	at org.python.pycode._pyx4.f$0(user_confirm_registration.py:18)
	at org.python.pycode._pyx4.call_function(user_confirm_registration.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.gluu.service.PythonService.loadPythonScript(PythonService.java:184)
	... 30 more

==================Further details============================
Failed to load python file 'java.io.ByteArrayInputStream@657d4587'
```

Title: oxTrust Server
Version: 4.2.0-SNAPSHOT
Builddate: Mon Jun 22 14:03:15 UTC 2020
Build: 59a37f06f252e55fcdb0a7298b20aa65f8912429

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/85620575-e3e5f880-b65b-11ea-90c3-646cbaa87f9f.png)

**Comment by syntrydy** [comment]
Fixed, have to update the script

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/85705872-8b554080-b6d9-11ea-955d-e80a918b3f42.png)
