### ISSUE TITLE
Navigating through oxTrust leads to error page 

### ISSUE THREAD

**Issue by maduvena** [GluuFederation/oxTrust#1995]
Navigating through oxTrust leads to error page - ERR_TOO_MANY_REDIRECTS on google Chrome (Cleared cache / cookies etc + using Incognito mode)
Logs show - 
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at org.gluu.util.process.ProcessHelper.executeProgram(ProcessHelper.java:153)
	at org.gluu.util.process.ProcessHelper.executeProgram(ProcessHelper.java:67)
	at org.gluu.util.process.ProcessHelper.executeProgram(ProcessHelper.java:52)
	at org.gluu.oxtrust.service.StatusCheckerTimer.getFacterData(StatusCheckerTimer.java:256)

Reproducible often.

## Steps To Reproduce
1. Clean install on CentOS 7
2. Noticed after logging in to oxTrust and navigating around randomly.
3. Error page is displayed - ERR_TOO_MANY_REDIRECTS

## Desktop (please complete the following information):
 - OS: CentOS 7
 - Gluu version - 4.2
 - Google Chrome

[2020_07_06.jetty.log](https://github.com/GluuFederation/oxTrust/files/4880151/2020_07_06.jetty.log)

![image](https://user-images.githubusercontent.com/12072533/86616691-d7568e00-bfd3-11ea-94ad-bfd6e5e4e6dd.png)

**Comment by syntrydy** [comment]
@maduvena we are looking into this.

**Comment by mbaser** [comment]
I tested these packages:
gluu-server-4.2.0-382.centos7.x86_64.rpm
gluu-server_4.2.0-409~xenial_amd64.deb

Did not see any issue.

**Comment by syntrydy** [comment]
@mbaser i think we can close, me too i wasn't able to replicate that issue.

**Comment by mbaser** [comment]
Closing since we can't replicate with recent builds
