### ISSUE TITLE
Gluu 4.2 QA | Unable to upload jar files through oxtrust

### ISSUE THREAD

**Issue by sahilIT2020** [GluuFederation/oxTrust#1996]
## Describe the issue
Unable to upload jar files through oxtrust

## Steps To Reproduce
1. Go to ' Configuration > Organization configuration > Extra Libraries '
2. Upload jar file
3. See error in screenshot

## Expected behavior
Jar files should be uploaded successfully

## Actual behavior
Getting error

## Screenshots
![image](https://user-images.githubusercontent.com/21104811/86653326-1a543980-bfb3-11ea-8048-7dab7ec0b2ef.png)

This time tried with a diff jar file but no progress and I see error in the logs

![image](https://user-images.githubusercontent.com/21104811/86653801-76b75900-bfb3-11ea-91cc-371cfa3fabda.png)

**Build Info**
 gluu-server                x86_64                4.2.0-382.centos7                Gluu-rpm-centos-7-testing-repo                1.5 G

Oxtrust logs

2020-07-06 22:06:11,236 TRACE [ForkJoinPool.commonPool-worker-7] [org.gluu.util.process.ProcessHelper] (ProcessHelper.java:71) - Problem during starting process [facter, -j]
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404) ~[commons-exec-1.3.jar:1.3]
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166) ~[commons-exec-1.3.jar:1.3]
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153) ~[commons-exec-1.3.jar:1.3]
        at org.gluu.util.process.ProcessHelper.executeProgram(ProcessHelper.java:153) ~[oxcore-util-4.2.0-SNAPSHOT.jar:?]
        at org.gluu.util.process.ProcessHelper.executeProgram(ProcessHelper.java:67) [oxcore-util-4.2.0-SNAPSHOT.jar:?]
        at org.gluu.util.process.ProcessHelper.executeProgram(ProcessHelper.java:52) [oxcore-util-4.2.0-SNAPSHOT.jar:?]
        at org.gluu.oxtrust.service.StatusCheckerTimer.getFacterData(StatusCheckerTimer.java:256) [classes/:?]
        at org.gluu.oxtrust.service.StatusCheckerTimer.processInt(StatusCheckerTimer.java:141) [classes/:?]
        at org.gluu.oxtrust.service.StatusCheckerTimer.process(StatusCheckerTimer.java:114) [classes/:?]
        at org.gluu.oxtrust.service.StatusCheckerTimer$Proxy$_$$_WeldSubclass.process$$super(Unknown Source) [classes/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]

**Comment by syntrydy** [comment]
@sahilIT2020 it is working expecting. The error is clear enough, the file is too big. 
For now i'm updating the file size to 10 Mo and also reodering the item.
