### ISSUE TITLE
Redis connection can't be obtained after some operational time in oxtrust (is pool closed?)

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#1998]
```
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: Pool not open
at org.apache.commons.pool2.impl.BaseGenericObjectPool.assertOpen(BaseGenericObjectPool.java:704) ~[commons-pool2-2.4.3.jar:2.4.3]
at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:410) ~[commons-pool2-2.4.3.jar:2.4.3]
at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:361) ~[commons-pool2-2.4.3.jar:2.4.3]
at redis.clients.util.Pool.getResource(Pool.java:50) ~[jedis-2.10.2.jar:?]
… 88 more**
```

![image](https://user-images.githubusercontent.com/2013070/87014055-3be03b80-c1d4-11ea-8b7d-e77dd7d6237b.png)

**Comment by yuriyz** [comment]
Fixed in 4.2.
