### ISSUE TITLE
JAXB-API implementation error

### ISSUE THREAD

**Issue by iromli** [GluuFederation/oxTrust#2005]
## Describe the issue

oxTrust throws error `javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath`.

## Steps To Reproduce

1. Deploy oxTrust app
1. Wait for a few minutes
1. Check the contents of `oxtrust.log` for `JAXBException`

## Server

- OS: Alpine
- Gluu version: v4.2.x
- Platform: docker/k8s
- JVM: AdoptOpenJDK 11

## Additional context

Never seen this error in Java 8.

**Comment by iromli** [comment]
Here's an example of errors found in `oxtrust.log`:

```
2020-07-27 19:49:27,874 DEBUG [oxTrustScheduler_Worker-4] [org.gluu.service.timer.TimerJob] (TimerJob.java:36) - Fire timer event [org.gluu.oxtrust.se
rvice.cdi.event.LogFileSizeChekerEvent] with qualifiers [@org.gluu.service.cdi.event.Scheduled()] from instance 754632851
2020-07-27 19:49:27,876 DEBUG [oxTrustScheduler_Worker-4] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:63) - Bound request end
ed
2020-07-27 19:49:27,882 DEBUG [ForkJoinPool.commonPool-worker-3] [org.gluu.oxtrust.service.LogFileSizeChecker] (LogFileSizeChecker.java:97) - Max Log 
Size: 200
2020-07-27 19:49:27,883 DEBUG [ForkJoinPool.commonPool-worker-3] [org.gluu.oxtrust.service.LogFileSizeChecker] (LogFileSizeChecker.java:100) - Max Log
 Size: 200
2020-07-27 19:49:27,883 DEBUG [ForkJoinPool.commonPool-worker-3] [org.gluu.oxtrust.service.LogFileSizeChecker] (LogFileSizeChecker.java:108) - Getting
 the tomcat home directory
2020-07-27 19:49:27,883 DEBUG [ForkJoinPool.commonPool-worker-3] [org.gluu.oxtrust.service.LogFileSizeChecker] (LogFileSizeChecker.java:110) - FilePat
h: /etc/gluu/conf/oxTrustLogRotationConfiguration.xml
2020-07-27 19:49:27,896 DEBUG [oxTrustScheduler_Worker-5] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:53) - Bound request sta
rted
2020-07-27 19:49:27,896 DEBUG [oxTrustScheduler_Worker-5] [org.gluu.service.timer.TimerJob] (TimerJob.java:36) - Fire timer event [org.gluu.service.cd
i.event.UpdateScriptEvent] with qualifiers [@org.gluu.service.cdi.event.Scheduled()] from instance 1746541180
2020-07-27 19:49:27,907 DEBUG [oxTrustScheduler_Worker-5] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:63) - Bound request end
ed
2020-07-27 19:49:27,955 ERROR [ForkJoinPool.commonPool-worker-3] [org.gluu.service.XmlService] (XmlService.java:64) - Failed to create JAXB marshaller
 and unmarshaller
javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:232) ~[jakarta.xml.bind-api-2.3.3.jar:2.3.3]
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:375) ~[jakarta.xml.bind-api-2.3.3.jar:2.3.3]
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691) ~[jakarta.xml.bind-api-2.3.3.jar:2.3.3]
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632) ~[jakarta.xml.bind-api-2.3.3.jar:2.3.3]
        at org.gluu.service.XmlService.init(XmlService.java:60) [oxcore-service-4.2.1-SNAPSHOT.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:83) [weld-core-impl-3.
1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:66) [weld-core-impl-3.
1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:122) [weld-core-impl-3.1.4.Final.jar:3.1.4.F
inal]
        at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:174) [weld-core-impl-3.1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96) [weld-core-impl-3.1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100) [weld-core-impl-3
.1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140) [weld-c
ore-impl-3.1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50) [weld-core-impl-3.1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:102) [weld-core-impl-3.1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:131) [weld-core-impl-3.1.4.Final.jar:3.1.4.Final]
        at org.gluu.service.XmlService$Proxy$_$$_WeldClientProxy.getXmlDocument(Unknown Source) [oxcore-service-4.2.1-SNAPSHOT.jar:?]
        at org.gluu.oxtrust.service.LogFileSizeChecker.readConfig(LogFileSizeChecker.java:170) [classes/:?]
        at org.gluu.oxtrust.service.LogFileSizeChecker.processInt(LogFileSizeChecker.java:112) [classes/:?]
        at org.gluu.oxtrust.service.LogFileSizeChecker.process(LogFileSizeChecker.java:84) [classes/:?]
        at org.gluu.oxtrust.service.LogFileSizeChecker$Proxy$_$$_WeldSubclass.process$$super(Unknown Source) [classes/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:83) [weld-core-impl-3.
1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:66) [weld-core-impl-3.
1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:122) [weld-core-impl-3.1.4.Final.jar:3.1.4.F
inal]
        at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:174) [weld-core-impl-3.1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96) [weld-core-impl-3.1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100) [weld-core-impl-3
.1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140) [weld-c
ore-impl-3.1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50) [weld-core-impl-3.1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:102) [weld-core-impl-3.1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:131) [weld-core-impl-3.1.4.Final.jar:3.1.4.Final]
        at org.gluu.service.XmlService$Proxy$_$$_WeldClientProxy.getXmlDocument(Unknown Source) [oxcore-service-4.2.1-SNAPSHOT.jar:?]
        at org.gluu.oxtrust.service.LogFileSizeChecker.readConfig(LogFileSizeChecker.java:170) [classes/:?]
        at org.gluu.oxtrust.service.LogFileSizeChecker.processInt(LogFileSizeChecker.java:112) [classes/:?]
        at org.gluu.oxtrust.service.LogFileSizeChecker.process(LogFileSizeChecker.java:84) [classes/:?]
        at org.gluu.oxtrust.service.LogFileSizeChecker$Proxy$_$$_WeldSubclass.process$$super(Unknown Source) [classes/:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld
-core-impl-3.1.4.Final.jar:3.1.4.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.1.4.Final.j
ar:3.1.4.Final]
        at org.gluu.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:36) [oxcore-service-4.2.1-SNAPSHOT.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(Unknown Source) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.ContextFactory
        at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:92) ~[jakarta.xml.bind-api-2.3.3.jar:2.3.3]
        at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:125) ~[jakarta.xml.bind-api-2.3.3.jar:2.3.3]
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:230) ~[jakarta.xml.bind-api-2.3.3.jar:2.3.3]
        ... 37 more
2020-07-27 19:49:27,966 DEBUG [ForkJoinPool.commonPool-worker-3] [org.gluu.oxtrust.service.LogFileSizeChecker] (LogFileSizeChecker.java:203) - Prefix:
 oxtrust Location: /opt/gluu/jetty/identity/logs
```

**Comment by yurem** [comment]
Fixed
