### ISSUE TITLE
can't logout of oxTrust after restart

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#202]
1. Login to oxTrust
  2. Restart gluu-server
  3. Navigate back to oxTrust (you should still be logged in because OpenID Connect session is still active in browser)
  4. Try to logout... redirected to Seam error page (and you are still logged in).

![image](https://cloud.githubusercontent.com/assets/3717101/13149396/01043306-d627-11e5-9169-97b1085f0e0d.png)

    2016-02-18 09:50:29,360 ERROR [org.gluu.oxtrust.service.AuthenticationSessionService] Invalid response code at oxAuth logout. User: 'admin'
    2016-02-18 09:50:29,362 WARN  [org.jboss.seam.Component] Exception calling component @Destroy method: appInitializer
    java.lang.NullPointerException
            at org.jboss.seam.async.AsynchronousInterceptor.isExecutingAsynchronousCall(AsynchronousInterceptor.java:63)
            at org.jboss.seam.async.AsynchronousInterceptor.aroundInvoke(AsynchronousInterceptor.java:46)
            at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
            at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
            at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196)
            at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114)
            at org.gluu.oxtrust.ldap.service.AppInitializer_$$_javassist_seam_2.destroyApplicationComponents(AppInitializer_$$_javassist_seam_2.java)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:606)
            at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
            at org.jboss.seam.util.Reflections.invokeAndWrap(Reflections.java:144)
            at org.jboss.seam.Component.callComponentMethod(Component.java:2313)
            at org.jboss.seam.Component.callDestroyMethod(Component.java:2244)
            at org.jboss.seam.Component.destroy(Component.java:1476)
            at org.jboss.seam.contexts.Contexts.destroy(Contexts.java:290)
            at org.jboss.seam.contexts.Lifecycle.endApplication(Lifecycle.java:61)
            at org.jboss.seam.contexts.ServletLifecycle.endApplication(ServletLifecycle.java:176)
            at org.jboss.seam.servlet.SeamListener.contextDestroyed(SeamListener.java:41)
            at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:5033)
            at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5685)
            at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
            at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1591)
            at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1580)
            at java.util.concurrent.FutureTask.run(FutureTask.java:262)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
            at java.lang.Thread.run(Thread.java:745)

**Comment by yurem** [comment]
I have tried to reproduce it in CE 2.4.2 beta2. But I didn't get exceptions. I used next scenario:
1. Login into oxTrust
2. service gluu-server-2.4.2 stop
3. service gluu-server-2.4.2 start
4. tail -f /opt/gluu-server-2.4.2/opt/apache-tomcat-7.0.55/logs/oxauth.log ---- to make sure that oxauth started
5. tail -f /opt/gluu-server-2.4.2/opt/apache-tomcat-7.0.55/logs/oxtrust.log ---- to make sure that oxtrust started
6. Click logout.
7. User log in into oxTrust again

After step 6 oxTrust do few redirects and send user to oxAuth login page. oxAuth do auto login because there is session cookie which exist in LDAP

**Comment by yurem** [comment]
![redirects](https://cloud.githubusercontent.com/assets/6104200/13153415/bfa58652-d67c-11e5-90c3-4dfe88722f01.png)

**Comment by yurem** [comment]
According to this list of calls oxTrust on logout action after server restart do next:
/idenity/logout -> /idenity/home (home requires user login)  -> /idenity/login (prepare authorization request) -> /oxauth/authorize (at this point oxAuth Auth Filter intercept process and do user authentication because there is session cookie) -> /identity/authcode#.....

**Comment by yurem** [comment]
oxTrust should send end_session requests to oxAuth on tomcat shutdown to end all authenticated users sessions

**Comment by yurem** [comment]
Seam destroy components in wrong order, without checking dependencies. As result if component uses dependencies in destroy method application throw NPE.
In order to resolve this issue we need to find out how to intercept PreDestroy event or something like this.

**Comment by aliaksander-samuseu** [comment]
@yurem @willow9886 
What is status of this one? Should we set milestone to 2.4.4 and add it to roadmap?

**Comment by aliaksander-samuseu** [comment]
I wasn't able to reproduce in 2.4.3-1-3 deb package

**Comment by yurem** [comment]
If we can reproduce it using workflow from [this](https://github.com/GluuFederation/oxTrust/issues/202#issuecomment-185843110) comment we can clsoe it

**Comment by zamilskhan** [comment]
Tried reproducing it. failed. 
![restart-check](https://cloud.githubusercontent.com/assets/7703245/14824547/41cbcd20-0bf8-11e6-8fa1-77f6bf8d55a8.png)

**Comment by yurem** [comment]
Resolved
