### ISSUE TITLE
Missing information on server status view

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#2047]
On the gluu server status page  some field oare not populate due to some error saving oxtrust metrics.

![image](https://user-images.githubusercontent.com/7513418/102190435-4fe14500-3eb8-11eb-8fa9-8d293e3357d6.png)

`
Caused by: com.unboundid.ldap.sdk.LDAPException: Entry uniqueIdentifier=2020-12-15,ou=202012,ou=oxtrust,ou=statistic,o=metric cannot be added because its parent entry ou=202012,ou=oxtrust,ou=statistic,o=metric does not exist in the server
        at com.unboundid.ldap.sdk.LDAPConnection.add(LDAPConnection.java:2160) ~[unboundid-ldapsdk-5.1.0.jar:5.1.0]
        at com.unboundid.ldap.sdk.AbstractConnectionPool.add(AbstractConnectionPool.java:776) ~[unboundid-ldapsdk-5.1.0.jar:5.1.0]
        at com.unboundid.ldap.sdk.AbstractConnectionPool.add(AbstractConnectionPool.java:704) ~[unboundid-ldapsdk-5.1.0.jar:5.1.0]
        at org.gluu.persist.ldap.operation.impl.LdapOperationServiceImpl.addEntryImpl(LdapOperationServiceImpl.java:726) ~[oxcore-persistence-ldap-4.2.2-SNAPSHOT.jar:?]
        at org.gluu.persist.ldap.operation.impl.LdapOperationServiceImpl.addEntry(LdapOperationServiceImpl.java:712) ~[oxcore-persistence-ldap-4.2.2-SNAPSHOT.jar:?]
        at org.gluu.persist.ldap.impl.LdapEntryManager.persist(LdapEntryManager.java:185) ~[oxcore-persistence-ldap-4.2.2-SNAPSHOT.jar:?]
        ... 21 more

`

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/102210552-9ba0e800-3ed2-11eb-8c47-d6e40c50fbca.png)
