### ISSUE TITLE
Add Person Form Crashes with New Objectclass

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#2069]
1. Add a new attribute and objectclass to LDAP

```
dn: cn=schema
objectClass: top
objectClass: ldapSubentry
objectClass: subschema
cn: schema
attributeTypes: ( 'spamNumber' NAME 'spamNumber'
  DESC 'Number of Spams'
  EQUALITY caseIgnoreMatch
  SUBSTR caseIgnoreSubstringsMatch
  SYNTAX 1.3.6.1.4.1.1466.115.121.1.15
  X-ORIGIN 'Sample domain attribute' )
attributeTypes: ( 'spamColor' NAME 'spamColor'
  DESC 'Color of Spam'
  EQUALITY caseIgnoreMatch
  SUBSTR caseIgnoreSubstringsMatch
  SYNTAX 1.3.6.1.4.1.1466.115.121.1.15
  X-ORIGIN 'Sample domain attribute' )
objectClasses: ( 'spamPerson' NAME 'spamPerson'
  SUP ( top )
  AUXILIARY
  MAY ( spamNumber $ spamColor $ )
  X-ORIGIN 'Sample Custom Person schema' )

```

2. Add JSON Properties for this, replacing "customPErson"

![image](https://user-images.githubusercontent.com/3717101/120238705-5a9f5480-c222-11eb-9a1c-d282359a4090.png)

![image](https://user-images.githubusercontent.com/3717101/120238749-6f7be800-c222-11eb-9db1-151e099ff0cb.png)

3. Register the Attribute

4. Try to add a person... this crashes whether or not you add the new custom attribute.

**Comment by nynymike** [comment]
Note: if you edit an existing person, you can add the new attribute fine. The new custom objectclass gets added to the person, and the data is persisted in LDAP. It's just when you add a new person that you get the "Ooops" message. I was able to repeat this error multiple times. I saw this in the logs

```
2021-05-31 19:51:43,081 TRACE [qtp222511810-19] [org.gluu.oxtrust.exception.GlobalExceptionHandler] (GlobalExceptionHandler.java:58) - //opt/jetty-9.4/temp/jetty-localhost-8082-identity_war-_identity-any-14808836951257958409/webapp/WEB-INF/incl/person/userForm.xhtml @354,63 value="#{_list.get(2).value}": java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
javax.el.ELException: //opt/jetty-9.4/temp/jetty-localhost-8082-identity_war-_identity-any-14808836951257958409/webapp/WEB-INF/incl/person/userForm.xhtml @354,63 value="#{_list.get(2).value}": java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:77) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:170) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:157) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at org.richfaces.component.UISequence.getValue(UISequence.java:180) ~[richfaces-a4j-4.5.18-gluu.Final.jar:4.5.18-gluu.Final]
	at org.richfaces.component.UISequence.createExtendedDataModel(UISequence.java:114) ~[richfaces-a4j-4.5.18-gluu.Final.jar:4.5.18-gluu.Final]
	at org.richfaces.component.UIDataAdaptor.getExtendedDataModel(UIDataAdaptor.java:467) ~[richfaces-a4j-4.5.18-gluu.Final.jar:4.5.18-gluu.Final]
	at org.richfaces.component.UIDataAdaptor.setRowKey(UIDataAdaptor.java:280) ~[richfaces-a4j-4.5.18-gluu.Final.jar:4.5.18-gluu.Final]
	at org.richfaces.component.UIDataAdaptor.visitTree(UIDataAdaptor.java:1320) ~[richfaces-a4j-4.5.18-gluu.Final.jar:4.5.18-gluu.Final]

```
