### ISSUE TITLE
Cache Refresh not working on 4.3.0 version.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2072]
## Describe the issue
Cache Refresh not working on latest 4.3.0 version. When you try to create connection its always prompt failed to connect to server.

## Steps To Reproduce
1.  Enable Cache Refresh script
2.  Add any Source Backend Server
3. Click on Test connection.

## Expected behavior
Connection has to established for cache refresh.

## Actual behavior
Failed to connect to Ldap server

### Error on log
```
ERROR [ForkJoinPool.commonPool-worker-3] [org.gluu.service.config.ConfigurationFactory] (ConfigurationFactory.java:306) - WELD-001334: Unsatisfied dependencies for type CacheRefreshConfiguration with qualifiers @Default 
org.jboss.weld.exceptions.UnsatisfiedResolutionException: WELD-001334: Unsatisfied dependencies for type CacheRefreshConfiguration with qualifiers @Default 
	at org.jboss.weld.bean.builtin.InstanceImpl.checkBeanResolved(InstanceImpl.java:241) ~[weld-core-impl-3.1.4.Final.jar:3.1.4.Final]
	at org.jboss.weld.bean.builtin.InstanceImpl.get(InstanceImpl.java:113) ~[weld-core-impl-3.1.4.Final.jar:3.1.4.Final]
	at org.gluu.service.config.ConfigurationFactory.destroy(ConfigurationFactory.java:314) ~[oxtrust-service-4.3.0-SNAPSHOT.jar:?]
	at org.gluu.oxtrust.service.config.ConfigurationFactory$Proxy$_$$_WeldSubclass.destroy(Unknown Source) ~[classes/:?]
	at org.gluu.oxtrust.service.config.ConfigurationFactory.destroryLoadedConfiguration(ConfigurationFactory.java:75) ~[classes/:?]
	at org.gluu.oxtrust.service.config.ConfigurationFactory$Proxy$_$$_WeldSubclass.destroryLoadedConfiguration(Unknown Source) ~[classes/:?]
	at org.gluu.service.config.ConfigurationFactory.createFromDb(ConfigurationFactory.java:297) [oxtrust-service-4.3.0-SNAPSHOT.jar:?]
	at org.gluu.service.config.ConfigurationFactory.reloadConfiguration(ConfigurationFactory.java:223) [oxtrust-service-4.3.0-SNAPSHOT.jar:?]
	at org.gluu.service.config.ConfigurationFactory.reloadConfigurationTimerEvent(ConfigurationFactory.java:175) [oxtrust-service-4.3.0-SNAPSHOT.jar:?]
	at org.gluu.oxtrust.service.config.ConfigurationFactory$Proxy$_$$_WeldSubclass.reloadConfigurationTimerEvent$$super(Unknown Source) [classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.1.4.Final.jar:3.1.4.Final]
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.1.4.Final.jar:3.1.4.Final]
	at org.gluu.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:36) [oxcore-service-4.3.0-SNAPSHOT.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
```

## Desktop (please complete the following information):
 - OS: Ubuntu 20
 - Gluu version 4.3.0

**Comment by syntrydy** [comment]
This issue is coming from a bug introduced in 4.3.0, mainly due to some changes in the way the LDAP connection settings are formatted. 
I have sent a fix into the oxOrm project.

**Comment by yurem** [comment]
Fixed
