### ISSUE TITLE
SAML NameID configuration is not working in Cloud Edition

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#2073]
!!! Note 
Unless you are Gluu staff, please first review and open an issue on https://support.gluu.org before opening an issue here. Thanks!
## Description
Mode details on ticket
## Log
2021-06-09 12:32:18,024 INFO  [qtp1671846437-15] [org.gluu.oxtrust.service.Shibboleth3ConfService] (Shibboleth3ConfService.java:306) - >>>>>>>>>> LEAVING Shibboleth3ConfService.generateConfigurationFiles()...
org.apache.http.conn.HttpHostConnectException: Connect to localhost:443 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)

**Comment by moabu** [comment]
Thanks, @syntrydy . We need to specify the protocol for the IDP url as well. 

```java

    public static  URL getIdpUrl(URL url, String idp_Env) throws MalformedURLException {
        String[] values = idp_Env.split(":");
        if (values.length > 1) {
            url = new URL(url.getProtocol(), values[0], Integer.valueOf(values[1]), url.getFile());
        } else {
            url = new URL(url.getProtocol(), values[0], url.getPort(), url.getFile());
        }
        return url;
    }

```

**Comment by coudiahub** [comment]
okay adding
