### ISSUE TITLE
"Organization Configuration" throwing error

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#2075]
- Gluu Server 4.3.0, backend with MySQL
- oxTrust throwing error when using `Configuration` > `Organization Configuration`
- GIF attached: 
![Peek 2021-06-23 10-48](https://user-images.githubusercontent.com/7156097/123128616-e87cf280-d410-11eb-9eb4-6459b548d93d.gif)

- oxtrust.log in TRACE: 

```
2021-06-23 15:48:01,054 TRACE [qtp534906248-21] [org.gluu.oxtrust.service.PermissionService] (PermissionService.java:72) - Checking permissions for target 'configuration' an 'action'. Identity: access
2021-06-23 15:48:01,055 TRACE [qtp534906248-21] [org.gluu.oxtrust.service.PermissionService] (PermissionService.java:72) - Checking permissions for target 'configuration' an 'action'. Identity: access
2021-06-23 15:48:01,056 TRACE [qtp534906248-21] [org.gluu.oxtrust.service.PermissionService] (PermissionService.java:72) - Checking permissions for target 'configuration' an 'action'. Identity: access
2021-06-23 15:48:01,057 TRACE [qtp534906248-21] [org.gluu.service.BaseCacheService] (BaseCacheService.java:37) - Request data, key 'l_inum=60B7,ou=groups,o=gluu'
2021-06-23 15:48:01,058 TRACE [qtp534906248-21] [org.gluu.service.BaseCacheService] (BaseCacheService.java:39) - Loaded data, key 'l_inum=60B7,ou=groups,o=gluu': 'null'
2021-06-23 15:48:01,059 TRACE [qtp534906248-21] [org.gluu.oxtrust.exception.GlobalExceptionHandler] (GlobalExceptionHandler.java:58) - null
java.lang.NullPointerException: null
	at java.net.URLEncoder.encode(URLEncoder.java:224) ~[?:?]
	at java.net.URLEncoder.encode(URLEncoder.java:196) ~[?:?]
	at com.sun.faces.context.UrlBuilder.addValuesToParameter(UrlBuilder.java:297) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.context.UrlBuilder.addParameters(UrlBuilder.java:101) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.context.ExternalContextImpl.encodeBookmarkableURL(ExternalContextImpl.java:1091) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.context.ExternalContextWrapper.encodeBookmarkableURL(ExternalContextWrapper.java:985) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.context.ExternalContextWrapper.encodeBookmarkableURL(ExternalContextWrapper.java:985) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.context.ExternalContextWrapper.encodeBookmarkableURL(ExternalContextWrapper.java:985) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.application.view.MultiViewHandler.getBookmarkableURL(MultiViewHandler.java:364) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.application.ViewHandlerWrapper.getBookmarkableURL(ViewHandlerWrapper.java:303) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.application.ViewHandlerWrapper.getBookmarkableURL(ViewHandlerWrapper.java:303) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at org.jboss.weld.module.jsf.ConversationAwareViewHandler.getBookmarkableURL(ConversationAwareViewHandler.java:135) ~[weld-jsf-3.1.4.Final.jar:3.1.4.Final]
	at javax.faces.application.ViewHandlerWrapper.getBookmarkableURL(ViewHandlerWrapper.java:303) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.renderkit.html_basic.OutcomeTargetRenderer.getEncodedTargetURL(OutcomeTargetRenderer.java:177) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.renderkit.html_basic.OutcomeTargetLinkRenderer.renderAsActive(OutcomeTargetLinkRenderer.java:134) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.renderkit.html_basic.OutcomeTargetLinkRenderer.encodeBegin(OutcomeTargetLinkRenderer.java:72) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.component.UIComponentBase.encodeBegin(UIComponentBase.java:540) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:276) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:90) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:278) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:90) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:278) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:90) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1647) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.renderkit.html_basic.CompositeRenderer.encodeChildren(CompositeRenderer.java:54) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:278) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:90) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1647) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:152) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:278) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:90) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:566) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1647) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1650) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:468) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:170) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:132) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:119) ~[omnifaces-2.6.9.jar:2.6.9]
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:102) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:199) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:708) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451) ~[jakarta.faces-2.3.14.jar:2.3.14]
	at org.eclipse.jetty.servlet.ServletHolder$NotAsyncServlet.service(ServletHolder.java:1402) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1651) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226) ~[websocket-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1638) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:567) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602) ~[jetty-security-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1610) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1580) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.Server.handle(Server.java:501) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-06-23 15:48:01,359 TRACE [qtp534906248-14] [org.gluu.service.BaseCacheService] (BaseCacheService.java:37) - Request data, key 'organization_oxtrust'
2021-06-23 15:48:01,359 TRACE [qtp534906248-14] [org.gluu.service.BaseCacheService] (BaseCacheService.java:39) - Loaded data, key 'organization_oxtrust': 'Entry [dn=o=gluu]'
2021-06-23 15:48:01,359 TRACE [qtp534906248-14] [org.gluu.service.BaseCacheService] (BaseCacheService.java:58) - Loaded from cache, key: 'organization_oxtrust'
2021-06-23 15:48:01,359 TRACE [qtp534906248-14] [org.gluu.service.BaseCacheService] (BaseCacheService.java:37) - Request data, key 'organization_oxtrust'
2021-06-23 15:48:01,359 TRACE [qtp534906248-14] [org.gluu.service.BaseCacheService] (BaseCacheService.java:39) - Loaded data, key 'organization_oxtrust': 'Entry [dn=o=gluu]'
```

**Comment by yurem** [comment]
fixed
