### ISSUE TITLE
HTTP 500 error on accessible endpoint `/identity/org.richfaces.resources/javax.faces.resource/`

### ISSUE THREAD

**Issue by moabu** [GluuFederation/oxTrust#2090]
## Describe the issue
HTTP `500` Error when hitting the endpoint `/identity/org.richfaces.resources/javax.faces.resource/`

## Steps To Reproduce
1. Install Gluu `4.2` or `4.3`
2. head to `https://FQDN/identity/org.richfaces.resources/javax.faces.resource/`
3. See error

## Expected behavior
This should redirect to the authentication page or perhaps the main page if authenticated. This endpoint shouldn't probably even be exposed.

## Actual behavior
HTTP `500` Error

## Screenshots

<img width="1440" alt="Screen Shot 2021-08-23 at 3 51 54 AM" src="https://user-images.githubusercontent.com/47318409/130410883-41a6e342-5aab-4902-82f2-9e4777e60499.png">

**Comment by yurem** [comment]
We need to apply changes to ResourceHandlerImpl in https://github.com/GluuFederation/richfaces-gluu project. Before applying changes we need to create new branch version_4.5.19.gluu.Final from version_4.5.18.gluu.Final

**Comment by moabu** [comment]
<h2 style="font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">HTTP ERROR 500 java.lang.StringIndexOutOfBoundsException: String index out of range: 0</h2>

URI: | /identity/org.richfaces.resources/javax.faces.resource/
-- | --
500
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
AutoRegisteredResourceServlet
java.lang.StringIndexOutOfBoundsException: String index out of range: 0

<h3 style="font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">Caused by:</h3><pre style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at com.sun.faces.application.resource.ResourceManager.trimLeadingSlash(ResourceManager.java:347)
	at com.sun.faces.application.resource.ResourceManager.getResourceInfo(ResourceManager.java:296)
	at com.sun.faces.application.resource.ResourceManager.doLookup(ResourceManager.java:266)
	at com.sun.faces.application.resource.ResourceManager.findResourceNonCompressed(ResourceManager.java:215)
	at com.sun.faces.application.resource.ResourceManager.findResource(ResourceManager.java:180)
	at com.sun.faces.application.resource.ResourceManager.findResource(ResourceManager.java:149)
	at com.sun.faces.application.resource.ResourceHandlerImpl.createResource(ResourceHandlerImpl.java:119)
	at javax.faces.application.ResourceHandlerWrapper.createResource(ResourceHandlerWrapper.java:159)
	at org.primefaces.application.resource.PrimeResourceHandler.createResource(PrimeResourceHandler.java:81)
	at org.richfaces.resource.ResourceHandlerImpl.createResource(ResourceHandlerImpl.java:268)
	at org.richfaces.resource.ResourceHandlerImpl.createResource(ResourceHandlerImpl.java:280)
	at org.omnifaces.resourcehandler.DefaultResourceHandler.createResource(DefaultResourceHandler.java:76)
	at org.omnifaces.resourcehandler.DefaultResourceHandler.createResource(DefaultResourceHandler.java:76)
	at com.sun.faces.application.resource.ResourceHandlerImpl.handleResourceRequest(ResourceHandlerImpl.java:285)
	at javax.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:171)
	at org.primefaces.application.resource.PrimeResourceHandler.handleResourceRequest(PrimeResourceHandler.java:97)
	at org.richfaces.resource.ResourceHandlerImpl.handleResourceRequest(ResourceHandlerImpl.java:219)
	at javax.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:171)
	at javax.faces.application.ResourceHandlerWrapper.handleResourceRequest(ResourceHandlerWrapper.java:171)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:704)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.richfaces.webapp.ResourceServlet.httpService(ResourceServlet.java:129)
	at org.richfaces.webapp.ResourceServlet.service(ResourceServlet.java:123)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1443)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
	at java.base/java.lang.Thread.run(Thread.java:834)</pre>

**Comment by shekhar16** [comment]
issue is fixed, and now resources are not available on url or not throwing any exception.
Its a invalid url for user and should get 404.here is screenshot.


![image](https://user-images.githubusercontent.com/15937500/162025368-077e783d-edcd-480c-a39a-f216af51665f.png)

**Comment by shekhar16** [comment]
closing this issue.
