### ISSUE TITLE
MySQL: Error updating an existing group

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#2106]
## Describe the issue  

Updating a group is not working.

## Steps To Reproduce
1. Create a user
2. Create a group
3. edit the group and assign created user to group and save
4. See an error

## logs
2021-11-23T11:15:24.653210721Z 2021-11-23 11:15:24,649 ERROR [qtp166794956-1988] [org.gluu.oxtrust.action.UpdateGroupAction] (UpdateGroupAction.java:146) - Failed to prepare lists
2021-11-23T11:15:24.653240285Z org.gluu.persist.exception.EntryPersistenceException: Failed to find entries with key: 'people', expression: 'ConvertedExpression [expression=doc.inum = 462947d8-cc2d-49fd-8a5d-be77696df84c, jsonAttributes={}]'
2021-11-23T11:15:24.653248126Z  at org.gluu.persist.sql.impl.SqlEntryManager.findEntriesImpl(SqlEntryManager.java:497) ~[gluu-orm-sql-4.3.1-SNAPSHOT.jar:?]
2021-11-23T11:15:24.653253653Z  at org.gluu.persist.sql.impl.SqlEntryManager.findEntries(SqlEntryManager.java:392) ~[gluu-orm-sql-4.3.1-SNAPSHOT.jar:?]
2021-11-23T11:15:24.653258693Z  at org.gluu.persist.impl.BaseEntryManager.findEntries(BaseEntryManager.java:159) ~[gluu-orm-core-4.3.1-SNAPSHOT.jar:?]
2021-11-23T11:15:24.653265127Z  at jdk.internal.reflect.GeneratedMethodAccessor389.invoke(Unknown Source) ~[?:?]
2021-11-23T11:15:24.653271206Z  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2021-11-23T11:15:24.653276920Z  at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2021-11-23T11:15:24.653283447Z  at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T11:15:24.653288585Z  at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T11:15:24.653297983Z  at org.gluu.persist.PersistenceEntryManager$EntityManager$1037559104$Proxy$_$$_WeldClientProxy.findEntries(Unknown Source) ~[gluu-orm-core-4.3.1-SNAPSHOT.jar:?]
2021-11-23T11:15:24.653303162Z  at org.gluu.service.LookupService.getDisplayNameEntries(LookupService.java:106) ~[oxcore-service-4.3.1-SNAPSHOT.jar:?]
2021-11-23T11:15:24.653308255Z  at org.gluu.service.LookupService$Proxy$_$$_WeldClientProxy.getDisplayNameEntries(Unknown Source) ~[oxcore-service-4.3.1-SNAPSHOT.jar:?]
2021-11-23T11:15:24.653313266Z  at org.gluu.oxtrust.action.UpdateGroupAction.getMemberDisplayNameEntiries(UpdateGroupAction.java:240) ~[classes/:?]
2021-11-23T11:15:24.653318360Z  at org.gluu.oxtrust.action.UpdateGroupAction.update(UpdateGroupAction.java:144) ~[classes/:?]
2021-11-23T11:15:24.653323358Z  at org.gluu.oxtrust.action.UpdateGroupAction$Proxy$_$$_WeldSubclass.update$$super(Unknown Source) ~[classes/:?]
2021-11-23T11:15:24.653337531Z  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
2021-11-23T11:15:24.653342166Z  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
2021-11-23T11:15:24.653346585Z  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2021-11-23T11:15:24.653351152Z  at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2021-11-23T11:15:24.653357316Z  at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T11:15:24.653361926Z  at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T11:15:24.653366274Z  at org.gluu.service.security.SecurityInterceptor.invoke(SecurityInterceptor.java:55) ~[security-extension-cdi-4.3.1-SNAPSHOT.jar:?]
2021-11-23T11:15:24.653370651Z  at jdk.internal.reflect.GeneratedMethodAccessor196.invoke(Unknown Source) ~[?:?]
2021-11-23T11:15:24.653375561Z  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2021-11-23T11:15:24.653380286Z  at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2021-11-23T11:15:24.653384712Z  at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T11:15:24.653392945Z  at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T11:15:24.653397424Z  at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T11:15:24.653402259Z  at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T11:15:24.653406599Z  at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T11:15:24.653410851Z  at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T11:15:24.653429610Z  at org.gluu.oxtrust.action.UpdateGroupAction$Proxy$_$$_WeldSubclass.update(Unknown Source) ~[classes/:?]
2021-11-23T11:15:24.653435284Z  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
2021-11-23T11:15:24.653439727Z  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
2021-11-23T11:15:24.653444201Z  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2021-11-23T11:15:24.653448565Z  at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2021-11-23T11:15:24.653452804Z  at org.apache.el.parser.AstValue.invoke(AstValue.java:247) ~[org.mortbay.jasper.apache-el-9.0.29.jar:9.0.29]
2021-11-23T11:15:24.653457196Z  at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267) ~[org.mortbay.jasper.apache-el-9.0.29.jar:9.0.29]
2021-11-23T11:15:24.653461767Z  at org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40) ~[weld-web-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T11:15:24.653466247Z  at org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50) ~[weld-web-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T11:15:24.653474890Z  at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:65) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T11:15:24.653479382Z  at com.sun.faces.application.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:66) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T11:15:24.653483754Z  at com.sun.faces.application.ActionListenerImpl.getNavigationOutcome(ActionListenerImpl.java:82) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T11:15:24.653488396Z  at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:71) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T11:15:24.653492716Z  at javax.faces.component.UIViewAction.broadcast(UIViewAction.java:548) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T11:15:24.653497091Z  at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:847) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T11:15:24.653501486Z  at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1396) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T11:15:24.653505801Z  at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:58) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T11:15:24.653510438Z  at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T11:15:24.653514585Z  at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T11:15:24.653518932Z  at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T11:15:24.653523360Z  at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T11:15:24.653527725Z  at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1410) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653532041Z  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653536490Z  at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1619) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653541053Z  at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:164) ~[websocket-servlet-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653545288Z  at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653549614Z  at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653553911Z  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:506) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653558133Z  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653562534Z  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:580) ~[jetty-security-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653566848Z  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653571129Z  at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653575375Z  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653579719Z  at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653584018Z  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1372) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653602374Z  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653607696Z  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:463) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653612045Z  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653616286Z  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653620580Z  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1294) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653624886Z  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653629321Z  at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653633576Z  at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653637920Z  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653642291Z  at org.eclipse.jetty.server.Server.handle(Server.java:562) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653646503Z  at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:406) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653650734Z  at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:663) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653655076Z  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:398) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653659490Z  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653663855Z  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319) ~[jetty-io-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653668231Z  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[jetty-io-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653672454Z  at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101) ~[jetty-io-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653676776Z  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412) ~[jetty-util-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653681483Z  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381) ~[jetty-util-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653685540Z  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268) ~[jetty-util-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653689911Z  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138) ~[jetty-util-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653694293Z  at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:378) [jetty-util-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653698565Z  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) [jetty-util-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653702916Z  at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) [jetty-util-10.0.6.jar:10.0.6]
2021-11-23T11:15:24.653708222Z  at java.lang.Thread.run(Thread.java:829) [?:?]
2021-11-23T11:15:24.653712677Z Caused by: org.gluu.persist.exception.MappingException: Object class isn't defined in bean 'class org.gluu.model.DisplayNameEntry'!
2021-11-23T11:15:24.653720122Z  at org.gluu.persist.sql.impl.SqlEntryManager.getBaseObjectClass(SqlEntryManager.java:956) ~[gluu-orm-sql-4.3.1-SNAPSHOT.jar:?]
2021-11-23T11:15:24.653724445Z  at org.gluu.persist.sql.impl.SqlEntryManager.findEntriesImpl(SqlEntryManager.java:486) ~[gluu-orm-sql-4.3.1-SNAPSHOT.jar:?]

**Comment by shekhar16** [comment]
This issue is fixed. @MohitMaliFtechiz   I m closing this issue.
