### ISSUE TITLE
MySQL: impossible to view the detail of the default admin user

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#2108]
## Describe the issue
 Impossible to view the detail of the default admin user, no error information is displayed on the UI.
## Steps To Reproduce
1. Go to users
2. Search for admin
3. Try to view his detail
4. See an error

## Logs
`
2021-11-23T13:37:53.808143800Z 2021-11-23 13:37:53,805 ERROR [qtp166794956-1039] [org.gluu.oxtrust.action.UpdatePersonAction] (UpdatePersonAction.java:309) - null
2021-11-23T13:37:53.808162972Z java.lang.NullPointerException: null
2021-11-23T13:37:53.808169780Z  at org.gluu.oxtrust.action.UpdatePersonAction.addMobileDevices(UpdatePersonAction.java:362) ~[classes/:?]
2021-11-23T13:37:53.808175125Z  at org.gluu.oxtrust.action.UpdatePersonAction.update(UpdatePersonAction.java:307) ~[classes/:?]
2021-11-23T13:37:53.808180165Z  at org.gluu.oxtrust.action.UpdatePersonAction$Proxy$_$$_WeldSubclass.update$$super(Unknown Source) ~[classes/:?]
2021-11-23T13:37:53.808193210Z  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
2021-11-23T13:37:53.808197764Z  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
2021-11-23T13:37:53.808241159Z  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2021-11-23T13:37:53.808245691Z  at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2021-11-23T13:37:53.808250432Z  at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T13:37:53.808258256Z  at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T13:37:53.808262775Z  at org.gluu.service.security.SecurityInterceptor.invoke(SecurityInterceptor.java:55) ~[security-extension-cdi-4.3.1-SNAPSHOT.jar:?]
2021-11-23T13:37:53.808268641Z  at jdk.internal.reflect.GeneratedMethodAccessor196.invoke(Unknown Source) ~[?:?]
2021-11-23T13:37:53.808273032Z  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2021-11-23T13:37:53.808277260Z  at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2021-11-23T13:37:53.808281713Z  at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T13:37:53.808287565Z  at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T13:37:53.808292005Z  at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T13:37:53.808296245Z  at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T13:37:53.808300593Z  at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T13:37:53.808304894Z  at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T13:37:53.808309178Z  at org.gluu.oxtrust.action.UpdatePersonAction$Proxy$_$$_WeldSubclass.update(Unknown Source) ~[classes/:?]
2021-11-23T13:37:53.808313469Z  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
2021-11-23T13:37:53.808317828Z  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
2021-11-23T13:37:53.808322053Z  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2021-11-23T13:37:53.808326528Z  at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2021-11-23T13:37:53.808330819Z  at org.apache.el.parser.AstValue.invoke(AstValue.java:247) ~[org.mortbay.jasper.apache-el-9.0.29.jar:9.0.29]
2021-11-23T13:37:53.808335053Z  at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267) ~[org.mortbay.jasper.apache-el-9.0.29.jar:9.0.29]
2021-11-23T13:37:53.808339435Z  at org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40) ~[weld-web-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T13:37:53.808343778Z  at org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50) ~[weld-web-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T13:37:53.808356555Z  at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:65) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T13:37:53.808361115Z  at com.sun.faces.application.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:66) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T13:37:53.808365604Z  at com.sun.faces.application.ActionListenerImpl.getNavigationOutcome(ActionListenerImpl.java:82) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T13:37:53.808369928Z  at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:71) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T13:37:53.808388558Z  at javax.faces.component.UIViewAction.broadcast(UIViewAction.java:548) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T13:37:53.808393993Z  at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:847) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T13:37:53.808398489Z  at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1396) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T13:37:53.808402830Z  at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:58) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T13:37:53.808407155Z  at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T13:37:53.808411414Z  at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T13:37:53.808415765Z  at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T13:37:53.808420020Z  at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T13:37:53.808424340Z  at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1410) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808428656Z  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808432939Z  at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1619) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808437329Z  at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:164) ~[websocket-servlet-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808441650Z  at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808445916Z  at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808450191Z  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:506) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808454401Z  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808458690Z  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:580) ~[jetty-security-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808462950Z  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808467155Z  at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808471513Z  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808475775Z  at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808480070Z  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1372) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808487508Z  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808491796Z  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:463) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808496029Z  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808500243Z  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808504468Z  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1294) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808508734Z  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808513217Z  at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808517485Z  at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808521730Z  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808526042Z  at org.eclipse.jetty.server.Server.handle(Server.java:562) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808530274Z  at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:406) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808534472Z  at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:663) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808538865Z  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:398) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808552752Z  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808557721Z  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319) ~[jetty-io-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808562167Z  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[jetty-io-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808566354Z  at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101) ~[jetty-io-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808572437Z  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412) ~[jetty-util-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808576967Z  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381) ~[jetty-util-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808581318Z  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268) ~[jetty-util-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808585682Z  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138) ~[jetty-util-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808589965Z  at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:378) [jetty-util-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808594194Z  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) [jetty-util-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808598459Z  at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) [jetty-util-10.0.6.jar:10.0.6]
2021-11-23T13:37:53.808602684Z  at java.lang.Thread.run(Thread.java:829) [?:?]
2021-11-23T13:38:05.856623383Z 2021-11-23 13:38:05,856 DEBUG [oxTrustScheduler_Worker-1] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:63) - Bound request ended
`

**Comment by syntrydy** [comment]
fixed
