### ISSUE TITLE
MySQL: Not possible to delete  a custom script

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxTrust#2113]
## Describe the issue

Trying to delete an existing or new custom script leads to an error.
## Steps To Reproduce
1. Go to person scripts
2. Add a new custom script
3. Try to delete it
4. See an error message

## Logs
`2021-11-23T14:58:32.402329912Z 2021-11-23 14:58:32,398 ERROR [qtp166794956-4818] [org.gluu.oxtrust.action.ManageCustomScriptAction] (ManageCustomScriptAction.java:208) - Failed to update custom scripts
2021-11-23T14:58:32.402360331Z org.gluu.persist.exception.EntryDeleteException: Failed to remove entry: 'inum=FF7F.C0F1,ou=scripts,o=gluu'
2021-11-23T14:58:32.402379462Z  at org.gluu.persist.sql.impl.SqlEntryManager.removeByDn(SqlEntryManager.java:293) ~[gluu-orm-sql-4.3.1-SNAPSHOT.jar:?]
2021-11-23T14:58:32.402385342Z  at org.gluu.persist.impl.BaseEntryManager.remove(BaseEntryManager.java:484) ~[gluu-orm-core-4.3.1-SNAPSHOT.jar:?]
2021-11-23T14:58:32.402390374Z  at org.gluu.persist.sql.impl.SqlEntryManager.remove(SqlEntryManager.java:164) ~[gluu-orm-sql-4.3.1-SNAPSHOT.jar:?]
2021-11-23T14:58:32.402395612Z  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
2021-11-23T14:58:32.402429191Z  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
2021-11-23T14:58:32.402434172Z  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2021-11-23T14:58:32.402439210Z  at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2021-11-23T14:58:32.402444611Z  at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T14:58:32.402449807Z  at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T14:58:32.402454742Z  at org.gluu.persist.PersistenceEntryManager$EntityManager$1037559104$Proxy$_$$_WeldClientProxy.remove(Unknown Source) ~[gluu-orm-core-4.3.1-SNAPSHOT.jar:?]
2021-11-23T14:58:32.402466545Z  at org.gluu.service.custom.script.AbstractCustomScriptService.remove(AbstractCustomScriptService.java:46) ~[oxcore-script-4.3.1-SNAPSHOT.jar:?]
2021-11-23T14:58:32.402471067Z  at org.gluu.service.custom.CustomScriptService$Proxy$_$$_WeldClientProxy.remove(Unknown Source) ~[oxcore-service-4.3.1-SNAPSHOT.jar:?]
2021-11-23T14:58:32.402475506Z  at org.gluu.oxtrust.action.ManageCustomScriptAction.save(ManageCustomScriptAction.java:204) ~[classes/:?]
2021-11-23T14:58:32.402480075Z  at org.gluu.oxtrust.action.ManageCustomScriptAction$Proxy$_$$_WeldSubclass.save$$super(Unknown Source) ~[classes/:?]
2021-11-23T14:58:32.402484283Z  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
2021-11-23T14:58:32.402488736Z  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
2021-11-23T14:58:32.402492907Z  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2021-11-23T14:58:32.402497298Z  at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2021-11-23T14:58:32.402502015Z  at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T14:58:32.402506341Z  at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T14:58:32.402510975Z  at org.gluu.service.security.SecurityInterceptor.invoke(SecurityInterceptor.java:55) ~[security-extension-cdi-4.3.1-SNAPSHOT.jar:?]
2021-11-23T14:58:32.402534792Z  at jdk.internal.reflect.GeneratedMethodAccessor196.invoke(Unknown Source) ~[?:?]
2021-11-23T14:58:32.402540342Z  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2021-11-23T14:58:32.402663245Z  at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2021-11-23T14:58:32.402667982Z  at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T14:58:32.402692512Z  at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T14:58:32.402696972Z  at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T14:58:32.402701555Z  at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T14:58:32.402915303Z  at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T14:58:32.402921401Z  at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T14:58:32.402932266Z  at org.gluu.oxtrust.action.ManageCustomScriptAction$Proxy$_$$_WeldSubclass.save(Unknown Source) ~[classes/:?]
2021-11-23T14:58:32.402937048Z  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
2021-11-23T14:58:32.402941336Z  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
2021-11-23T14:58:32.402945698Z  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2021-11-23T14:58:32.402950067Z  at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2021-11-23T14:58:32.402954505Z  at org.apache.el.parser.AstValue.invoke(AstValue.java:247) ~[org.mortbay.jasper.apache-el-9.0.29.jar:9.0.29]
2021-11-23T14:58:32.402968610Z  at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267) ~[org.mortbay.jasper.apache-el-9.0.29.jar:9.0.29]
2021-11-23T14:58:32.402973592Z  at org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40) ~[weld-web-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T14:58:32.402978135Z  at org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50) ~[weld-web-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T14:58:32.402982418Z  at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:65) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T14:58:32.402986772Z  at com.sun.faces.application.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:66) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T14:58:32.402991240Z  at com.sun.faces.application.ActionListenerImpl.getNavigationOutcome(ActionListenerImpl.java:82) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T14:58:32.402995550Z  at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:71) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T14:58:32.402999925Z  at javax.faces.component.UICommand.broadcast(UICommand.java:222) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T14:58:32.403004215Z  at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:847) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T14:58:32.403008485Z  at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1396) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T14:58:32.403012708Z  at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:58) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T14:58:32.403071493Z  at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T14:58:32.403075940Z  at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T14:58:32.403080360Z  at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T14:58:32.403084668Z  at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451) ~[jakarta.faces-2.3.14.jar:2.3.14]
2021-11-23T14:58:32.403089050Z  at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1410) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403093327Z  at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403097610Z  at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1619) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403102128Z  at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:164) ~[websocket-servlet-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403106445Z  at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403110673Z  at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1594) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403114945Z  at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:506) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403119188Z  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403123448Z  at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:580) ~[jetty-security-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403127688Z  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403146657Z  at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403151562Z  at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403155819Z  at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403160109Z  at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1372) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403169291Z  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403173812Z  at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:463) ~[jetty-servlet-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403178122Z  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403182442Z  at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403186774Z  at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1294) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403191101Z  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403195589Z  at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403199844Z  at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403204104Z  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403216243Z  at org.eclipse.jetty.server.Server.handle(Server.java:562) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403220564Z  at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:406) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403224827Z  at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:663) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403231374Z  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:398) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403235816Z  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) ~[jetty-server-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403242082Z  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319) ~[jetty-io-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403246444Z  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[jetty-io-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403250879Z  at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101) ~[jetty-io-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403255189Z  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412) ~[jetty-util-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403259862Z  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381) ~[jetty-util-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403268286Z  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268) ~[jetty-util-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403272777Z  at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138) ~[jetty-util-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403277222Z  at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:378) [jetty-util-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403284989Z  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) [jetty-util-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403289374Z  at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) [jetty-util-10.0.6.jar:10.0.6]
2021-11-23T14:58:32.403293971Z  at java.lang.Thread.run(Thread.java:829) [?:?]
2021-11-23T14:58:32.403298294Z Caused by: org.gluu.persist.exception.EntryPersistenceException: Failed to find entry: 'inum=FF7F.C0F1,ou=scripts,o=gluu'
2021-11-23T14:58:32.403304027Z  at org.gluu.persist.sql.impl.SqlEntryManager.exportEntry(SqlEntryManager.java:772) ~[gluu-orm-sql-4.3.1-SNAPSHOT.jar:?]
2021-11-23T14:58:32.403308681Z  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
2021-11-23T14:58:32.403313084Z  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
2021-11-23T14:58:32.403317422Z  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2021-11-23T14:58:32.403321814Z  at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2021-11-23T14:58:32.403326106Z  at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T14:58:32.403330459Z  at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T14:58:32.403335027Z  at org.gluu.persist.PersistenceEntryManager$EntityManager$1037559104$Proxy$_$$_WeldClientProxy.exportEntry(Unknown Source) ~[gluu-orm-core-4.3.1-SNAPSHOT.jar:?]
2021-11-23T14:58:32.403339302Z  at org.gluu.oxtrust.service.LdifArchiver.onBeforeRemove(LdifArchiver.java:62) ~[classes/:?]
2021-11-23T14:58:32.403346724Z  at org.gluu.persist.sql.impl.SqlEntryManager.removeByDn(SqlEntryManager.java:286) ~[gluu-orm-sql-4.3.1-SNAPSHOT.jar:?]
2021-11-23T14:58:32.403351774Z  ... 89 more
2021-11-23T14:58:32.403356298Z Caused by: java.lang.NullPointerException
2021-11-23T14:58:32.403360665Z  at com.google.common.base.CharMatcher.matchesAllOf(CharMatcher.java:509) ~[guava-31.0.1-jre.jar:?]
2021-11-23T14:58:32.403365003Z  at com.google.common.base.CharMatcher$Negated.matchesNoneOf(CharMatcher.java:1514) ~[guava-31.0.1-jre.jar:?]
2021-11-23T14:58:32.403369306Z  at com.google.common.base.CharMatcher.matchesAnyOf(CharMatcher.java:495) ~[guava-31.0.1-jre.jar:?]
2021-11-23T14:58:32.403373846Z  at com.querydsl.sql.SQLTemplates.requiresQuotes(SQLTemplates.java:832) ~[querydsl-sql-4.4.0.jar:?]
2021-11-23T14:58:32.403378173Z  at com.querydsl.sql.SQLTemplates.quoteIdentifier(SQLTemplates.java:824) ~[querydsl-sql-4.4.0.jar:?]
2021-11-23T14:58:32.403382653Z  at com.querydsl.sql.SQLSerializer.appendTableName(SQLSerializer.java:108) ~[querydsl-sql-4.4.0.jar:?]
2021-11-23T14:58:32.403386971Z  at com.querydsl.sql.SQLSerializer.handleJoinTarget(SQLSerializer.java:210) ~[querydsl-sql-4.4.0.jar:?]
2021-11-23T14:58:32.403391218Z  at com.querydsl.sql.SQLSerializer.serializeSources(SQLSerializer.java:674) ~[querydsl-sql-4.4.0.jar:?]
2021-11-23T14:58:32.403395443Z  at com.querydsl.sql.SQLSerializer.serializeForQuery(SQLSerializer.java:348) ~[querydsl-sql-4.4.0.jar:?]
2021-11-23T14:58:32.403399665Z  at com.querydsl.sql.SQLTemplates.serialize(SQLTemplates.java:855) ~[querydsl-sql-4.4.0.jar:?]
2021-11-23T14:58:32.403404083Z  at com.querydsl.sql.SQLSerializer.serialize(SQLSerializer.java:221) ~[querydsl-sql-4.4.0.jar:?]
2021-11-23T14:58:32.403408298Z  at com.querydsl.sql.ProjectableSQLQuery.serialize(ProjectableSQLQuery.java:493) ~[querydsl-sql-4.4.0.jar:?]
2021-11-23T14:58:32.403412525Z  at com.querydsl.sql.AbstractSQLQuery.getResults(AbstractSQLQuery.java:277) ~[querydsl-sql-4.4.0.jar:?]
2021-11-23T14:58:32.403419773Z  at org.gluu.persist.sql.operation.impl.SqlOperationServiceImpl.lookupImpl(SqlOperationServiceImpl.java:363) ~[gluu-orm-sql-4.3.1-SNAPSHOT.jar:?]
2021-11-23T14:58:32.403424175Z  at org.gluu.persist.sql.operation.impl.SqlOperationServiceImpl.lookup(SqlOperationServiceImpl.java:344) ~[gluu-orm-sql-4.3.1-SNAPSHOT.jar:?]
2021-11-23T14:58:32.403428525Z  at org.gluu.persist.sql.impl.SqlEntryManager.exportEntry(SqlEntryManager.java:764) ~[gluu-orm-sql-4.3.1-SNAPSHOT.jar:?]
2021-11-23T14:58:32.403432808Z  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
2021-11-23T14:58:32.403437041Z  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
2021-11-23T14:58:32.403441213Z  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
2021-11-23T14:58:32.403445601Z  at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
2021-11-23T14:58:32.403449973Z  at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T14:58:32.403454583Z  at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.1.8.Final.jar:3.1.8.Final]
2021-11-23T14:58:32.403459026Z  at org.gluu.persist.PersistenceEntryManager$EntityManager$1037559104$Proxy$_$$_WeldClientProxy.exportEntry(Unknown Source) ~[gluu-orm-core-4.3.1-SNAPSHOT.jar:?]
2021-11-23T14:58:32.403463388Z  at org.gluu.oxtrust.service.LdifArchiver.onBeforeRemove(LdifArchiver.java:62) ~[classes/:?]
2021-11-23T14:58:32.403467690Z  at org.gluu.persist.sql.impl.SqlEntryManager.removeByDn(SqlEntryManager.java:286) ~[gluu-orm-sql-4.3.1-SNAPSHOT.jar:?]
2021-11-23T14:58:32.403472025Z  ... 89 more
2021-11-23T14:58:35.858605241Z 2021-11-23 14:58:35,858 INFO  [Thread-4253] [org.gluu.service.logger.LoggerService] (LoggerService.java:205) - Updated log level of '127' loggers to INFO

`

**Comment by syntrydy** [comment]
Fixed
