### ISSUE TITLE
Cache refresh throws Failed to delete entries error on log, however it is working fine.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2192]
## Describe the issue

Cache refresh throws Failed to delete entries error in log, howerver it is working fine. 

## Steps To Reproduce
1. Go to admin UI
2. Click on Configuration
3. Go to cache refresh 
4. configure cache refresh with External AD
5. wait till cache refresh pull the data from AD.
6. check the cache refresh log.

### cache refresh log

																										
```
 2022-06-30 10:48:02,851 ERROR [ForkJoinPool.commonPool-worker-7] [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (CacheRefreshTimer.java:793) - Failed to remove person entry with inum '0000!FC6A.2EB9' and DN: inum=0000!FC6A.2EB9,ou=people,o=gluu
org.gluu.persist.exception.EntryDeleteException: Failed to remove entry: inum=0000!FC6A.2EB9,ou=people,o=gluu
	at org.gluu.persist.ldap.impl.LdapEntryManager.removeRecursivelyFromDn(LdapEntryManager.java:364) ~[gluu-orm-ldap-4.4.1-SNAPSHOT.jar:?]
	at org.gluu.persist.impl.BaseEntryManager.removeRecursively(BaseEntryManager.java:504) ~[gluu-orm-core-4.4.1-SNAPSHOT.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.gluu.persist.PersistenceEntryManager$EntityManager$1037559104$Proxy$_$$_WeldClientProxy.removeRecursively(Unknown Source) ~[gluu-orm-core-4.4.1-SNAPSHOT.jar:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.removeTargetEntries(CacheRefreshTimer.java:790) ~[classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.detectChangedEntries(CacheRefreshTimer.java:465) ~[classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.processImpl(CacheRefreshTimer.java:302) ~[classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.processInt(CacheRefreshTimer.java:201) ~[classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer$Proxy$_$$_WeldSubclass.processInt(Unknown Source) ~[classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.process(CacheRefreshTimer.java:185) ~[classes/:?]
	at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer$Proxy$_$$_WeldSubclass.process$$super(Unknown Source) ~[classes/:?]
	at jdk.internal.reflect.GeneratedMethodAccessor250.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.gluu.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:36) ~[oxcore-service-4.4.1-SNAPSHOT.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: org.gluu.persist.exception.EntryPersistenceException: Failed to find entry: inum=0000!FC6A.2EB9,ou=people,o=gluu
	at org.gluu.persist.ldap.impl.LdapEntryManager.exportEntry(LdapEntryManager.java:880) ~[gluu-orm-ldap-4.4.1-SNAPSHOT.jar:?]
	at org.gluu.persist.ldap.impl.LdapEntryManager.exportEntry(LdapEntryManager.java:886) ~[gluu-orm-ldap-4.4.1-SNAPSHOT.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.gluu.persist.PersistenceEntryManager$EntityManager$1037559104$Proxy$_$$_WeldClientProxy.exportEntry(Unknown Source) ~[gluu-orm-core-4.4.1-SNAPSHOT.jar:?]
	at org.gluu.oxtrust.service.LdifArchiver.onBeforeRemove(LdifArchiver.java:62) ~[classes/:?]
	at org.gluu.persist.ldap.impl.LdapEntryManager.removeRecursivelyFromDn(LdapEntryManager.java:354) ~[gluu-orm-ldap-4.4.1-SNAPSHOT.jar:?]
	... 28 more
Caused by: org.gluu.persist.exception.operation.SearchException: Failed to lookup entry by DN: 'inum=0000!FC6A.2EB9,ou=people,o=gluu'
	at org.gluu.persist.ldap.operation.impl.LdapOperationServiceImpl.lookupImpl(LdapOperationServiceImpl.java:629) ~[gluu-orm-ldap-4.4.1-SNAPSHOT.jar:?]
	at org.gluu.persist.ldap.operation.impl.LdapOperationServiceImpl.lookup(LdapOperationServiceImpl.java:605) ~[gluu-orm-ldap-4.4.1-SNAPSHOT.jar:?]
	at org.gluu.persist.ldap.impl.LdapEntryManager.exportEntry(LdapEntryManager.java:871) ~[gluu-orm-ldap-4.4.1-SNAPSHOT.jar:?]
	at org.gluu.persist.ldap.impl.LdapEntryManager.exportEntry(LdapEntryManager.java:886) ~[gluu-orm-ldap-4.4.1-SNAPSHOT.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.gluu.persist.PersistenceEntryManager$EntityManager$1037559104$Proxy$_$$_WeldClientProxy.exportEntry(Unknown Source) ~[gluu-orm-core-4.4.1-SNAPSHOT.jar:?]
	at org.gluu.oxtrust.service.LdifArchiver.onBeforeRemove(LdifArchiver.java:62) ~[classes/:?]
	at org.gluu.persist.ldap.impl.LdapEntryManager.removeRecursivelyFromDn(LdapEntryManager.java:354) ~[gluu-orm-ldap-4.4.1-SNAPSHOT.jar:?]
	... 28 more
```
### Complete log

[cache-refresh.log](https://github.com/GluuFederation/oxTrust/files/9018496/cache-refresh.log)

**Comment by MohitMaliFtechiz** [comment]
hi @shekhar16 after some testing, i found out the issue is arriving when the gluu-server  is reinstalled on same vm and run the cache refresh. on a fresh vm the issue is not reproduced. it needs more testing to find the real cause for this. i am closing this ticket for now.
