### ISSUE TITLE
fix: unable to create document due to incorrect integer value

### ISSUE THREAD

**Issue by iromli** [GluuFederation/oxTrust#2256]
## Describe the issue

Failed to write to oxDocument.document attribute when using MySQL.

## Steps To Reproduce
1. Go oxTrust UI
2. Go to JSON Configuration > Store Provider Configuration, and select `DB` in Document store Type dropdown.
3. Restart oxTrust
4. Add new Trust Relationship
5. See error below

```
2022-10-18 06:57:00,108 INFO  [main] [org.gluu.oxtrust.service.ShibbolethInitializer] (ShibbolethInitializer.java:47) - ########## shibbolethVersion =
 v3                                                                                                                                                   
2022-10-18 06:57:00,670 INFO  [main] [org.gluu.oxtrust.service.Shibboleth3ConfService] (Shibboleth3ConfService.java:1233) - >>>>>>>>>> IN Shibboleth3C
onfService.generateMetadataFiles()...                                                                                                                 
2022-10-18 06:57:00,687 INFO  [main] [org.gluu.oxtrust.service.ApplicationFactory] (ApplicationFactory.java:92) - Document store configuration: Docume
ntStoreConfiguration [documentStoreType=DB, localConfiguration=LocalConfiguration [baseLocation=/], jcaConfiguration=JcaDocumentStoreConfiguration [se
rverUrl=http://jackrabbit:8080/rmi, workspaceName=default, connectionTimeout=15, userId=admin], webDavConfiguration=null, DBConfiguration=null]       
2022-10-18 06:57:00,769 ERROR [main] [gluu.service.document.store.provider.DBDocumentStoreProvider] (DBDocumentStoreProvider.java:133) - Failed to wri
te document from stream to file '/etc/certs/idp-signing.crt'                                                                                          
org.gluu.persist.exception.EntryPersistenceException: Failed to persist entry: 'inum=dfc6dd55-4f11-4e30-826c-28dcede5f3af,ou=document,o=gluu'         
        at org.gluu.persist.sql.impl.SqlEntryManager.persist(SqlEntryManager.java:221) ~[gluu-orm-sql-4.4.2-SNAPSHOT.jar:?]                           
        at org.gluu.persist.impl.BaseEntryManager.persist(BaseEntryManager.java:127) ~[gluu-orm-
core-4.4.2-SNAPSHOT.jar:?]                            
Caused by: org.gluu.persist.exception.operation.PersistenceException: Failed to add entry
        at org.gluu.persist.sql.operation.impl.SqlOperationServiceImpl.addEntryImpl(SqlOperationServiceImpl.java:196) ~[gluu-orm-sql-4.4.2-SNAPSHOT.ja
r:?]
        at org.gluu.persist.sql.operation.impl.SqlOperationServiceImpl.addEntry(SqlOperationServiceImpl.java:165) ~[gluu-orm-sql-4.4.2-SNAPSHOT.jar:?]
        at org.gluu.persist.sql.impl.SqlEntryManager.persist(SqlEntryManager.java:216) ~[gluu-orm-sql-4.4.2-SNAPSHOT.jar:?]
        ... 42 more
Caused by: com.querydsl.core.QueryException: Caught SQLException for insert into gluu.oxDocument (creationDate, description, displayName, document, in
um, oxEnabled, oxModuleProperty, objectClass, dn, doc_id)
values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
at org.gluu.persist.sql.impl.SqlEntryManager.persist(SqlEntryManager.java:216) ~[gluu-orm-sql-4.4.2-SNAPSHOT.jar:?]
        ... 42 more
Caused by: java.sql.SQLException: Incorrect integer value: 'true' for column 'oxEnabled' at row 1
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[mysql-connector-java-8.0.28.jar:8.0.28]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.28.jar:8.0.2
8]

```

## Expected behavior

Document created without any errors.

## Actual behavior

See errors above.

## Additional context

The `oxDocument.document` column type is `smallint` as created by CE and CN installers.

```
mysql> show columns in oxDocument where Field = 'oxEnabled';
+-----------+----------+------+-----+---------+-------+
| Field     | Type     | Null | Key | Default | Extra |
+-----------+----------+------+-----+---------+-------+
| oxEnabled | smallint | YES  |     | NULL    |       |
+-----------+----------+------+-----+---------+-------+
```

**Comment by shekhar16** [comment]
issue Fixed. Code has been merged to master branch.
Closing this ticket.
