### ISSUE TITLE
fix: NPE is thrown when using DB document store

### ISSUE THREAD

**Issue by iromli** [GluuFederation/oxTrust#2273]
## Describe the issue

When using DB document store, during oxTrust startup, the following NPE is thrown.

## Steps To Reproduce
1. Deploy Gluu Server 4.5.0-SNAPSHOT
2. Change document store type to `DB`
3. Restart oxTrust
4. See error during oxTrust startup

```
2022-12-05 18:44:42,766 ERROR [main] [org.gluu.oxtrust.service.Shibboleth3ConfService] (Shibboleth3ConfService.java:1303) - Unable to get IDP 3 signin
g certificate from /etc/certs/idp-signing.crt                                                                                                         
java.lang.NullPointerException: null                                                                                                                  
        at org.gluu.oxtrust.service.Shibboleth3ConfService.generateMetadataFiles(Shibboleth3ConfService.java:1299) ~[oxtrust-service-4.5.0-SNAPSHOT.ja
r:?]                                                                                                                                                  
        at org.gluu.oxtrust.service.Shibboleth3ConfService$Proxy$_$$_WeldClientProxy.generateMetadataFiles(Unknown Source) ~[oxtrust-service-4.5.0-SNA
PSHOT.jar:?]                                                                                                                                          
        at org.gluu.oxtrust.service.ShibbolethInitializer.createShibbolethConfiguration(ShibbolethInitializer.java:48) ~[classes/:?]                  
        at org.gluu.oxtrust.service.ShibbolethInitializer$Proxy$_$$_WeldClientProxy.createShibbolethConfiguration(Unknown Source) ~[classes/:?]       
        at org.gluu.oxtrust.service.AppInitializer.applicationInitialized(AppInitializer.java:203) ~[classes/:?]                                      
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final
]
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final
]
        at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168) ~[weld-core-impl
-3.1.9.Final.jar:3.1.9.Final]
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
        at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124) ~[jakarta.enterprise.cdi-api-2.0.2.jar:?]
        at org.jboss.weld.util.Observers.notify(Observers.java:166) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
        at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
        at org.jboss.weld.bootstrap.BeanDeploymentModule.fireEvent(BeanDeploymentModule.java:93) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
        at org.jboss.weld.module.web.servlet.HttpContextLifecycle.fireEventForApplicationScope(HttpContextLifecycle.java:161) ~[weld-web-3.1.9.Final.j
ar:3.1.9.Final]
        at org.jboss.weld.module.web.servlet.HttpContextLifecycle.contextInitialized(HttpContextLifecycle.java:147) ~[weld-web-3.1.9.Final.jar:3.1.9.F
inal]
        at org.jboss.weld.module.web.servlet.WeldInitialListener.contextInitialized(WeldInitialListener.java:99) ~[weld-web-3.1.9.Final.jar:3.1.9.Fina
l]
        at org.jboss.weld.servlet.api.helpers.ForwardingServletListener.contextInitialized(ForwardingServletListener.java:34) ~[weld-spi-3.1.SP4.jar:3
.1.0.SP4]
        at org.jboss.weld.environment.servlet.EnhancedListener.onStartup(EnhancedListener.java:66) ~[weld-servlet-core-3.1.9.Final.jar:3.1.9.Final]
        at org.eclipse.jetty.servlet.ServletContainerInitializerHolder.doStart(ServletContainerInitializerHolder.java:148) ~[?:?]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[?:?]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) ~[?:?]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) ~[?:?]
        at org.eclipse.jetty.servlet.ServletContextHandler$ServletContainerInitializerStarter.doStart(ServletContextHandler.java:1660) ~[?:?]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[?:?]
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:369) ~[?:?]
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1304) ~[?:?]
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:889) ~[?:?]
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306) ~[?:?]
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532) ~[?:?]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[?:?]
        at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:40) ~[?:?]
        at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:183) ~[?:?]
        at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:516) ~[?:?]
        at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:151) ~[?:?]
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:186) ~[?:?]
        at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:439) ~[?:?]
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:58) ~[?:?]
        at org.eclipse.jetty.util.Scanner$DiscreteListener.pathAdded(Scanner.java:282) ~[?:?]
        at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:836) ~[?:?]
        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:802) ~[?:?]
        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:709) ~[?:?]
        at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:597) ~[?:?]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[?:?]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) ~[?:?]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121) ~[?:?]
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:158) ~[?:?]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[?:?]
        at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:605) ~[?:?]
        at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:246) ~[?:?]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[?:?]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) ~[?:?]
        at org.eclipse.jetty.server.Server.start(Server.java:469) ~[?:?]
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121) ~[?:?]
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) ~[?:?]
        at org.eclipse.jetty.server.Server.doStart(Server.java:414) ~[?:?]
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[?:?]
        at org.eclipse.jetty.xml.XmlConfiguration.lambda$main$4(XmlConfiguration.java:1867) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1810) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:226) ~[?:?]
        at org.eclipse.jetty.start.Main.start(Main.java:502) ~[?:?]
        at org.eclipse.jetty.start.Main.main(Main.java:73) ~[?:?]
2022-12-05 18:44:42,825 INFO  [main] [org.gluu.oxtrust.service.Shibboleth3ConfService] (Shibboleth3ConfService.java:287) - >>>>>>>>>> IN Shibboleth3ConfService.generateConfigurationFiles()...
```

## Additional context

The `LOCAL` document store type is not affected.

**Comment by iromli** [comment]
Tested using latest 4.5.0-SNAPSHOT and the error is gone.
