### ISSUE TITLE
Regex pattern validation on Password attributes causes error when creating user

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#2310]
## Description
As pointed out by customer in ticket 11134, when creating a new user, oxTrust will throw an error at the moment admin steps into "Confirm password" field when a particular regex is set as "Regex Pattern" for "Password" attribute. The customer tried to use this approach to ensure strict password policies, as they are creating users via oxTrust (that includes self-registration as well).
Assigned high priority because customer insists the issue disrupts their workflows. We may need to backport the fix to the version they use (4.4)

## Steps To Reproduce
1. Login to oxTrust
2. Move to "Attributes" page
3. Edit attribute "Password" by adding next regex as "Regex pattern" property: `^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–[{}]:;'.,?/*~$^+=<>]).{8,32}$`
4. Move to "Users" > "Add person" page
5. Click on the "Password" field and input next string (works for any string that contains special character): `1q2w3e$R` 
6. Click on the "Confirm Password" field

## Expected behavior
All fields can be filled and user can be created. For all attributes with custom validation rules these rules must be enforced, or user creation attempt must fail

## Actual behavior
oxTrust redirects to an error page. No errors is logged to `oxtrust.log`

**Comment by mzico** [comment]
@aliaksander-samuseu @shekhar16 : below error appearing in oxtrust.log: 

```
2023-03-23 17:57:09,681 TRACE [qtp952562199-19] [org.gluu.oxtrust.exception.GlobalExceptionHandler] (GlobalExceptionHandler.java:58) - javax.el.ELException: //opt/jetty-10.0/temp/jetty-localhost-8082-identity_war-_identity-any-4542728865167733874/webapp/WEB-INF/incl/person/userForm.xhtml @252,157 validator="#{updatePersonAction.validateConfirmPassword}": java.lang.NullPointerException
javax.faces.FacesException: javax.el.ELException: //opt/jetty-10.0/temp/jetty-localhost-8082-identity_war-_identity-any-4542728865167733874/webapp/WEB-INF/incl/person/userForm.xhtml @252,157 validator="#{updatePersonAction.validateConfirmPassword}": java.lang.NullPointerException
	at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:61) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1410) ~[jetty-servlet-10.0.9.jar:10.0.9]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) ~[jetty-servlet-10.0.9.jar:10.0.9]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1630) ~[jetty-servlet-10.0.9.jar:10.0.9]
	at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:170) ~[websocket-servlet-10.0.9.jar:10.0.9]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1600) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:506) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131) ~[?:?]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578) ~[?:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223) ~[?:?]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1571) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1378) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:463) ~[?:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1544) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1300) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192) ~[?:?]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51) ~[?:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[?:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:562) ~[?:?]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505) ~[?:?]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762) ~[?:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497) ~[?:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) ~[?:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319) ~[?:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[?:?]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:412) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:381) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:268) ~[?:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:138) ~[?:?]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:407) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) ~[?:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: javax.faces.FacesException: javax.el.ELException: //opt/jetty-10.0/temp/jetty-localhost-8082-identity_war-_identity-any-4542728865167733874/webapp/WEB-INF/incl/person/userForm.xhtml @252,157 validator="#{updatePersonAction.validateConfirmPassword}": java.lang.NullPointerException
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:269) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65) ~[primefaces-8.0.jar:8.0]
	at org.richfaces.context.ExtendedPartialViewContext.processPartial(ExtendedPartialViewContext.java:264) ~[richfaces-core-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at javax.faces.context.PartialViewContextWrapper.processPartial(PartialViewContextWrapper.java:228) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at org.omnifaces.context.OmniPartialViewContext.processPartial(OmniPartialViewContext.java:124) ~[omnifaces-2.6.9.jar:2.6.9]
	at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1308) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:53) ~[jakarta.faces-2.3.18.jar:2.3.18]
	... 43 more
Caused by: javax.el.ELException: //opt/jetty-10.0/temp/jetty-localhost-8082-identity_war-_identity-any-4542728865167733874/webapp/WEB-INF/incl/person/userForm.xhtml @252,157 validator="#{updatePersonAction.validateConfirmPassword}": java.lang.NullPointerException
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:71) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.validator.MethodExpressionValidator.validate(MethodExpressionValidator.java:85) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIInput.validateValue(UIInput.java:1232) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIInput.validate(UIInput.java:1021) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIInput.executeValidate(UIInput.java:1318) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIInput.processValidators(UIInput.java:733) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:621) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at org.richfaces.context.MetaComponentProcessingVisitCallback.visit(MetaComponentProcessingVisitCallback.java:73) ~[richfaces-core-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.richfaces.context.BaseExtendedVisitContext.invokeVisitCallback(BaseExtendedVisitContext.java:103) ~[richfaces-core-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.richfaces.context.ExtendedExecuteVisitContext.invokeVisitCallback(ExtendedExecuteVisitContext.java:55) ~[richfaces-core-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1457) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at org.richfaces.component.UIDataAdaptor$DataVisitorForVisitTree.process(UIDataAdaptor.java:207) ~[richfaces-a4j-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.ajax4jsf.model.SequenceDataModel.walk(SequenceDataModel.java:66) ~[richfaces-core-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.richfaces.component.UIDataAdaptor.walk(UIDataAdaptor.java:817) ~[richfaces-a4j-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.richfaces.component.UIDataAdaptor.visitDataChildren(UIDataAdaptor.java:1290) ~[richfaces-a4j-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.richfaces.component.UIDataAdaptor.visitTree(UIDataAdaptor.java:1368) ~[richfaces-a4j-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at org.richfaces.component.UIDataAdaptor$DataVisitorForVisitTree.process(UIDataAdaptor.java:207) ~[richfaces-a4j-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.ajax4jsf.model.SequenceDataModel.walk(SequenceDataModel.java:66) ~[richfaces-core-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.richfaces.component.UIDataAdaptor.walk(UIDataAdaptor.java:817) ~[richfaces-a4j-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.richfaces.component.UIDataAdaptor.visitDataChildren(UIDataAdaptor.java:1290) ~[richfaces-a4j-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.richfaces.component.UIDataAdaptor.visitTree(UIDataAdaptor.java:1368) ~[richfaces-a4j-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIForm.visitTree(UIForm.java:356) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:413) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:262) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65) ~[primefaces-8.0.jar:8.0]
	at org.richfaces.context.ExtendedPartialViewContext.processPartial(ExtendedPartialViewContext.java:264) ~[richfaces-core-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at javax.faces.context.PartialViewContextWrapper.processPartial(PartialViewContextWrapper.java:228) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at org.omnifaces.context.OmniPartialViewContext.processPartial(OmniPartialViewContext.java:124) ~[omnifaces-2.6.9.jar:2.6.9]
	at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1308) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:53) ~[jakarta.faces-2.3.18.jar:2.3.18]
	... 43 more
Caused by: java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1770) ~[?:?]
	at java.util.regex.Matcher.reset(Matcher.java:416) ~[?:?]
	at java.util.regex.Matcher.<init>(Matcher.java:253) ~[?:?]
	at java.util.regex.Pattern.matcher(Pattern.java:1133) ~[?:?]
	at org.gluu.oxtrust.action.UpdatePersonAction.validateConfirmPassword(UpdatePersonAction.java:899) ~[classes/:?]
	at org.gluu.oxtrust.action.UpdatePersonAction$Proxy$_$$_WeldSubclass.validateConfirmPassword$$super(Unknown Source) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.gluu.service.security.SecurityInterceptor.invoke(SecurityInterceptor.java:55) ~[security-extension-cdi-4.5.0.Final.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor266.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.gluu.oxtrust.action.UpdatePersonAction$Proxy$_$$_WeldSubclass.validateConfirmPassword(Unknown Source) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.apache.el.parser.AstValue.invoke(AstValue.java:246) ~[org.mortbay.jasper.apache-el-9.0.52.jar:9.0.52]
	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:266) ~[org.mortbay.jasper.apache-el-9.0.52.jar:9.0.52]
	at org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40) ~[weld-web-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50) ~[weld-web-3.1.9.Final.jar:3.1.9.Final]
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:65) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.validator.MethodExpressionValidator.validate(MethodExpressionValidator.java:85) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIInput.validateValue(UIInput.java:1232) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIInput.validate(UIInput.java:1021) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIInput.executeValidate(UIInput.java:1318) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIInput.processValidators(UIInput.java:733) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:621) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at org.richfaces.context.MetaComponentProcessingVisitCallback.visit(MetaComponentProcessingVisitCallback.java:73) ~[richfaces-core-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.richfaces.context.BaseExtendedVisitContext.invokeVisitCallback(BaseExtendedVisitContext.java:103) ~[richfaces-core-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.richfaces.context.ExtendedExecuteVisitContext.invokeVisitCallback(ExtendedExecuteVisitContext.java:55) ~[richfaces-core-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1457) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at org.richfaces.component.UIDataAdaptor$DataVisitorForVisitTree.process(UIDataAdaptor.java:207) ~[richfaces-a4j-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.ajax4jsf.model.SequenceDataModel.walk(SequenceDataModel.java:66) ~[richfaces-core-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.richfaces.component.UIDataAdaptor.walk(UIDataAdaptor.java:817) ~[richfaces-a4j-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.richfaces.component.UIDataAdaptor.visitDataChildren(UIDataAdaptor.java:1290) ~[richfaces-a4j-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.richfaces.component.UIDataAdaptor.visitTree(UIDataAdaptor.java:1368) ~[richfaces-a4j-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at org.richfaces.component.UIDataAdaptor$DataVisitorForVisitTree.process(UIDataAdaptor.java:207) ~[richfaces-a4j-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.ajax4jsf.model.SequenceDataModel.walk(SequenceDataModel.java:66) ~[richfaces-core-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.richfaces.component.UIDataAdaptor.walk(UIDataAdaptor.java:817) ~[richfaces-a4j-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.richfaces.component.UIDataAdaptor.visitDataChildren(UIDataAdaptor.java:1290) ~[richfaces-a4j-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at org.richfaces.component.UIDataAdaptor.visitTree(UIDataAdaptor.java:1368) ~[richfaces-a4j-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIForm.visitTree(UIForm.java:356) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1469) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:413) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:262) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65) ~[primefaces-8.0.jar:8.0]
	at org.richfaces.context.ExtendedPartialViewContext.processPartial(ExtendedPartialViewContext.java:264) ~[richfaces-core-4.5.19-gluu.Final.jar:4.5.19-gluu.Final]
	at javax.faces.context.PartialViewContextWrapper.processPartial(PartialViewContextWrapper.java:228) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at org.omnifaces.context.OmniPartialViewContext.processPartial(OmniPartialViewContext.java:124) ~[omnifaces-2.6.9.jar:2.6.9]
	at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1308) ~[jakarta.faces-2.3.18.jar:2.3.18]
	at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:53) ~[jakarta.faces-2.3.18.jar:2.3.18]
	... 43 more
```
