### ISSUE TITLE
fix(oxtrust): client search fail with NPE if there is client without "displayName" attribute set

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxTrust#2348]
## Describe the issue

1. register client without "displayName"
2. Go to UI and try to search client
Result: error is shown

```
2023-06-28 12:32:31,797 ERROR [qtp1199673596-16] [org.gluu.oxtrust.action.SearchClientAction] (SearchClientAction.java:83) - Failed to find clients
java.lang.NullPointerException: null
	at java.util.Comparator.lambda$comparing$77a9974f$1(Comparator.java:469) ~[?:?]
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?]
	at java.util.TimSort.sort(TimSort.java:220) ~[?:?]
	at java.util.Arrays.sort(Arrays.java:1515) ~[?:?]
	at java.util.ArrayList.sort(ArrayList.java:1750) ~[?:?]
	at org.gluu.oxtrust.action.SearchClientAction.searchImpl(SearchClientAction.java:79) ~[classes/:?]
```

## Expected behavior
It must not fail.

## Actual behavior
Fail

## Screenshots

![image](https://github.com/GluuFederation/oxTrust/assets/2013070/4b8009f9-731e-47ae-9249-91d333fd7ef7)

**Comment by shekhar16** [comment]
Code has been merged.
closing this ticket.
