### ISSUE TITLE
User Registration Error

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#237]
OS: CentOS 6.6, Package:1-3.centos
When I navigate to Custom Scripts and click on User Registration tab, I see errors in Red appearing on the WebUi and the following show up in the wrapper.log

>SEVERE: //localhost/identity/WEB-INF/incl/script/customScriptListForm.xhtml @72,137 value="#{_customScript.locationType}": Error writing 'locationType' on type org.xdi.model.custom.script.model.CustomScript
INFO   | jvm 1    | 2016/04/21 23:41:15 | javax.el.ELException: //localhost/identity/WEB-INF/incl/script/customScriptListForm.xhtml @72,137 value="#{_customScript.locationType}": Error writing 'locationType' on type org.xdi.model.custom.script.model.CustomScript
INFO   | jvm 1    | 2016/04/21 23:41:15 | 	at com.sun.faces.facelets.el.TagValueExpression.setValue(TagValueExpression.java:139)
INFO   | jvm 1    | 2016/04/21 23:41:15 | 	at javax.faces.component.UIInput.updateModel(UIInput.java:818)
INFO   | jvm 1    | 2016/04/21 23:41:15 | 	at javax.faces.component.UIInput.processUpdates(UIInput.java:735)

**Comment by zamilskhan** [comment]
Closing as there is an existing case #140
