### ISSUE TITLE
`oxPasswordExpirationDate` not following ISO 8601 format

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#2376]
I am trying to use `oxPasswordExpirationDate` attribute for my authentication script but I am unable to find a proper format how we should insert this value. 

According to code, it should follow ISO 8601 format but that's not happening. 

I tried: 

 - Format: `2023-10-03`
 - Format: `20231003`
 - Format: `20000123T012345.678+0900`
 
 But still getting error from oxTrust: 
 
 ```
 2023-10-03 02:55:13,654 ERROR [qtp733943822-15] [org.gluu.oxtrust.action.UpdatePersonAction] (UpdatePersonAction.java:589) - Failed to update person 9c69623d-5270-440c-96c2-097e0b88272f
java.lang.Exception: Duplicate UID value: mohib
	at org.gluu.oxtrust.service.PersonService.updatePerson(PersonService.java:141) ~[oxtrust-service-4.2.3.Final.jar:?]
	at org.gluu.oxtrust.service.PersonService$Proxy$_$$_WeldClientProxy.updatePerson(Unknown Source) ~[oxtrust-service-4.2.3.Final.jar:?]
....
....
....
Caused by: com.unboundid.ldap.sdk.LDAPException: When attempting to modify entry inum=9c69623d-5270-440c-96c2-097e0b88272f,ou=people,o=gluu to add one or more values for attribute oxPasswordExpirationDate, value "20000123T012345.678+0900" was found to be invalid according to the associated syntax: The provided value "20000123T012345.678+0900" is not a valid generalized time value because "T0" is not a valid hour specification
```

![Screenshot from 2023-10-03 08-56-45](https://github.com/GluuFederation/oxTrust/assets/7156097/abbbef75-867c-4f3f-a428-9f4a6ed7d5db)

**How to reproduce**

 - Register a custom attribute with name  `oxPasswordExpirationDate`
 - Open any user's profile and try to insert this attribute to this user's profile.

**Comment by shekhar16** [comment]
we have to save the value as similar to oxCreationTimestamp like 20231004144807.231Z.

**Comment by shekhar16** [comment]
Discussed with @mzico 
closing this ticket.
