### ISSUE TITLE
getting password mismatch error on registration of a user on register.htm

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxTrust#2418]
!!! Note 
Unless you are Gluu staff, please first review and open an issue on https://support.gluu.org before opening an issue here. Thanks!

## Describe the issue
getting password mismatch error on registration of a user on register.htm

## Steps To Reproduce
1. enable user registration and confirmation script.
2. go to register.htm page
3. try to register a user via register.htm
4. see error 

## Expected behavior
A user must be registered  without any issue 

## Actual behavior
user gets register but throws password mismatch error. 

## Screenshots
![Screenshot (29)](https://github.com/GluuFederation/oxTrust/assets/34593983/51624ae8-9503-4fe4-8f21-1d1cc16cde09)

## Desktop (please complete the following information):
 - OS: [e.g. Ubuntu22.04
 - Gluu version 4.5.4
 - Database mysql, opendj

## Additional context

oxauth script.log
```
2024-04-25 06:33:33,013 INFO  [ForkJoinPool.commonPool-worker-3] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - Casa. init. Initialized successfully
2024-04-25 06:33:33,813 ERROR [ForkJoinPool.commonPool-worker-3] [org.gluu.service.PythonService] (PythonService.java:186) - Failed to load python file
org.python.core.PyException: ImportError: No module named notnoop
	at org.python.core.Py.ImportError(Py.java:327) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.import_logic(imp.java:1292) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.import_module_level(imp.java:1371) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.importName(imp.java:1544) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyObject.__call__(PyObject.java:433) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.__builtin__.__import__(__builtin__.java:1232) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.importFromAs(imp.java:1636) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.importFrom(imp.java:1611) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at gluu_common$py.f$0(/opt/gluu/python/libs/gluu_common.py:819) ~[?:?]
	at gluu_common$py.call_function(/opt/gluu/python/libs/gluu_common.py) ~[?:?]
	at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyCode.call(PyCode.java:18) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.createFromCode(imp.java:632) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.createFromSource(imp.java:585) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.loadFromSource(imp.java:946) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.find_module(imp.java:771) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.import_next(imp.java:1160) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.import_module_level(imp.java:1352) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.importName(imp.java:1544) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyObject.__call__(PyObject.java:433) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.__builtin__.__import__(__builtin__.java:1232) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.importFromAs(imp.java:1636) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.importFrom(imp.java:1611) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.pycode._pyx6.f$0(super_gluu_ro.py:23) ~[?:?]
	at org.python.pycode._pyx6.call_function(super_gluu_ro.py) ~[?:?]
	at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyCode.call(PyCode.java:18) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.Py.runCode(Py.java:1742) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:297) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.gluu.service.PythonService.loadPythonScript(PythonService.java:184) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.PythonService$Proxy$_$$_WeldClientProxy.loadPythonScript(Unknown Source) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager.createExternalTypeFromStringWithPythonException(CustomScriptManager.java:417) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.createExternalTypeFromStringWithPythonException(Unknown Source) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager.createExternalType(CustomScriptManager.java:385) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager.reloadCustomScriptConfigurations(CustomScriptManager.java:293) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager.reloadImpl(CustomScriptManager.java:182) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager.reload(CustomScriptManager.java:152) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager.initTimer(CustomScriptManager.java:107) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.initTimer$$super(Unknown Source) ~[oxcore-script-4.5.4.Final.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.gluu.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:36) ~[oxcore-service-4.5.4.Final.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
2024-04-25 06:33:33,842 ERROR [ForkJoinPool.commonPool-worker-3] [org.gluu.service.custom.script.CustomScriptManager] (CustomScriptManager.java:387) - Failed to prepare external type 'org.gluu.exception.PythonException: Failed to load python file 'java.io.ByteArrayInputStream@7bdd3890''
2024-04-25 06:33:33,951 INFO  [ForkJoinPool.commonPool-worker-3] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - Casa client registration. Initialization
2024-04-25 06:33:33,952 INFO  [ForkJoinPool.commonPool-worker-3] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - Casa client registration. Initialized successfully
2024-04-25 06:33:52,507 INFO  [qtp1714078840-16] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - RPT Policy. Authorizing ...
2024-04-25 06:33:52,511 INFO  [qtp1714078840-16] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - UmaRptPolicy. client_id = 1502.7f8fa6d8-99b7-4d61-a95c-c62e16c14118
2024-04-25 06:33:52,513 INFO  [qtp1714078840-16] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - UmaRptPolicy. Authorizing client
2024-04-25 07:34:31,884 INFO  [qtp1714078840-23] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - RPT Policy. Authorizing ...
2024-04-25 07:34:31,884 INFO  [qtp1714078840-23] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - UmaRptPolicy. client_id = 1502.7f8fa6d8-99b7-4d61-a95c-c62e16c14118
2024-04-25 07:34:31,884 INFO  [qtp1714078840-23] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - UmaRptPolicy. Authorizing client
2024-04-25 08:08:34,191 INFO  [oxAuthScheduler_Worker-4] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - RPT Policy. Destroyed successfully
2024-04-25 08:08:34,218 INFO  [oxAuthScheduler_Worker-4] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - RPT Policy. Initializing ...
2024-04-25 08:08:34,219 INFO  [oxAuthScheduler_Worker-4] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - RPT Policy. Initialized successfully
2024-04-25 08:08:34,222 INFO  [oxAuthScheduler_Worker-4] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - Super-Gluu-DynScope destroy
2024-04-25 08:08:34,222 INFO  [oxAuthScheduler_Worker-4] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - Super-Gluu-DynScope destroy complete
2024-04-25 08:08:34,240 INFO  [oxAuthScheduler_Worker-4] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - Super-Gluu-DynScope init
2024-04-25 08:08:34,241 INFO  [oxAuthScheduler_Worker-4] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - Super-Gluu-DynScope init complete
2024-04-25 08:08:34,243 INFO  [oxAuthScheduler_Worker-4] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - Permission dynamic scope. Destroy
2024-04-25 08:08:34,243 INFO  [oxAuthScheduler_Worker-4] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - Permission dynamic scope. Destroyed successfully
2024-04-25 08:08:34,261 INFO  [oxAuthScheduler_Worker-4] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - Permission dynamic scope. Initialization
2024-04-25 08:08:34,261 INFO  [oxAuthScheduler_Worker-4] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - Permission dynamic scope. Initialized successfully
2024-04-25 08:08:34,263 ERROR [oxAuthScheduler_Worker-4] [org.gluu.service.custom.script.CustomScriptManager] (CustomScriptManager.java:465) - null
java.lang.NullPointerException: null
	at org.gluu.service.custom.script.CustomScriptManager.executeCustomScriptDestroy(CustomScriptManager.java:463) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.executeCustomScriptDestroy(Unknown Source) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager.destroyCustomScript(CustomScriptManager.java:350) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager.reloadCustomScriptConfigurations(CustomScriptManager.java:248) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager.reloadImpl(CustomScriptManager.java:182) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager.reload(CustomScriptManager.java:152) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager.reloadTimerEvent(CustomScriptManager.java:128) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.reloadTimerEvent(Unknown Source) ~[oxcore-script-4.5.4.Final.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor218.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124) ~[jakarta.enterprise.cdi-api-2.0.2.jar:?]
	at org.jboss.weld.util.Observers.notify(Observers.java:166) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:159) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:632) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.util.ForwardingBeanManager.fireEvent(ForwardingBeanManager.java:104) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.gluu.service.timer.TimerJob.execute(TimerJob.java:37) ~[oxcore-timer-weld-4.5.4.Final.jar:?]
	at org.gluu.service.timer.JobExecutionDelegate.execute(JobExecutionDelegate.java:31) ~[oxcore-timer-weld-4.5.4.Final.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.2.jar:?]
2024-04-25 08:08:34,276 ERROR [oxAuthScheduler_Worker-4] [org.gluu.service.custom.script.CustomScriptManager] (CustomScriptManager.java:352) - Failed to destroy custom script 'B8FD-4C11' correctly
2024-04-25 08:08:34,354 ERROR [oxAuthScheduler_Worker-4] [org.gluu.service.PythonService] (PythonService.java:186) - Failed to load python file
org.python.core.PyException: ImportError: No module named notnoop
	at org.python.core.Py.ImportError(Py.java:327) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.import_logic(imp.java:1292) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.import_module_level(imp.java:1371) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.importName(imp.java:1544) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyObject.__call__(PyObject.java:433) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.__builtin__.__import__(__builtin__.java:1232) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.importFromAs(imp.java:1636) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.importFrom(imp.java:1611) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at gluu_common$py.f$0(/opt/gluu/python/libs/gluu_common.py:819) ~[?:?]
	at gluu_common$py.call_function(/opt/gluu/python/libs/gluu_common.py) ~[?:?]
	at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyCode.call(PyCode.java:18) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.createFromCode(imp.java:632) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.createFromPyClass(imp.java:314) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.createFromPyClass(imp.java:257) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.loadFromSource(imp.java:931) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.find_module(imp.java:771) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.import_next(imp.java:1160) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.import_module_level(imp.java:1352) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.importName(imp.java:1544) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyObject.__call__(PyObject.java:433) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.__builtin__.__import__(__builtin__.java:1232) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.importFromAs(imp.java:1636) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.imp.importFrom(imp.java:1611) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.pycode._pyx11.f$0(super_gluu_ro.py:23) ~[?:?]
	at org.python.pycode._pyx11.call_function(super_gluu_ro.py) ~[?:?]
	at org.python.core.PyTableCode.call(PyTableCode.java:173) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.PyCode.call(PyCode.java:18) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.core.Py.runCode(Py.java:1742) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:297) ~[jython-standalone-2.7.3.jar:2.7.4a1-SNAPSHOT]
	at org.gluu.service.PythonService.loadPythonScript(PythonService.java:184) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.PythonService$Proxy$_$$_WeldClientProxy.loadPythonScript(Unknown Source) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager.createExternalTypeFromStringWithPythonException(CustomScriptManager.java:417) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.createExternalTypeFromStringWithPythonException(Unknown Source) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager.createExternalType(CustomScriptManager.java:385) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager.reloadCustomScriptConfigurations(CustomScriptManager.java:293) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager.reloadImpl(CustomScriptManager.java:182) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager.reload(CustomScriptManager.java:152) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager.reloadTimerEvent(CustomScriptManager.java:128) ~[oxcore-script-4.5.4.Final.jar:?]
	at org.gluu.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.reloadTimerEvent(Unknown Source) ~[oxcore-script-4.5.4.Final.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor218.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124) ~[jakarta.enterprise.cdi-api-2.0.2.jar:?]
	at org.jboss.weld.util.Observers.notify(Observers.java:166) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:159) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:632) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.jboss.weld.util.ForwardingBeanManager.fireEvent(ForwardingBeanManager.java:104) ~[weld-core-impl-3.1.9.Final.jar:3.1.9.Final]
	at org.gluu.service.timer.TimerJob.execute(TimerJob.java:37) ~[oxcore-timer-weld-4.5.4.Final.jar:?]
	at org.gluu.service.timer.JobExecutionDelegate.execute(JobExecutionDelegate.java:31) ~[oxcore-timer-weld-4.5.4.Final.jar:?]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) ~[quartz-2.3.2.jar:?]
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) ~[quartz-2.3.2.jar:?]
2024-04-25 08:08:34,359 ERROR [oxAuthScheduler_Worker-4] [org.gluu.service.custom.script.CustomScriptManager] (CustomScriptManager.java:387) - Failed to prepare external type 'org.gluu.exception.PythonException: Failed to load python file 'java.io.ByteArrayInputStream@79614c23''
2024-04-25 08:08:34,372 INFO  [oxAuthScheduler_Worker-4] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - Casa client registration. Destroy
2024-04-25 08:08:34,372 INFO  [oxAuthScheduler_Worker-4] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - Casa client registration. Destroyed successfully
2024-04-25 08:08:34,396 INFO  [oxAuthScheduler_Worker-4] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - Casa client registration. Initialization
2024-04-25 08:08:34,397 INFO  [oxAuthScheduler_Worker-4] [org.gluu.service.PythonService$PythonLoggerOutputStream] (PythonService.java:243) - Casa client registration. Initialized successfully
    ```

**Comment by shekhar16** [comment]
@MohitMaliFtechiz  closing this ticket.
