### ISSUE TITLE
CR failing to connect backend server which has SSL enabled

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#242]
Environment: 

OS: RHEL 7
Gluu Server: 
 - oxTrust: 2.4.3.Final / Implementation-Build: 21258
 - oxAuth: 2.4.3.Final / Implementation-Build: e4580d2ee307f7718a98643d6b4ce03e7fa58005

Situation: 

- I can ldapsearch backend with -Z -X 
- CR is throwing SocketException: Connection reset
- Backend cert, Backend trust certs are already imported in Gluu Server java keystore ( cacerts )

Stack trace: 

1. Ldapsearch working: 

```
[ldap@idp-dev ~]$ /opt/opendj/bin/ldapsearch -h company.com -p 636 -Z -X -D "cn=someone,dc=somewhere,dc=somecompany" -j /tmp/.adpw -b 'dc=somewhere,dc=somecompany' --simplePageSize=999 -z 5 'objectclass=*'
dn: dc=somewhere,dc=somecompany
objectClass: top
objectClass: domain
objectClass: domainDNS

```

2. oxtrust_cache_refresh.log showing: 

```
2016-05-04 03:22:47,200 ERROR [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (pool-4-thread-2) Failed to connect to LDAP server using configuration source
2016-05-04 03:22:47,222 ERROR [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (pool-4-thread-2) Skipping cache refresh due to invalid server configuration

```

3. oxtrust_persistence.log showing: 

```
2016-05-04 03:22:47,200 ERROR [org.gluu.site.ldap.LDAPConnectionProvider] (pool-4-thread-2) Failed to create connection pool with properties: {binaryAttributes=objectGUID, maxconnections=5, bindDN=cn=someone,dc=somewhere,dc=somecompany, useSSL=true, bindPassword=xxxxxx, servers=company.com:636}
LDAPException(resultCode=81 (server down), errorMessage='An error occurred while attempting to send the LDAP message to server company.com:636:  java.net.SocketException: Connection reset', diagnosticMessage='An error occurred while attempting to send the LDAP message to server company:636:  java.net.SocketException: Connection reset')
        at com.unboundid.ldap.sdk.LDAPConnectionPool.createConnection(LDAPConnectionPool.java:1288)
        at com.unboundid.ldap.sdk.LDAPConnectionPool.createConnection(LDAPConnectionPool.java:1177)
        at com.unboundid.ldap.sdk.LDAPConnectionPool.<init>(LDAPConnectionPool.java:1114)
        at com.unboundid.ldap.sdk.LDAPConnectionPool.<init>(LDAPConnectionPool.java:996)
        at com.unboundid.ldap.sdk.LDAPConnectionPool.<init>(LDAPConnectionPool.java:933)
        at com.unboundid.ldap.sdk.LDAPConnectionPool.<init>(LDAPConnectionPool.java:876)
        at com.unboundid.ldap.sdk.LDAPConnectionPool.<init>(LDAPConnectionPool.java:791)
        at org.gluu.site.ldap.LDAPConnectionProvider.init(LDAPConnectionProvider.java:113)
        at org.gluu.site.ldap.LDAPConnectionProvider.<init>(LDAPConnectionProvider.java:59)
        at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.prepareLdapServerConnection(CacheRefreshTimer.java:1052)
        at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.prepareLdapServerConnection(CacheRefreshTimer.java:1040)
        at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.prepareLdapServerConnections(CacheRefreshTimer.java:1030)
        at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.processImpl(CacheRefreshTimer.java:247)
        at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer.process(CacheRefreshTimer.java:178)
        at sun.reflect.GeneratedMethodAccessor492.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
        at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
        at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.async.AsynchronousInterceptor.aroundInvoke(AsynchronousInterceptor.java:52)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
        at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196)
        at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114)
        at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer_$$_javassist_seam_33.process(CacheRefreshTimer_$$_javassist_seam_33.java)
        at sun.reflect.GeneratedMethodAccessor491.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
        at org.jboss.seam.util.Reflections.invokeAndWrap(Reflections.java:144)
        at org.jboss.seam.Component.callComponentMethod(Component.java:2313)
        at org.jboss.seam.core.Events.raiseEvent(Events.java:85)
        at org.jboss.seam.async.AsynchronousEvent$1.process(AsynchronousEvent.java:33)
        at org.jboss.seam.async.Asynchronous$ContextualAsynchronousRequest.run(Asynchronous.java:80)
        at org.jboss.seam.async.AsynchronousEvent.execute(AsynchronousEvent.java:27)
        at org.jboss.seam.async.ThreadPoolDispatcher$RunnableAsynchronous.run(ThreadPoolDispatcher.java:142)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by mzico** [comment]
@yurem @nynymike : 'http://ox.gluu.org/maven/org/xdi/oxtrust-server/2.4.3.Final/oxtrust-server-2.4.3.Final.war' resolved the issue.

**Comment by mzico** [comment]
[5/4/2016 2:37:29 PM] Yuriy Movchan: It will try to create connection pool using next protocols
[5/4/2016 2:37:31 PM] Yuriy Movchan:  private static final String[] SSL_PROTOCOLS = { "TLSv1.2", "TLSv1.1", "TLSv1", "SSLv3" };
