### ISSUE TITLE
Asimba's keystore cert expiration monitoring

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxTrust#248]
Ryan Kinzy: so how do you know if it expires?  it just stops working and you look at the log files?
Dmitry Ogn: Yes. It shoud broke with a SSL exception.
Ryan Kinzy: ok - but then you'd be scrambling to get it back up - so it would be good to have an alert
Ryan Kinzy: once we get this up - you'll have 3 months to get it done!
Ryan Kinzy: because you'd have to generate it and send it to the partner right?  and then when their cert is about to expire you'd have to request one from them
Dmitry Ogn: I think it's good idea, we should add this.

**Comment by dmogn** [comment]
Good keystore manipulation Java app (can be used as reference):
https://github.com/kaikramer/keystore-explorer/tree/master/kse/src/net/sf/keystore_explorer/crypto

**Comment by dmogn** [comment]
Done for Asimba keystore.

TODO: Shib and httpd certs.

**Comment by dmogn** [comment]
Done.

**Comment by dmogn** [comment]
It works for all certificates: httpd, openDJ, shdib IDP,  Asimba's keystore, trust certificates in oxTrust.
One point for check all.

**Comment by dmogn** [comment]
Exception with uninstalled Asimba:
2016-06-13 01:51:06,586 INFO  [org.gluu.oxtrust.action.CertificateManagementAction] refresh() CertificateManagement call
2016-06-13 01:51:06,589 ERROR [org.gluu.oxtrust.action.CertificateManagementAction] Load Asimba keystore configuration exception
java.lang.NullPointerException
        at java.security.Provider$ServiceKey.<init>(Provider.java:517)
        at java.security.Provider$ServiceKey.<init>(Provider.java:510)
        at java.security.Provider.getService(Provider.java:684)
        at sun.security.jca.ProviderList.getService(ProviderList.java:331)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:157)
        at java.security.Security.getImpl(Security.java:695)
        at java.security.KeyStore.getInstance(KeyStore.java:625)
        at org.gluu.oxtrust.util.KeystoreWrapper.<init>(KeystoreWrapper.java:40)
        at org.gluu.oxtrust.service.asimba.AsimbaXMLConfigurationService.getKeystore(AsimbaXMLConfigurationService.java:174)

**Comment by dmogn** [comment]
Done.
