### ISSUE TITLE
Fix method which parses LDAP schema

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#26]
2015-01-22 09:11:29,187 DEBUG [org.gluu.oxtrust.servlet.FaviconImageServlet] Successfully send organization favicon with size
2015-01-22 09:11:29,385 WARN  [org.jboss.seam.ui.renderkit.DefaultActionRendererBase] Must set an id for the default action source
2015-01-22 09:11:29,414 WARN  [org.jboss.seam.ui.renderkit.DefaultActionRendererBase] Must set an id for the default action source
2015-01-22 09:11:30,476 ERROR [org.gluu.oxtrust.action.UpdateTrustRelationshipAction] Failed to get OID for attribute name email_verified
2015-01-22 09:11:31,059 ERROR [org.gluu.oxtrust.action.UpdateTrustRelationshipAction] Failed to get OID for attribute name updated_at
2015-01-22 09:11:31,236 ERROR [org.gluu.oxtrust.action.UpdateTrustRelationshipAction] Failed to get OID for attribute name middle_name
2015-01-22 09:11:31,667 ERROR [org.gluu.oxtrust.action.UpdateTrustRelationshipAction] Failed to get OID for attribute name phone_number_verified
2015-01-22 09:11:31,917 ERROR [org.gluu.oxtrust.action.UpdateTrustRelationshipAction] Failed to get OID for attribute name preferred_username
2015-01-22 09:11:32,195 ERROR [org.xdi.service.SchemaService] Failed to get attribute type definition by string ( zoneinfo-oid NAME ( 'zoneinfo' 'timezone' ) DESC 'time zone database representing the End-User's time zone. For example, Europe/Paris or America/Los_Angeles' SUBSTR caseIgnoreSubstringsMatch EQUALITY caseIgnoreMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 X-ORIGIN 'OpenID Connect 1.0 Standard Claim' )
LDAPException(resultCode=84 (decoding error), errorMessage='Unable to parse string '( zoneinfo-oid NAME ( 'zoneinfo' 'timezone' ) DESC 'time zone database representing the End-User's time zone. For example, Europe/Paris or America/Los_Angeles' SUBSTR caseIgnoreSubstringsMatch EQUALITY caseIgnoreMatch SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 X-ORIGIN 'OpenID Connect 1.0 Standard Claim' )' as a schema element because the end of the string was reached without finding an expected space after a closing single quote.')
    at com.unboundid.ldap.sdk.schema.SchemaElement.readQDString(SchemaElement.java:342)
    at com.unboundid.ldap.sdk.schema.AttributeTypeDefinition.<init>(AttributeTypeDefinition.java:222)
    at org.xdi.service.SchemaService.getAttributeTypeDefinitions(SchemaService.java:308)
    at sun.reflect.GeneratedMethodAccessor408.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)

**Comment by willow9886** [comment]
@yurem is this still outstanding?

**Comment by yurem** [comment]
yes, this issue still exists. But we can move it to 2.4.3 milestone.

**Comment by aliaksander-samuseu** [comment]
@yurem, has it been fixed? How can I test for it?

**Comment by yurem** [comment]
Probably yes. In 2.4.3 I updated UnboundID SDK. Also in 2.4.3 we use OpenDJ 3.0.0

Can you do next in order if ther is no this issue now:
1) Open attributes list.
2) Open 'zoneinfo' attribute
3) Create dummy inactive TR with 'zoneinfo' attribute/
4) Check oxtrust.log/wrapper.log
5) Close issue if there is no error in the logs

**Comment by nynymike** [comment]
Schema service has been removed. This issue should be resolved.
