### ISSUE TITLE
Failed to remove Asimba requestor from file system

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxTrust#332]
oxTrust GUI allows to add/remove Asimba requestors. But during requestor removal it don't remove SP metadata file from file system. This can led to requestors leak.

**Comment by nynymike** [comment]
@dmogn Status?

**Comment by yurem** [comment]
In 3.0.0 we don't do war files explode under jetty. As result Gluu Asimba can't use exploded war folder to store these files. QA @zamilskhan with @mzico help  should verify if Asimba works fine in CE 3.0.0

**Comment by dmogn** [comment]
@yurem - Yes, I should change default directory and retest it.

**Comment by dmogn** [comment]
Done.

**Comment by dmogn** [comment]
with latest DEB:

2017-01-13 04:59:29,730 WARN  [qtp425918570-18] [org.jboss.seam.util.Resources] (Resources.java:168) - Unable to determine real path from servlet context for "/WEB-INF/dev" path does not exist.
2017-01-13 04:59:29,956 ERROR [qtp425918570-18] [org.jboss.seam.exception.Exceptions] (Exceptions.java:86) - handled and logged exception
javax.servlet.ServletException: couldn't parse request parts
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:606) ~[jsf-api-2.1.28.jar:2.1]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) ~[?:?]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1712) ~[?:?]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:83) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:63) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]

Caused by: org.richfaces.exception.FileUploadException: couldn't parse request parts
        at org.richfaces.renderkit.FileUploadRendererBase.initializeUploadedFiles(FileUploadRendererBase.java:112) ~[richfaces-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.renderkit.FileUploadRendererBase.doDecode(FileUploadRendererBase.java:152) ~[richfaces-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.renderkit.RendererBase.decode(RendererBase.java:81) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at javax.faces.component.UIComponentBase.decode(UIComponentBase.java:789) ~[jsf-api-2.1.28.jar:2.1]
        at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1183) ~[jsf-api-2.1.28.jar:2.1]
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:534) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]


Caused by: java.lang.IllegalStateException: No multipart config for servlet
        at org.eclipse.jetty.server.Request.getParts(Request.java:2309) ~[jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at org.eclipse.jetty.server.Request.getParts(Request.java:2296) ~[jetty-server-9.3.14.v20161028.jar:9.3.14.v20161028]
        at javax.servlet.http.HttpServletRequestWrapper.getParts(HttpServletRequestWrapper.java:375) ~[servlet-api-3.1.jar:3.1.0]
        at org.richfaces.renderkit.FileUploadRendererBase.initializeUploadedFiles(FileUploadRendererBase.java:84) ~[richfaces-4.5.17.Final.jar:4.5.17.Final]
2017-01-13 04:59:30,237 WARN  [qtp425918570-11] [org.jboss.seam.util.Resources] (Resources.java:168) - Unable to determine real path from servlet context for "/WEB-INF/dev" path does not exist.

**Comment by yurem** [comment]
Latest stack trace related to another issue caused by specific versions conflict: jetty/richfaces/faces/Seam.
New deb/rpm contains new Jetty. I think we resolved it.

**Comment by dmogn** [comment]
Thanks, @yurem!
