### ISSUE TITLE
Add Asimba IDP - add certificate exception

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxTrust#341]
gluu-server 2.4.4; Ubuntu 14.04_64

2016-09-02 15:07:17,384 WARN  [org.gluu.oxtrust.service.asimba.AsimbaXMLConfigurationService] Certificate parsing exception
java.lang.ClassCastException: org.bouncycastle.cert.X509CertificateHolder cannot be cast to java.security.cert.X509Certificate
        at org.gluu.oxtrust.ldap.service.SSLService.getPEMCertificateStatic(SSLService.java:116)
        at org.gluu.oxtrust.ldap.service.SSLService.getPEMCertificate(SSLService.java:89)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

This code has been tested, maybe there is other type of cert or BC version...
I'll fix this case.

**Comment by dmogn** [comment]
Has been fixed in 2.4.4
TODO: check in 3.0.0

**Comment by dmogn** [comment]
Yeah, the patch has been losted. Fixing...

**Comment by dmogn** [comment]
Fixed.

**Comment by dmogn** [comment]
Hm... In 2.4.4.SP3 it has been lost too... Fixed.
