### ISSUE TITLE
Would it possible providing the antlr g4 file for SCIM2 filter

### ISSUE THREAD

**Issue by vfahrenheit** [GluuFederation/oxTrust#359]
It seems  that an error will occur while use Number/Boolean value in filter:   emails[primary eq true] or (someCount eq 2)

exception stack;
Exception in thread "main" org.antlr.v4.runtime.NoViableAltException
	at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:1884)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATNWithFullContext(ParserATNSimulator.java:694)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:524)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:412)
	at org.antlr.v4.runtime.atn.ProfilingATNSimulator.adaptivePredict(ProfilingATNSimulator.java:86)
	at org.gluu.oxtrust.service.antlr.scimFilter.antlr4.ScimFilterParser.criteria(ScimFilterParser.java:909)
	at org.gluu.oxtrust.service.antlr.scimFilter.antlr4.ScimFilterParser.expression(ScimFilterParser.java:584)
	at org.gluu.oxtrust.service.antlr.scimFilter.antlr4.ScimFilterParser.expression(ScimFilterParser.java:658)
	at org.gluu.oxtrust.service.antlr.scimFilter.antlr4.ScimFilterParser.expression(ScimFilterParser.java:741)
	at org.gluu.oxtrust.service.antlr.scimFilter.antlr4.ScimFilterParser.scimFilter(ScimFilterParser.java:131)

**Comment by uboznikov** [comment]
`emails[primary eq "true"]`

**Comment by vfahrenheit** [comment]
thank uboznikov.    
and It's possible to provide the ANTLR g4 file?   I didn't find it the source repository

**Comment by uboznikov** [comment]
Please see https://github.com/GluuFederation/antlr-scim-filter
