### ISSUE TITLE
v3.0.0 oxTrust startup error: wrong schema

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxTrust#390]
gluu-server-3.0.0_16-ALPHA1~trusty+Ub14.04_amd64.deb (Ubuntu 14.04 64)

No errors in setup.log

2016-11-14 01:22:55.600:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@3bfdc050{/identity,[file:///opt/jetty-9.3/temp/jetty-0.0.0.0-8082-identity.war-_identity-any-93952601825142845.dir/webapp/, jar:file:///opt/jetty-9.3/temp/jetty-0.0.0.0-8082-identity.war-_identity-any-93952601825142845.dir/webapp/WEB-INF/lib/jboss-seam-debug-2.3.1.Final.jar!/META-INF/resources, jar:file:///opt/jetty-9.3/temp/jetty-0.0.0.0-8082-identity.war-_identity-any-93952601825142845.dir/webapp/WEB-INF/lib/oxtrust-static-3.0.0-SNAPSHOT.jar!/META-INF/resources, jar:file:///opt/jetty-9.3/temp/jetty-0.0.0.0-8082-identity.war-_identity-any-93952601825142845.dir/webapp/WEB-INF/lib/richfaces-core-impl-4.3.7.Final.jar!/META-INF/resources, jar:file:///opt/jetty-9.3/temp/jetty-0.0.0.0-8082-identity.war-_identity-any-93952601825142845.dir/webapp/WEB-INF/lib/jsf-impl-2.1.28-jbossorg-1.jar!/META-INF/resources, jar:file:///opt/jetty-9.3/temp/jetty-0.0.0.0-8082-identity.war-_identity-any-93952601825142845.dir/webapp/WEB-INF/lib/richfaces-components-ui-4.3.7.Final.jar!/META-INF/resources],UNAVAILABLE}{/identity.war}
org.jboss.seam.InstantiationException: Could not instantiate Seam component: appInitializer
        at org.jboss.seam.Component.newInstance(Component.java:2208)
        at org.jboss.seam.contexts.Contexts.startup(Contexts.java:343)
        at org.jboss.seam.contexts.Contexts.startup(Contexts.java:335)
        at org.jboss.seam.contexts.Contexts.startup(Contexts.java:317)
        at org.jboss.seam.contexts.ServletLifecycle.endInitialization(ServletLifecycle.java:143)
        at org.jboss.seam.init.Initialization.init(Initialization.java:813)
        at org.jboss.seam.servlet.SeamListener.contextInitialized(SeamListener.java:36)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:843)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:816)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345)
        at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778)
        at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.bindings.StandardStarter.processBinding(StandardStarter.java:41)
        at org.eclipse.jetty.deploy.AppLifeCycle.runBindings(AppLifeCycle.java:188)
        at org.eclipse.jetty.deploy.DeploymentManager.requestAppGoal(DeploymentManager.java:499)
        at org.eclipse.jetty.deploy.DeploymentManager.addApp(DeploymentManager.java:147)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.fileAdded(ScanningAppProvider.java:180)
        at org.eclipse.jetty.deploy.providers.WebAppProvider.fileAdded(WebAppProvider.java:452)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider$1.fileAdded(ScanningAppProvider.java:64)
        at org.eclipse.jetty.util.Scanner.reportAddition(Scanner.java:610)
        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:529)
        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:392)
        at org.eclipse.jetty.util.Scanner.doStart(Scanner.java:313)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.providers.ScanningAppProvider.doStart(ScanningAppProvider.java:150)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.deploy.DeploymentManager.startAppProvider(DeploymentManager.java:561)
        at org.eclipse.jetty.deploy.DeploymentManager.doStart(DeploymentManager.java:236)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
        at org.eclipse.jetty.server.Server.start(Server.java:411)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
        at org.eclipse.jetty.server.Server.doStart(Server.java:378)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1516)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1441)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:214)
        at org.eclipse.jetty.start.Main.start(Main.java:457)
        at org.eclipse.jetty.start.Main.main(Main.java:75)
Caused by:
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to find entry: cn=schema
        at org.gluu.site.ldap.persistence.LdapEntryManager.find(LdapEntryManager.java:242)
        at org.gluu.site.ldap.persistence.AbstractEntryManager.find(AbstractEntryManager.java:417)
        at org.gluu.site.ldap.persistence.AbstractEntryManager.find(AbstractEntryManager.java:366)
        at org.gluu.site.ldap.persistence.AbstractEntryManager.find(AbstractEntryManager.java:355)
        at org.xdi.service.SchemaService.getSchema(SchemaService.java:58)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
        at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
        at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
        at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
        at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196)
        at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114)
        at org.xdi.service.SchemaService_$$_javassist_seam_26.getSchema(SchemaService_$$_javassist_seam_26.java)
        at org.gluu.oxtrust.ldap.service.Shibboleth3ConfService.initAttributeParamMap(Shibboleth3ConfService.java:427)
        at org.gluu.oxtrust.ldap.service.Shibboleth3ConfService.generateConfigurationFiles(Shibboleth3ConfService.java:170)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by yurem** [comment]
Fixed: https://github.com/GluuFederation/oxCore/commit/800a5129b12bfeaf527a219b8db528c95704e565
