### ISSUE TITLE
CR is not working Gluu3.0.0.

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#396]
CacheRefresh is not working in Gluu 3.0.0, While setting bind DN password from UI, get following error in CR logs, 
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: unencrypted string was null or empty
        at org.xdi.util.security.StringEncrypter.encrypt(StringEncrypter.java:268)
        at org.xdi.util.security.StringEncrypter.encrypt(StringEncrypter.java:323)

**Comment by yurem** [comment]
I will take  a loo on this before we will build 3.0.0.Beta2

**Comment by yurem** [comment]
Fixed password dialog
