### ISSUE TITLE
Cache Referesh throwing error

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#413]
When trying to import users using cache refresh from opendj, the following error is shown in the `oxtrust_cache_refresh.log` . The testing was done in CentOS release 6.6 (Final) with gluu-server-3.0.0.x86_64 24-ALPHA1.centos6 @Gluu-rpm-centos-testing-repo.

```
2016-12-13 18:45:33,319 TRACE [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (pool-1-thread-7) Checking source entry with key: 'CacheCompoundKey [primaryKeyValues=[
user.329], secondaryKeyValues=null, tertiaryKeyValues=null]', and DN: uid=user.329,ou=People,o=gluu
2016-12-13 18:45:33,499 ERROR [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (pool-1-thread-7) Exception happened while executing cache refresh synchronization
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to persist entry: inum=@!411D.CFEB.5D66.7C86!0001!F7B2.576C!0000!FED7.1A12,o=site
        at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:106)
        at org.gluu.site.ldap.persistence.AbstractEntryManager.persist(AbstractEntryManager.java:90)
        at org.gluu.oxtrust.ldap.cache.service.CacheRefreshService.addInumMap(CacheRefreshService.java:118)
        at sun.reflect.GeneratedMethodAccessor512.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
 at org.gluu.oxtrust.ldap.cache.service.CacheRefreshTimer_$$_javassist_seam_32.process(CacheRefreshTimer_$$_javassist_seam_32.java)
        at sun.reflect.GeneratedMethodAccessor426.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: Connection exception (LDAP config error: insufficient access rights.: no write access to parent)
        at org.gluu.site.ldap.OperationsFacade.addEntry(OperationsFacade.java:395)
        at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:101)
        ... 59 more
```

**Comment by sahiliamsso** [comment]
Under "Cache Refresh" > Inum LDAP Server , If you update o=gluu then this error is fixed but you start getting below error. 

Caused by: Connection exception (LDAP config error: schema violation contact LDAP admin.: invalid structural object class chain (inetOrgPerson/gluuPerson))
        at org.gluu.site.ldap.OperationsFacade.addEntry(OperationsFacade.java:401)
        at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:101)
        ... 60 more
2016-12-17 05:53:25,179 ERROR [gluu.oxtrust.ldap.cache.service.CacheRefreshTimer] (pool-2-thread-4) Failed to 'add' person '@!0FF5.3804.DD31.5857!0001!28A3.CD43!0000!E57E.63F9'
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to persist entry: inum=@!0FF5.3804.DD31.5857!0001!28A3.CD43!0000!E57E.63F9,ou=people,o=@!0FF5.3804.DD31.5857!0001!28A3.CD43,o=gluu

**Comment by yurem** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/e269845d1cfc65f3e828fedc5ea31351959aa2a3

**Comment by sahiliamsso** [comment]
- Verified CR is working fine in 8-BETA1~trusty+Ub14.04
- External authentication is also working fine.

But getting this error in logs and no CR Snapshots are being saved.

```
2016-12-28 01:16:18,884 ERROR [gluu.oxtrust.ldap.cache.service.CacheRefreshSnapshotFileService] (pool-3-thread-3) Failed to create snapshot file '/var/ox/identity/cr-snapshots/inum-snapshot-2016-12-28-01-16.txt'
java.io.FileNotFoundException: /var/ox/identity/cr-snapshots/inum-snapshot-2016-12-28-01-16.txt (Permission denied)
```

**Comment by sahiliamsso** [comment]
Changing the ownership of folder /var/ox/identity/cr-snapshots to jetty:jetty gets this issue fixed.

**Comment by yurem** [comment]
I updated setup to set right permissions: https://github.com/GluuFederation/community-edition-setup/commit/d159467d6f95246fc24941da129b48182d6311e2
Now this folder ha permissions 775 and user:group - root:gluu
Into gluu group belongs 3 users: jetty, node, ldap
