### ISSUE TITLE
Unable to remove client

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#439]
OS: **CentOS 6.6 (Final)**
Package: **gluu-server-3.0.0.x86_64 6-BETA2.centos6**

The added OpenID Clients cannot be deleted showing the message **_Cannot remove Client_** with the following in the `oxTrust.log` file.
```
2017-01-11 08:22:56,381 ERROR [qtp425918570-18] [org.gluu.oxtrust.action.UpdateClientAction] (UpdateClientAction.java:261) - Failed to remove client @!6571.E442.3A02.037
8!0001!05A7.AE77!0008!CA79.B496.3659.9E6E
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to remove entry: inum=@!6571.E442.3A02.0378!0001!05A7.AE77!0008!CA79.B496.3659.9E6E,ou=clients
,o=@!6571.E442.3A02.0378!0001!05A7.AE77,o=gluu
        at org.gluu.site.ldap.persistence.LdapEntryManager.removeWithSubtree(LdapEntryManager.java:224) ~[oxLdap-3.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxtrust.ldap.service.ClientService.removeClient(ClientService.java:78) ~[classes/:?]

 at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: org.gluu.site.ldap.exception.ConnectionException: Connection exception (Failed to delete entry: subordinate objects must be deleted first)
```

The `oxauth.log` file shows the following error.
```
ERROR [qtp425918570-15] [org.gluu.oxtrust.action.UpdateClientAction] (UpdateClientAction.java:261) - Failed to remove client @!6571.E442.3A02.037
8!0001!05A7.AE77!0008!CA79.B496.3659.9E6E
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to remove entry: inum=@!6571.E442.3A02.0378!0001!05A7.AE77!0008!CA79.B496.3659.9E6E,ou=clients
,o=@!6571.E442.3A02.0378!0001!05A7.AE77,o=gluu
        at org.gluu.site.ldap.persistence.LdapEntryManager.removeWithSubtree(LdapEntryManager.java:224) ~[oxLdap-3.0.0-SNAPSHOT.jar:?]

at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: org.gluu.site.ldap.exception.ConnectionException: Connection exception (Failed to delete entry: subordinate objects must be deleted first)
        at org.gluu.site.ldap.OperationsFacade.deleteWithSubtree(OperationsFacade.java:596) ~[oxLdap-3.0.0-SNAPSHOT.jar:?]
```

**Comment by yurem** [comment]
Fixed: https://github.com/GluuFederation/oxCore/commit/4977abe2f09b8952c611fa64eae88c7d72cab2f1
New build should contains this fix
