### ISSUE TITLE
Error Adding group in oxtrust

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#448]
Steps to reproduce:
1. Login to oxtrust
2. Click on Users > Manage Groups > Add Group
3. Provide required information, click on Add Member and select user
4. Click Add

Expected Result: We should get "Group creation successful" message
Actual Result: Error message "Failed to Add group"

PS: We get error message but group is created successfully though.

**Logs**
2017-01-20 06:05:46,316 DEBUG [qtp425918570-15] [org.gluu.oxtrust.action.UpdateGroupAction] (UpdateGroupAction.java:322) - Old members: [DisplayNameEntry [displayName=Test, inum=@!495F.F2BE.310E.8C33!0001!756E.14E2!0000!2B7C.363A.9BD5.7B07, toString()=Entry [dn=inum=@!495F.F2BE.310E.8C33!0001!756E.14E2!0000!2B7C.363A.9BD5.7B07,ou=people,o=@!495F.F2BE.310E.8C33!0001!756E.14E2,o=gluu]]]
2017-01-20 06:05:46,316 DEBUG [qtp425918570-15] [org.gluu.oxtrust.action.UpdateGroupAction] (UpdateGroupAction.java:323) - New members: [DisplayNameEntry [displayName=Test, inum=@!495F.F2BE.310E.8C33!0001!756E.14E2!0000!2B7C.363A.9BD5.7B07, toString()=Entry [dn=inum=@!495F.F2BE.310E.8C33!0001!756E.14E2!0000!2B7C.363A.9BD5.7B07,ou=people,o=@!495F.F2BE.310E.8C33!0001!756E.14E2,o=gluu]]]
2017-01-20 06:05:46,317 DEBUG [qtp425918570-15] [org.gluu.oxtrust.action.UpdateGroupAction] (UpdateGroupAction.java:403) - Updating group inum=@!495F.F2BE.310E.8C33!0001!756E.14E2!0003!ED9D.9AE5,ou=groups,o=@!495F.F2BE.310E.8C33!0001!756E.14E2,o=gluu to person Test memberOf
2017-01-20 06:05:46,322 INFO  [qtp425918570-15] [org.gluu.oxtrust.action.UpdateGroupAction] (UpdateGroupAction.java:173) - error updating group
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to update entry: inum=@!495F.F2BE.310E.8C33!0001!756E.14E2!0000!2B7C.363A.9BD5.7B07,ou=people,o=@!495F.F2BE.310E.8C33!0001!756E.14E2,o=gluu
        at org.gluu.site.ldap.persistence.LdapEntryManager.merge(LdapEntryManager.java:182) ~[oxLdap-3.0.0-SNAPSHOT.jar:?]
        at org.gluu.site.ldap.persistence.AbstractEntryManager.merge(AbstractEntryManager.java:268) ~[oxLdap-3.0.0-SNAPSHOT.jar:?]
        at org.gluu.site.ldap.persistence.AbstractEntryManager.merge(AbstractEntryManager.java:283) ~[oxLdap-3.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxtrust.ldap.service.PersonService.updatePerson(PersonService.java:116) ~[classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]

**Gluu Version: ** gluu-server-3.0.0 (2-BETA3~trusty+Ub14.04)
**Platform:** Ubuntu 14.04

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/22342212/94d1dbc8-e419-11e6-8620-f6f2b065ba54.png)

**Comment by shekhar16** [comment]
I tested this in latest version i.e gluu-server-3.0.0_3-BETA4-trusty+Ub14.04_amd64.deb
and found it is working fine.
I m closing this issue ,please test it again and let me know if you found any issues in Add Group functionality.
