### ISSUE TITLE
Error changing default authn method

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#449]
I set the default authn method for oxTrust to U2F. The config was properly saved, but the oxTrust GUI reported an error.  I saw this message in the log, which leads me to think that there was something wrong because I hadn't configured passport yet.  It was an incorrect and confusing error notification.

![image](https://cloud.githubusercontent.com/assets/3717101/22168299/6d5305dc-df31-11e6-861d-2d3b59194c5c.png)

```
2017-01-20 19:55:17,373 ERROR [qtp425918570-17] [org.gluu.oxtrust.action.ManagePersonAuthenticationAction] (ManagePersonAuthenticationAction.java:194) - Failed to update appliance configuration
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to persist entry: ou=oxpassport,ou=configuration,inum=@!E25E.32AB.D050.5420!0002!96CF.D593,ou=appliances,o=gluu
        at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:96) ~[oxLdap-3.0.0-SNAPSHOT.jar:?]
        at org.gluu.site.ldap.persistence.AbstractEntryManager.persist(AbstractEntryManager.java:90) ~[oxLdap-3.0.0-SNAPSHOT.jar:?]
        at org.gluu.oxtrust.ldap.service.PassportService.updateLdapOxPassportConfiguration(PassportService.java:80) ~[classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.gluu.oxtrust.ldap.service.PassportService_$$_javassist_seam_47.updateLdapOxPassportConfiguration(PassportService_$$_javassist_seam_47.java) ~[classes/:?]
        at org.gluu.oxtrust.action.ManagePersonAuthenticationAction.save(ManagePersonAuthenticationAction.java:192) [classes/:?]
```

**Comment by yurem** [comment]
Fixed

**Comment by mzico** [comment]
@zamilskhan : Can you QA this?
