### ISSUE TITLE
Cache Refresh page throws error

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxTrust#453]
The Cache Refresh page doesn't even come up for me...

![image](https://cloud.githubusercontent.com/assets/3717101/22189557/dbbdea3e-e0e2-11e6-9d7b-d23c2b75d6ae.png)

```
SEVERE: Error Rendering View[/organization/cacheRefresh.xhtml]
javax.el.PropertyNotFoundException: //opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1969810757127842908.dir/webapp/WEB-INF/incl/organization/cacheRefreshForm.xhtml @74,111 value="#{_configureCacheRefreshAction.appliance.vdsCacheRefreshLastUpdateDate}": Property 'vdsCacheRefreshLastUpdateDate' not found on type org.gluu.oxtrust.model.GluuAppliance
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:111)
	at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194)
	at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:182)
	at javax.faces.component.UIOutput.getValue(UIOutput.java:170)
	at com.sun.faces.renderkit.html_basic.HtmlBasicInputRenderer.getValue(HtmlBasicInputRenderer.java:205)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.getCurrentValue(HtmlBasicRenderer.java:355)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeEnd(HtmlBasicRenderer.java:164)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:877)
	at org.jboss.seam.ui.util.cdk.RendererBase.renderChild(RendererBase.java:190)
	at org.jboss.seam.ui.util.cdk.RendererBase.renderChildren(RendererBase.java:166)
	at org.jboss.seam.ui.renderkit.ValidateAllRendererBase.doEncodeChildren(ValidateAllRendererBase.java:35)
	at org.jboss.seam.ui.util.cdk.RendererBase.encodeChildren(RendererBase.java:92)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:847)
	at org.jboss.seam.ui.util.cdk.RendererBase.renderChild(RendererBase.java:186)
	at org.jboss.seam.ui.util.cdk.RendererBase.renderChildren(RendererBase.java:166)
	at org.jboss.seam.ui.renderkit.DecorateRendererBase.doEncodeChildren(DecorateRendererBase.java:170)
	at org.jboss.seam.ui.util.cdk.RendererBase.encodeChildren(RendererBase.java:92)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:847)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304)
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:105)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:847)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1819)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:168)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:847)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1819)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1822)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1822)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:447)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:125)
	at org.jboss.seam.jsf.SeamViewHandler.renderView(SeamViewHandler.java:188)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:286)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:139)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:594)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74)
	at org.jboss.seam.web.RewriteFilter.process(RewriteFilter.java:98)
	at org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:57)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	at org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	at org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
	at org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
	at org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	at org.jboss.seam.servlet.SeamFilter.doFilter(SeamFilter.java:158)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1751)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)

2017-01-23 02:40:05,562 ERROR [qtp425918570-19] [org.jboss.seam.exception.Exceptions] (Exceptions.java:86) - handled and logged exception
javax.servlet.ServletException: //opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1969810757127842908.dir/webapp/WEB-INF/incl/organization/cacheRefreshForm.xhtml @74,111 value="#{_configureCacheRefreshAction.appliance.vdsCacheRefreshLastUpdateDate}": Property 'vdsCacheRefreshLastUpdateDate' not found on type org.gluu.oxtrust.model.GluuAppliance
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:606) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[?:?]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) ~[?:?]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) ~[?:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[?:?]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199) ~[?:?]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74) ~[?:?]
	at org.jboss.seam.web.RewriteFilter.process(RewriteFilter.java:98) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:57) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter.doFilter(SeamFilter.java:158) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1751) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.Server.handle(Server.java:534) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: javax.el.PropertyNotFoundException: //opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1969810757127842908.dir/webapp/WEB-INF/incl/organization/cacheRefreshForm.xhtml @74,111 value="#{_configureCacheRefreshAction.appliance.vdsCacheRefreshLastUpdateDate}": Property 'vdsCacheRefreshLastUpdateDate' not found on type org.gluu.oxtrust.model.GluuAppliance
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:111) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
	at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:182) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
	at javax.faces.component.UIOutput.getValue(UIOutput.java:170) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
	at com.sun.faces.renderkit.html_basic.HtmlBasicInputRenderer.getValue(HtmlBasicInputRenderer.java:205) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.getCurrentValue(HtmlBasicRenderer.java:355) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeEnd(HtmlBasicRenderer.java:164) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:877) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
	at org.jboss.seam.ui.util.cdk.RendererBase.renderChild(RendererBase.java:190) ~[jboss-seam-ui-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.ui.util.cdk.RendererBase.renderChildren(RendererBase.java:166) ~[jboss-seam-ui-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.ui.renderkit.ValidateAllRendererBase.doEncodeChildren(ValidateAllRendererBase.java:35) ~[jboss-seam-ui-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.ui.util.cdk.RendererBase.encodeChildren(RendererBase.java:92) ~[jboss-seam-ui-2.3.1.Final.jar:2.3.1.Final]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:847) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
	at org.jboss.seam.ui.util.cdk.RendererBase.renderChild(RendererBase.java:186) ~[jboss-seam-ui-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.ui.util.cdk.RendererBase.renderChildren(RendererBase.java:166) ~[jboss-seam-ui-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.ui.renderkit.DecorateRendererBase.doEncodeChildren(DecorateRendererBase.java:170) ~[jboss-seam-ui-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.ui.util.cdk.RendererBase.encodeChildren(RendererBase.java:92) ~[jboss-seam-ui-2.3.1.Final.jar:2.3.1.Final]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:847) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:105) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:847) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1819) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:168) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:847) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1819) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1822) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1822) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:447) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:125) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at org.jboss.seam.jsf.SeamViewHandler.renderView(SeamViewHandler.java:188) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:286) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:139) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:594) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
	... 51 more
2017-01-23 02:40:05,589 INFO  [qtp425918570-19] [org.gluu.oxtrust.ldap.service.OrganizationService] (OrganizationService.java:258) - Starting App version 3.0.0-SNAPSHOT

```

**Comment by dmogn** [comment]
2017-01-23 21:35:38,966 ERROR [qtp425918570-20] [org.jboss.seam.exception.Exceptions] (Exceptions.java:86) - handled and logged exception
javax.servlet.ServletException: //opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-1657062042042827326.dir/webapp/WEB-INF/incl/organization/cacheRefreshForm.xhtml @74,111 value="#{_configureCacheRefreshAction.appliance.vdsCacheRefreshLastUpdateDate}": **Property 'vdsCacheRefreshLastUpdateDate' not found on type org.gluu.oxtrust.model.GluuAppliance**
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:606) ~[jsf-api-2.1.28.jar:2.1]

**Comment by dmogn** [comment]
Fixed.
