### ISSUE TITLE
Passport Exception on change passport support field

### ISSUE THREAD

**Issue by shekhar16** [GluuFederation/oxTrust#462]
`2017-01-26 13:46:19,738 ERROR [qtp502572999-56] [org.jboss.seam.exception.Exceptions] (Exceptions.java:86) - handled and logged exception
javax.servlet.ServletException: /WEB-INF/incl/authentication/customAuthenticationForm.xhtml @120,204 value="#{_ldapPassport}": /WEB-INF/incl/authentication/customAuthenticationForm.xhtml @102,88 value="#{_action.ldapPassportConfigurations}": The class 'org.gluu.oxtrust.action.ManagePersonAuthenticationAction_$$_javassist_seam_57' does not have the property 'ldapPassportConfigurations'.
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:606) ~[jsf-api-2.1.28.jar:2.1]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[?:?]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:595) ~[?:?]`

**Comment by shekhar16** [comment]
fixed.
