### ISSUE TITLE
User Registration page redirects to home 

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxTrust#471]
OS: Ubuntu 14.04.2
Package: gluu-server-3.0.0 2-BETA5~trusty+Ub14.04
oxTrust Version:
```
 GLUU.root@ubuntu:~# cat /opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-3490586617116349045.dir/webapp/META-INF/MANIFEST.MF      
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 3.0.0-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: tomcat
Implementation-Build: 3b892
Implementation-Vendor-Id: org.xdi
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9
```
User registration custom script was enabled from the custom script page and the user registration page was accessed via `<hostname>/identity/register`. Upon trying to enter the username, the home page appeared with the following error. Please see [this video](https://youtu.be/d36QvrJYn5I) for clarification.

The following appeared in the `oxtrust.log`
```
2017-02-01 20:58:41,579 ERROR [qtp425918570-15] [org.jboss.seam.exception.Exceptions] (Exceptions.java:86) - handled and logged exception
javax.servlet.ServletException: //opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-3490586617116349045.dir/webapp/register.xhtml @93
,204 value="#{((empty _custAttr) or (empty _custAttr.metadata) or (empty _custAttr.metadata.regExp))?'.*':_custAttr.metadata.regExp}": Property 'regEx
p' not found on type org.xdi.model.GluuAttribute
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:606) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) ~[?:?]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584) ~[?:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[?:?]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) ~[?:?]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) ~[?:?]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) ~[?:?]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) ~[?:?]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) ~[?:?]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) ~[?:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[?:?]
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199) ~[?:?]
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74) ~[?:?]
        at org.jboss.seam.web.RewriteFilter.process(RewriteFilter.java:98) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:57) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.servlet.SeamFilter.doFilter(SeamFilter.java:158) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1751) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v2016122
0]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213) [jetty-server-9.3.15.v20161220.jar:9.3.
15.v20161220]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.Server.handle(Server.java:534) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220
]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.15.v2016
1220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.15.v20161220.ja
r:9.3.15.v20161220]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.15.v20161220.jar:9.3.15.v2
0161220]
      at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: javax.el.PropertyNotFoundException: //opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-3490586617116349045.dir/webapp/reg
ister.xhtml @93,204 value="#{((empty _custAttr) or (empty _custAttr.metadata) or (empty _custAttr.metadata.regExp))?'.*':_custAttr.metadata.regExp}": 
Property 'regExp' not found on type org.xdi.model.GluuAttribute
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:111) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
        at javax.faces.component.UIComponentBase$AttributesMap.get(UIComponentBase.java:2364) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at org.gluu.oxtrust.util.jsf.ExtendedRegexValidator.validate(ExtendedRegexValidator.java:20) ~[classes/:?]
        at javax.faces.component.UIInput.validateValue(UIInput.java:1153) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at javax.faces.component.UIInput.validate(UIInput.java:971) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at javax.faces.component.UIInput.executeValidate(UIInput.java:1237) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at javax.faces.component.UIInput.processValidators(UIInput.java:702) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:536) ~[jsf-impl-2.1.28-jbossorg-1.ja
r:?]
        at org.richfaces.context.MetaComponentProcessingVisitCallback.visit(MetaComponentProcessingVisitCallback.java:73) ~[richfaces-core-4.5.17.Fina
l.jar:4.5.17.Final]
        at org.richfaces.context.BaseExtendedVisitContext.invokeVisitCallback(BaseExtendedVisitContext.java:103) ~[richfaces-core-4.5.17.Final.jar:4.5
.17.Final]
        at org.richfaces.context.ExtendedExecuteVisitContext.invokeVisitCallback(ExtendedExecuteVisitContext.java:55) ~[richfaces-core-4.5.17.Final.ja
r:4.5.17.Final]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1652) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1663) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1663) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1663) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at org.richfaces.component.UIDataAdaptor$DataVisitorForVisitTree.process(UIDataAdaptor.java:207) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final
]
        at org.ajax4jsf.model.SequenceDataModel.walk(SequenceDataModel.java:66) ~[richfaces-core-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.component.UIDataAdaptor.walk(UIDataAdaptor.java:817) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.component.UIDataAdaptor.visitDataChildren(UIDataAdaptor.java:1290) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.component.UIDataAdaptor.visitTree(UIDataAdaptor.java:1368) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1663) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1663) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at javax.faces.component.UIForm.visitTree(UIForm.java:371) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1663) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1663) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:383) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:257) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
        at org.richfaces.context.ExtendedPartialViewContext.processPartial(ExtendedPartialViewContext.java:264) ~[richfaces-core-4.5.17.Final.jar:4.5.
17.Final]
at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1162) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:76) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593) ~[jboss-jsf-api_2.1_spec-2.1.28.Final.jar:2.1.28.Final]
        ... 51 more
2017-02-01 20:58:43,410 DEBUG [pool-2-thread-3] [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] (MetadataValidationTimer.java:87) - Starting m
etadata validation
2017-02-01 20:58:43,411 TRACE [pool-2-thread-3] [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] (MetadataValidationTimer.java:119) - Starting 
metadata validation process.
```

**Comment by zamilskhan** [comment]
@shekhar16 this issue is there in the RC1 package. In this package the user registration page does not appear at all.

**Comment by yurem** [comment]
There is typo in path to property value. I fixed it but not tested.

**Comment by yurem** [comment]
@zamilskhan can you retest on this war: https://ox.gluu.org/maven/org/xdi/oxtrust-server/3.0.0-SNAPSHOT/oxtrust-server-3.0.0-SNAPSHOT.war

**Comment by zamilskhan** [comment]
Redirection does not happen anymore. Tested oxTrust version
```
GLUU.root@ubuntu:~# cat /opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-3116257539850615010.dir/webapp/META-INF/MANIFEST.MF 
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 3.0.0-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: tomcat
Implementation-Build: 6bea6
Implementation-Vendor-Id: org.xdi
Build-Jdk: 1.7.0_79
Created-By: Apache Maven 3.3.9
```
