### ISSUE TITLE
SAML TR add error

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxTrust#505]
Related with metadata example from https://support.gluu.org/single-sign-on/3875/issue-with-meta-tag-when-adding-a-tr/
Adding metadata as file.
Log:
2017-03-13 18:29:30,460 INFO  [qtp274064559-17] [org.gluu.oxtrust.ldap.service.OrganizationService] (OrganizationService.java:258) - Starting App version 3.0.1
2017-03-13 18:29:39,664 WARN  [qtp274064559-12] [org.jboss.seam.ui.renderkit.DefaultActionRendererBase] (DefaultActionRendererBase.java:54) - Must set an id for the default action source
2017-03-13 18:29:39,677 WARN  [qtp274064559-12] [org.jboss.seam.ui.renderkit.DefaultActionRendererBase] (DefaultActionRendererBase.java:54) - Must set an id for the default action source
^[[B^[[B^[[B^[[B^[[B^[[B2017-03-13 18:40:41,990 INFO  [qtp274064559-11] [org.gluu.oxtrust.ldap.service.TrustService] (TrustService.java:81) - Creating TR @!E34F.89CE.7FD0.FD3B!0002!C252.E4C6!0006!BD7B.FC9A
2017-03-13 18:40:42,039 ERROR [qtp274064559-11] [org.gluu.oxtrust.ldap.service.Shibboleth3ConfService] (Shibboleth3ConfService.java:935) - Failed to read metadata file '/opt/shibboleth-idp/metadata/E34F89CE7FD0FD3B0002C252E4C60006BD7BFC9A-sp-metadata.xml'
java.io.FileNotFoundException: File '/opt/shibboleth-idp/metadata/E34F89CE7FD0FD3B0002C252E4C60006BD7BFC9A-sp-metadata.xml' does not exist
        at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299) ~[commons-io-2.4.jar:2.4]
        at org.gluu.oxtrust.ldap.service.Shibboleth3ConfService.isFederationMetadata(Shibboleth3ConfService.java:926) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
        at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]     
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]       
        at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107) [jboss-seam-2.3.1.Final.jar:2.3.1.Final] 
        at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]     
        at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]     
        at org.gluu.oxtrust.ldap.service.Shibboleth3ConfService_$$_javassist_seam_11.isFederationMetadata(Shibboleth3ConfService_$$_javassist_seam_11.java) [classes/:?]                                                                                                       
        at org.gluu.oxtrust.ldap.service.TrustService.isFederation(TrustService.java:404) [classes/:?]                                          
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]                                  
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]                                 
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]                                    
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]                                    
        at org.jboss.seam.util.Reflections.invoke(Reflections.java:22) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]       
        at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]     
        at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]

**Comment by willow9886** [comment]
@dmogn since the user mentioned that this was a result of an error on their side, curious about what resolution you plan on adding?

> Apparently, it was a problem on our side with blocking/inspection of SSL traffic. Since we have allowed this traffic, all validations are successful.

**Comment by dmogn** [comment]
@willow9886 
Yeah, but I got other error with same metadata in 3.0.1.

**Comment by willow9886** [comment]
got it. thanks for clarification.

**Comment by dmogn** [comment]
I found a race condition here. UI calls save(); create second thread for metadata downloading and process metadata for isFederal() checking in first thread. But metdata isn't downloaded yet...

**Comment by dmogn** [comment]
I found same exception (TR adding) in oxTrust 2.4.4.sp3:

2017-03-27 03:14:00,721 INFO  [org.gluu.oxtrust.ldap.service.OrganizationService] Starting App version 2.4.4.sp3
2017-03-27 03:39:26,092 WARN  [org.jboss.seam.ui.renderkit.DefaultActionRendererBase] Must set an id for the default action source
2017-03-27 03:39:26,125 WARN  [org.jboss.seam.ui.renderkit.DefaultActionRendererBase] Must set an id for the default action source
2017-03-27 03:41:34,014 INFO  [org.gluu.oxtrust.ldap.service.TrustService] Creating TR @!E8B8.E7E8.F4F9.2D12!0002!A44B.0698!0006!AEA3.4EE7
2017-03-27 03:41:34,094 ERROR [org.gluu.oxtrust.ldap.service.Shibboleth2ConfService] Failed to read metadata file '/opt/idp/metadata/E8B8E7E8F4F92D120002A44B06980006AEA34EE7-sp-metadata.xml'
java.io.FileNotFoundException: File '/opt/idp/metadata/E8B8E7E8F4F92D120002A44B06980006AEA34EE7-sp-metadata.xml' does not exist
        at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
        at org.gluu.oxtrust.ldap.service.Shibboleth2ConfService.isFederationMetadata(Shibboleth2ConfService.java:820)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

- File /opt/idp/metadata/E8B8E7E8F4F92D120002A44B06980006AEA34EE7-sp-metadata.xml really is exist in gluu-server.

**Comment by dmogn** [comment]
Same issue with #490
