### ISSUE TITLE
reset password link not working.

### ISSUE THREAD

**Issue by shekhar16** [GluuFederation/oxTrust#554]
Throwing below exception.

2017-05-14 13:21:00,075 DEBUG [pool-2-thread-10] [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] (MetadataValidationTimer.java:92) - Metadata validation finished with result: 'false'
May 14, 2017 1:21:13 PM com.sun.faces.facelets.tag.jsf.core.ViewHandler apply
WARNING: Using en_US for locale because expression /WEB-INF/incl/layout/newtemplate.xhtml @12,58 locale="#{language.localeCode}" returned null.
May 14, 2017 1:21:22 PM com.sun.faces.application.view.FaceletViewHandlingStrategy handleRenderException
SEVERE: Error Rendering View[/resetPassword.xhtml]
javax.el.ELException: /WEB-INF/incl/layout/topmenu.xhtml: java.lang.NullPointerException
	at com.sun.faces.facelets.compiler.TextInstruction.write(TextInstruction.java:88)
	at com.sun.faces.facelets.compiler.UIInstructions.encodeBegin(UIInstructions.java:82)
	at com.sun.faces.facelets.compiler.UILeaf.encodeAll(UILeaf.java:207)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:168)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:847)
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304)
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:105)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:847)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1819)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1822)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1822)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:447)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:125)
	at org.jboss.seam.jsf.SeamViewHandler.renderView(SeamViewHandler.java:188)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:286)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:139)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:594)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74)
	at org.jboss.seam.web.RewriteFilter.process(RewriteFilter.java:98)
	at org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:57)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	at org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	at org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
	at org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
	at org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
	at org.jboss.seam.servlet.SeamFilter.doFilter(SeamFilter.java:158)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:201)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.gluu.oxtrust.util.jsf.JsfFunctions.getPersonDisplayName(JsfFunctions.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.el.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:335)
	at org.jboss.el.parser.AstFunction.getValue(AstFunction.java:84)
	at org.jboss.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:186)
	at com.sun.faces.facelets.el.ELText$ELTextVariable.writeText(ELText.java:227)
	at com.sun.faces.facelets.el.ELText$ELTextComposite.writeText(ELText.java:150)
	at com.sun.faces.facelets.compiler.TextInstruction.write(TextInstruction.java:85)
	... 71 more

2017-05-14 13:21:22,955 ERROR [qtp1394336709-268] [org.jboss.seam.exception.Exceptions] (Exceptions.java:86) - handled and logged exception
javax.servlet.ServletException: null
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:606) ~[jsf-api-2.1.28.jar:2.1]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[?:?]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) ~[?:?]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) ~[?:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) ~[?:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) ~[?:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[?:?]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199) ~[?:?]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74) ~[?:?]
	at org.jboss.seam.web.RewriteFilter.process(RewriteFilter.java:98) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:57) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.jboss.seam.servlet.SeamFilter.doFilter(SeamFilter.java:158) [jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668) [jetty-servlet-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581) [jetty-servlet-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [jetty-servlet-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.server.Server.handle(Server.java:524) [jetty-server-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [jetty-server-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [jetty-server-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:201) [jetty-io-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [jetty-io-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.10.v20160621.jar:9.3.10.v20160621]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.10.v20160621.jar:9.3.10.v20160621]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at org.gluu.oxtrust.util.jsf.JsfFunctions.getPersonDisplayName(JsfFunctions.java:112) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at org.jboss.el.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:335) ~[jboss-el-1.0_02.CR6.jar:1.0_02.CR6]
	at org.jboss.el.parser.AstFunction.getValue(AstFunction.java:84) ~[jboss-el-1.0_02.CR6.jar:1.0_02.CR6]
	at org.jboss.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:186) ~[jboss-el-1.0_02.CR6.jar:1.0_02.CR6]
	at com.sun.faces.facelets.el.ELText$ELTextVariable.writeText(ELText.java:227) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at com.sun.faces.facelets.el.ELText$ELTextComposite.writeText(ELText.java:150) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at com.sun.faces.facelets.compiler.TextInstruction.write(TextInstruction.java:85) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at com.sun.faces.facelets.compiler.UIInstructions.encodeBegin(UIInstructions.java:82) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at com.sun.faces.facelets.compiler.UILeaf.encodeAll(UILeaf.java:207) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:168) ~[jsf-api-2.1.28.jar:2.1]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:847) ~[jsf-api-2.1.28.jar:2.1]
	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:105) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:847) ~[jsf-api-2.1.28.jar:2.1]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1819) ~[jsf-api-2.1.28.jar:2.1]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1822) ~[jsf-api-2.1.28.jar:2.1]
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1822) ~[jsf-api-2.1.28.jar:2.1]
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:447) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:125) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at org.jboss.seam.jsf.SeamViewHandler.renderView(SeamViewHandler.java:188) ~[jboss-seam-2.3.1.Final.jar:2.3.1.Final]
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:286) ~[jsf-api-2.1.28.jar:2.1]
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:139) ~[jsf-impl-2.1.28-jbossorg-1.jar:?]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:594) ~[jsf-api-2.1.28.jar:2.1]
	... 53 more
2017-05-14 13:21:24,378 WARN  [qtp1394336709-268] [org.jboss.seam.util.Resources] (Resources.java:168) - Unable to determine real path from servlet context for "/WEB-INF/classes" path does not exist.
2017-05-14 13:21:24,659 WARN  [qtp1394336709-268] [org.jboss.seam.util.Resources] (Resources.java:168) - Unable to determine real path from servlet context for "/WEB-INF/lib" path does not exist.
2017-05-14 13:21:24,940 WARN  [qtp1394336709-268] [org.jboss.seam.util.Resources] (Resources.java:168) - Unable to determine real path from servlet context for "/WEB-INF/dev" path does not exist.
2017-05-14 13:21:34,635 DEBUG [pool-2-thread-1] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:137) - Starting update of appliance status
2017-05-14 13:21:38,606 DEBUG [pool-2-thread-1] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:339) - Setting facter attributes
2017-05-14 13:21:38,622 DEBUG [pool-2-thread-1] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:406) - Setting df attributes
2017-05-14 13:21:38,638 DEBUG [pool-2-thread-1] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:219) - Setting httpd attributes
2017-05-14 13:21:41,772 DEBUG [pool-2-thread-1] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:195) - Appliance status update finished
2017-05-14 13:22:03,005 DEBUG [pool-2-thread-10] [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] (MetadataValidationTimer.java:87) - Starting metadata validation
2017-05-14 13:22:03,084 DEBUG [pool-2-thread-10] [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] (MetadataValidationTimer.java:92) - Metadata validation finished with result: 'false'
2017-05-14 13:22:34,609 DEBUG [pool-2-thread-1] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:137) - Starting update of appliance status
2017-05-14 13:22:38,563 DEBUG [pool-2-thread-1] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:339) - Setting facter attributes
2017-05-14 13:22:38,579 DEBUG [pool-2-thread-1] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:406) - Setting df attributes
2017-05-14 13:22:38,595 DEBUG [pool-2-thread-1] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:219) - Setting httpd attributes
2017-05-14 13:22:41,725 DEBUG [pool-2-thread-1] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:195) - Appliance status update finished
2017-05-14 13:23:06,001 DEBUG [pool-2-thread-2] [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] (MetadataValidationTimer.java:87) - Starting metadata validation
2017-05-14 13:23:06,065 DEBUG [pool-2-thread-2] [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] (MetadataValidationTimer.java:92) - Metadata validation finished with result: 'false'
2017-05-14 13:23:34,629 DEBUG [pool-2-thread-6] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:137) - Starting update of appliance status
2017-05-14 13:23:38,556 DEBUG [pool-2-thread-6] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:339) - Setting facter attributes
2017-05-14 13:23:38,573 DEBUG [pool-2-thread-6] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:406) - Setting df attributes
2017-05-14 13:23:38,588 DEBUG [pool-2-thread-6] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:219) - Setting httpd attributes
2017-05-14 13:23:41,652 DEBUG [pool-2-thread-6] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:195) - Appliance status update finished
2017-05-14 13:24:09,013 DEBUG [pool-2-thread-8] [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] (MetadataValidationTimer.java:87) - Starting metadata validation
2017-05-14 13:24:09,092 DEBUG [pool-2-thread-8] [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] (MetadataValidationTimer.java:92) - Metadata validation finished with result: 'false'
2017-05-14 13:24:34,645 DEBUG [pool-2-thread-6] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:137) - Starting update of appliance status
2017-05-14 13:24:38,583 DEBUG [pool-2-thread-6] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:339) - Setting facter attributes
2017-05-14 13:24:38,616 DEBUG [pool-2-thread-6] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:406) - Setting df attributes
2017-05-14 13:24:38,631 DEBUG [pool-2-thread-6] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:219) - Setting httpd attributes
2017-05-14 13:24:41,913 DEBUG [pool-2-thread-6] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:195) - Appliance status update finished
2017-05-14 13:25:12,010 DEBUG [pool-2-thread-8] [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] (MetadataValidationTimer.java:87) - Starting metadata validation
2017-05-14 13:25:12,073 DEBUG [pool-2-thread-8] [org.gluu.oxtrust.ldap.service.MetadataValidationTimer] (MetadataValidationTimer.java:92) - Metadata validation finished with result: 'false'

**Comment by shekhar16** [comment]
It was seam -> weld migration issue.And it is fixed.
the reason for this issue was org.gluu.oxtrust.util.jsf.JsfFunctions.getPersonDisplayName(JsfFunctions.java:112) null pointer .

But still need to test it with latest code.But as currently weld migrated code is in working not condition so couldn't able to test it properly. 
presently facing issue :
jsf externalContext.redirect java.lang.illegalstateexception committed

**Comment by shekhar16** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/15937500/27506503-c99674fe-58d6-11e7-9eea-b7f18377d48a.png)

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/issues/585
