### ISSUE TITLE
Register page is not working.

### ISSUE THREAD

**Issue by shekhar16** [GluuFederation/oxTrust#599]
http://localhost:8490/identity/register.

logs : 

2017-06-27 19:52:35,658 DEBUG [oxTrustScheduler_Worker-2] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:222) - Setting httpd attributes
2017-06-27 19:52:35,746 DEBUG [oxTrustScheduler_Worker-2] [org.gluu.oxtrust.ldap.service.StatusCheckerTimer] (StatusCheckerTimer.java:198) - Appliance status update finished
2017-06-27 19:52:55,104 INFO  [qtp331844619-491] [org.gluu.oxtrust.exception.GlobalExceptionHandler] (GlobalExceptionHandler.java:44) - global Excetion WELD-000054: Producers cannot produce unserializable instances for injection into an injection point that requires a passivation capable dependency
  Producer:  Producer Method [ExternalContext] with qualifiers [@Any @Default] declared as [[UnbackedAnnotatedMethod] @Produces @Dependent public org.gluu.jsf2.service.FacesResources.getExternalContext()]
	at org.gluu.jsf2.service.FacesResources.getExternalContext(FacesResources.java:24)
  Injection Point:  [UnbackedAnnotatedField] @Inject private org.gluu.oxtrust.action.RegisterPersonAction.externalContext
	at org.gluu.oxtrust.action.RegisterPersonAction.externalContext(RegisterPersonAction.java:0)
  StackTrace:
javax.faces.FacesException: WELD-000054: Producers cannot produce unserializable instances for injection into an injection point that requires a passivation capable dependency
  Producer:  Producer Method [ExternalContext] with qualifiers [@Any @Default] declared as [[UnbackedAnnotatedMethod] @Produces @Dependent public org.gluu.jsf2.service.FacesResources.getExternalContext()]
	at org.gluu.jsf2.service.FacesResources.getExternalContext(FacesResources.java:24)
  Injection Point:  [UnbackedAnnotatedField] @Inject private org.gluu.oxtrust.action.RegisterPersonAction.externalContext
	at org.gluu.oxtrust.action.RegisterPersonAction.externalContext(RegisterPersonAction.java:0)
  StackTrace:
	at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:86)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:848)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
	at org.jboss.weld.probe.ProbeFilter$FilterAction.proceed(ProbeFilter.java:329)
	at org.jboss.weld.probe.ProbeFilter$FilterAction.proceed(ProbeFilter.java:312)
	at org.jboss.weld.probe.InvocationMonitor$Action.perform(InvocationMonitor.java:173)
	at org.jboss.weld.probe.ProbeFilter$FilterAction.doFilter(ProbeFilter.java:338)
	at org.jboss.weld.probe.ProbeFilter.embedInfoSnippet(ProbeFilter.java:188)
	at org.jboss.weld.probe.ProbeFilter.doFilter(ProbeFilter.java:176)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1751)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199)
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74)
	at org.ocpsoft.rewrite.servlet.impl.HttpRewriteResultHandler.handleResult(HttpRewriteResultHandler.java:42)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.rewrite(RewriteFilter.java:297)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:198)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:534)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.weld.exceptions.IllegalProductException: WELD-000054: Producers cannot produce unserializable instances for injection into an injection point that requires a passivation capable dependency
  Producer:  Producer Method [ExternalContext] with qualifiers [@Any @Default] declared as [[UnbackedAnnotatedMethod] @Produces @Dependent public org.gluu.jsf2.service.FacesResources.getExternalContext()]
	at org.gluu.jsf2.service.FacesResources.getExternalContext(FacesResources.java:24)
  Injection Point:  [UnbackedAnnotatedField] @Inject private org.gluu.oxtrust.action.RegisterPersonAction.externalContext
	at org.gluu.oxtrust.action.RegisterPersonAction.externalContext(RegisterPersonAction.java:0)
  StackTrace:
	at org.jboss.weld.bean.AbstractProducerBean.checkReturnValue(AbstractProducerBean.java:155)
	at org.jboss.weld.bean.AbstractProducerBean.create(AbstractProducerBean.java:181)
	at org.jboss.weld.contexts.unbound.DependentContextImpl.get(DependentContextImpl.java:70)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:676)
	at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:776)
	at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)
	at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:335)
	at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:346)
	at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:69)
	at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)
	at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:71)
	at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:117)
	at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:159)
	at org.jboss.weld.util.bean.IsolatedForwardingBean.create(IsolatedForwardingBean.java:45)
	at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
	at org.jboss.weld.contexts.PassivatingContextWrapper$AbstractPassivatingContextWrapper.get(PassivatingContextWrapper.java:76)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.get(ContextualInstanceStrategy.java:177)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:676)
	at org.jboss.weld.module.web.el.AbstractWeldELResolver.lookup(AbstractWeldELResolver.java:107)
	at org.jboss.weld.module.web.el.AbstractWeldELResolver.getValue(AbstractWeldELResolver.java:90)
	at org.jboss.weld.environment.servlet.util.ForwardingELResolver.getValue(ForwardingELResolver.java:49)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:63)
	at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176)
	at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203)
	at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:94)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:137)
	at org.apache.el.parser.AstEqual.getValue(AstEqual.java:37)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184)
	at org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109)
	at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194)
	at javax.faces.component.UIViewAction.isRendered(UIViewAction.java:448)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1211)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1222)
	at javax.faces.component.UIComponentBase.processDecodes(UIComponentBase.java:1222)
	at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:929)
	at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:78)
	... 51 more
2017-06-27 19:53:11,461 DEBUG [qtp331844619-508] [org.gluu.oxtrust.servlet.LogoImageServlet] (LogoImageServlet.java:53) - Starting organization logo upload
2017-06-27 19:53:11,614 DEBUG [qtp331844619-508] [org.gluu.oxtrust.servlet.LogoImageServlet] (LogoImageServlet.java:108) - Successfully send organization logo with size

**Comment by shekhar16** [comment]
@rajnikantsh is it working with latest code?Because its not working for me..

**Comment by rajnikantsh** [comment]
@shekhar16 following is the PR is opened for this issue this is still not merged. Please have a review on this https://github.com/GluuFederation/oxTrust/pull/623/commits/0b2fb882f7dd90ea24a3e62c54ec3a5d5afd36e3

**Comment by yurem** [comment]
Fixed
