### ISSUE TITLE
<ox:decorate> exception while rendering UI

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxTrust#610]
ERROR [qtp274064559-12] [org.gluu.oxtrust.exception.GlobalExceptionHandler] (GlobalExceptionHandler.java:50) - argument type mismatch
java.lang.IllegalArgumentException: argument type mismatch
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at javax.faces.component.UIComponentBase$AttributesMap.put(UIComponentBase.java:2464) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponentBase$AttributesMap.put(UIComponentBase.java:2336) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.facelets.tag.jsf.CompositeComponentTagHandler$CompositeComponentRule$LiteralAttributeMetadata.applyMetadata(CompositeComponentTagHandler.java:591) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.tag.MetadataImpl.applyMetadata(MetadataImpl.java:81) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.view.facelets.MetaTagHandler.setAttributes(MetaTagHandler.java:129) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.view.facelets.DelegatingMetaTagHandler.setAttributes(DelegatingMetaTagHandler.java:102) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.facelets.tag.jsf.CompositeComponentTagHandler.setAttributes(CompositeComponentTagHandler.java:245) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.tag.jsf.CompositeComponentTagHandler.applyNextHandler(CompositeComponentTagHandler.java:181) ~[jsf-impl-2.2.14.jar:2.2.14]
        at org.richfaces.view.facelets.html.BehaviorsAddingComponentHandlerWrapper.applyNextHandler(BehaviorsAddingComponentHandlerWrapper.java:53) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137) ~[jsf-api-2.2.14.jar:2.2]
        at org.richfaces.view.facelets.html.BehaviorsAddingComponentHandlerWrapper.applyNextHandler(BehaviorsAddingComponentHandlerWrapper.java:53) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137) ~[jsf-api-2.2.14.jar:2.2]
        at org.richfaces.view.facelets.html.BehaviorsAddingComponentHandlerWrapper.applyNextHandler(BehaviorsAddingComponentHandlerWrapper.java:53) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.facelets.tag.ui.CompositionHandler.apply(CompositionHandler.java:194) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:93) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:87) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:312) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:371) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:350) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.impl.DefaultFaceletContext.includeFacelet(DefaultFaceletContext.java:199) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.tag.ui.DecorateHandler.apply(DecorateHandler.java:153) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.facelets.tag.ui.DefineHandler.applyDefinition(DefineHandler.java:106) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.tag.ui.CompositionHandler.apply(CompositionHandler.java:206) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.impl.DefaultFaceletContext$TemplateManager.apply(DefaultFaceletContext.java:395) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.impl.DefaultFaceletContext.includeDefinition(DefaultFaceletContext.java:366) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.tag.ui.InsertHandler.apply(InsertHandler.java:111) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137) ~[jsf-api-2.2.14.jar:2.2]
        at org.richfaces.view.facelets.html.BehaviorsAddingComponentHandlerWrapper.applyNextHandler(BehaviorsAddingComponentHandlerWrapper.java:53) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.facelets.tag.jsf.core.ViewHandler.apply(ViewHandler.java:225) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:93) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:93) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:87) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:312) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:371) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:350) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.impl.DefaultFaceletContext.includeFacelet(DefaultFaceletContext.java:199) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.tag.ui.CompositionHandler.apply(CompositionHandler.java:174) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:93) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:87) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.facelets.impl.DefaultFacelet.apply(DefaultFacelet.java:161) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.application.view.FaceletViewHandlingStrategy.buildView(FaceletViewHandlingStrategy.java:1006) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:99) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219) [jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659) [jsf-api-2.2.14.jar:2.2]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.jboss.weld.probe.ProbeFilter$FilterAction.proceed(ProbeFilter.java:329) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.ProbeFilter$FilterAction.proceed(ProbeFilter.java:312) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.InvocationMonitor$Action.perform(InvocationMonitor.java:173) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.ProbeFilter$FilterAction.doFilter(ProbeFilter.java:338) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.ProbeFilter.embedInfoSnippet(ProbeFilter.java:188) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.probe.ProbeFilter.doFilter(ProbeFilter.java:176) [weld-probe-core-3.0.0.Final.jar:3.0.0.Final]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1751) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) [jetty-security-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.ocpsoft.rewrite.servlet.impl.HttpRewriteResultHandler.handleResult(HttpRewriteResultHandler.java:42) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
        at org.ocpsoft.rewrite.servlet.RewriteFilter.rewrite(RewriteFilter.java:297) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:198) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.Server.handle(Server.java:534) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

Maybe it's JAR versions conflict? <ox:decorate> removing only fix it.

**Comment by yurem** [comment]
Where do you get it? In all other places it works fine. Here is random [example](https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/webapp/group/groupInventory.xhtml#L51).

**Comment by dmogn** [comment]
@yurem 
https://ce.gluu.info/identity/asimba/editIDP
https://ce.gluu.info/identity/asimba/editSPRequestor.htm

https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/webapp/WEB-INF/incl/asimba/idpForm.xhtml#L69

All works fine after I've removed all <ox:decorate> from these pages.

**Comment by dmogn** [comment]
I did not find any difference from other pages with <ox:decorate>

**Comment by yurem** [comment]
Fixed editIdp.xhtml
