### ISSUE TITLE
SMTP trust issues

### ISSUE THREAD

**Issue by bluebaroncanada** [GluuFederation/oxTrust#627]
I am experiencing a severe issue with SMTP setup.  I try to connect and there's a generic `Failed to connect to SMTP server.`  Very helpful.
So I checked out the project and wrote a small Main function like so:

```
import org.gluu.oxtrust.util.MailUtils;

public class Main {

	public static void main(String[] args) {
		MailUtils mailUtils = new MailUtils("*****", 587, true, true, "******", "******");
		try {
		mailUtils.sendMail("*****", "*******", "You are electric", "You are electric?");
		}
		catch(Exception e)
		{
			System.out.println(e.getMessage());
		}
	}
}
```
The error that I got is:
```
2017-07-27 18:23:48,590 DEBUG [main] [org.gluu.oxtrust.util.MailUtils] (MailUtils.java:65) - HostName: ****** Port: 587 ConnectionTimeOut: 5000
2017-07-27 18:23:48,594 DEBUG [main] [org.gluu.oxtrust.util.MailUtils] (MailUtils.java:66) - UserName: ******* Password: *******
[ERROR] 
javax.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1907)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:666)
	at javax.mail.Service.connect(Service.java:317)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at org.gluu.oxtrust.util.MailUtils.sendMail(MailUtils.java:104)
	at Main.main(Main.java:9)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:549)
	at com.sun.mail.util.SocketFetcher.startTLS(SocketFetcher.java:486)
	at com.sun.mail.smtp.SMTPTransport.startTLS(SMTPTransport.java:1902)
	... 8 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 19 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
	at java.security.cert.CertPathBuilder.build(Unknown Source)
	... 25 more
```
That led me to: https://stackoverflow.com/questions/16115453/javamail-could-not-convert-socket-to-tls-gmail

and indeed, if I add `props.put("mail.smtp.ssl.trust", this.hostName);` to line 75 of `MailUtils.java` the issue is resolved.
Please fix and build.  This is urgent.

**Comment by bluebaroncanada** [comment]
May be related to https://github.com/GluuFederation/oxTrust/issues/608

**Comment by yurem** [comment]
Merged your pull request
