### ISSUE TITLE
Unable to Add users via oxTrust

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#643]
Click on users > add person, fill in required details.
Even though password and confirm password is same, getting this validation error
![image](https://user-images.githubusercontent.com/21104811/28990172-5f94ab10-7998-11e7-8751-6d40a6f06ab5.png)

Click submit
![image](https://user-images.githubusercontent.com/21104811/28990181-75f77748-7998-11e7-8536-85258247b78a.png)

Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 3.1.0-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: tomcat
Implementation-Build: 1a18acc8ccf62cd0e20214bb8e7bd06043d8f761

Oxtrust log

Caused by: javax.faces.FacesException: #{updatePersonAction.save}: org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to find entry with baseDN: inum=@!B99E.9D6D.BF94.91A7!0001!CFCD.3A40!0000!AD0E.649B.356D.0804,ou=people,o=@!B99E.9D6D.BF94.91A7!0001!CFCD.3A40,o=gluu, filter: (&(objectClass=top)(objectClass=gluuPerson))
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:118) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.co

        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.component.UICommand.broadcast(UICommand.java:315) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81) ~[jsf-impl-2.2.14.jar:2.2.14]
        ... 53 more
Caused by: com.unboundid.ldap.sdk.LDAPSearchException: Failed to scroll to specified startIndex

**Comment by shekhar16** [comment]
@sahiliamsso it working with latest code.Can u please try it with latest identity.war file.
Validation for password and confirm password is working on blurr event so whenever you we will move  these textfield the validation will call.So if both the value are same,the validation will get clear.

**Comment by sahiliamsso** [comment]
@shekhar16 just tried on latest war file. Still getting same error
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 3.1.0-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: tomcat
Implementation-Build: 55827a37709be01b000c74b477ed71293c566092


![image](https://user-images.githubusercontent.com/21104811/29198435-a72092dc-7e61-11e7-98d2-8498ce700bf1.png)


2017-08-11 01:22:22,913 ERROR [qtp985655350-10] [org.gluu.oxtrust.exception.GlobalExceptionHandler] (GlobalExceptionHandler.java:50) - #{updatePersonAction.save}: org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to find entry with baseDN: inum=@!86DE.2EF4.4A1D.B812!0001!93AA.6E4D!0000!0D24.B7F4.1025.1A0B,ou=people,o=@!86DE.2EF4.4A1D.B812!0001!93AA.6E4D,o=gluu, filter: (&(objectClass=top)(objectClass=gluuPerson))
javax.faces.FacesException: #{updatePersonAction.save}: org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to find entry with baseDN: inum=@!86DE.2EF4.4A1D.B812!0001!93AA.6E4D!0000!0D24.B7F4.1025.1A0B,ou=people,o=@!86DE.2EF4.4A1D.B812!0001!93AA.6E4D,o=gluu, filter: (&(objectClass=top)(objectClass=gluuPerson))

**Comment by nynymike** [comment]
Can you include the ldif for this entry? Perhaps the entry is not objectclass gluuPerson...

**Comment by arvindsinghtomar** [comment]
@sahiliamsso I was able to add person successfully.
