### ISSUE TITLE
Log level not changing 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#651]
changing log level from oxTrust ( Configuration -> JSON configuration -> loggingLevel ) is not doing anything in log levels of oxtrust. 

Here is what oxtrust.log says: 

```
2017-08-12 14:05:01,361 INFO  [Thread-337] [org.gluu.oxtrust.config.ConfigurationFactory] (ConfigurationFactory.java:349) - Loading configuration from LDAP...
2017-08-12 14:05:01,366 ERROR [Thread-337] [org.gluu.oxtrust.config.ConfigurationFactory] (ConfigurationFactory.java:368) - WELD-001335: Ambiguous dependencies for type ImportPersonConfig with qualifiers @Default
 Possible dependencies:
  - Managed Bean [class org.xdi.config.oxtrust.ImportPersonConfig] with qualifiers [@Any @Default],
  - Producer Method [ImportPersonConfig] with qualifiers [@Any @Default] declared as [[UnbackedAnnotatedMethod] @Produces @ApplicationScoped public org.gluu.oxtrust.config.ConfigurationFactory.getImportPersonConfig()]
org.jboss.weld.exceptions.AmbiguousResolutionException: WELD-001335: Ambiguous dependencies for type ImportPersonConfig with qualifiers @Default
 Possible dependencies:
  - Managed Bean [class org.xdi.config.oxtrust.ImportPersonConfig] with qualifiers [@Any @Default],
  - Producer Method [ImportPersonConfig] with qualifiers [@Any @Default] declared as [[UnbackedAnnotatedMethod] @Produces @ApplicationScoped public org.gluu.oxtrust.config.ConfigurationFactory.getImportPersonConfig()]
        at org.jboss.weld.bean.builtin.InstanceImpl.get(InstanceImpl.java:117) ~[weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.gluu.oxtrust.config.ConfigurationFactory.destroy(ConfigurationFactory.java:384) ~[classes/:?]
        at org.gluu.oxtrust.config.ConfigurationFactory$Proxy$_$$_WeldSubclass.destroy(Unknown Source) ~[classes/:?]
        at org.gluu.oxtrust.config.ConfigurationFactory.createFromLdap(ConfigurationFactory.java:359) [classes/:?]
        at org.gluu.oxtrust.config.ConfigurationFactory.reloadConfiguration(ConfigurationFactory.java:231) [classes/:?]
        at org.gluu.oxtrust.config.ConfigurationFactory.reloadConfigurationTimerEvent(ConfigurationFactory.java:179) [classes/:?]
        at org.gluu.oxtrust.config.ConfigurationFactory$Proxy$_$$_WeldSubclass.reloadConfigurationTimerEvent$$super(Unknown Source) [classes/:?]
        at sun.reflect.GeneratedMethodAccessor150.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) [weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.xdi.service.cdi.async.AsynchronousInterceptor$1.get(AsynchronousInterceptor.java:36) [oxcore-service-3.1.0-SNAPSHOT.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_112]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

```

**Comment by worm333** [comment]
Fixed in [this](https://github.com/GluuFederation/oxCore/pull/46) pull request.
