### ISSUE TITLE
smtp configuration not working

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#708]
Provide  valid smtp Server configurations and click ?Test Configuration" 

![image](https://user-images.githubusercontent.com/21104811/30006133-259a4bf8-90e1-11e7-8b8b-feae9336cc9b.png)

2017-09-03 19:44:46,998 INFO  [qtp985655350-19] [org.gluu.oxtrust.action.UpdateOrganizationAction] (UpdateOrganizationAction.java:239) - UserName: support@gluu.org Password: null
2017-09-03 19:44:46,999 ERROR [qtp985655350-19] [org.gluu.oxtrust.ldap.service.ApplianceService] (ApplianceService.java:228) - Failed to decrypt SMTP password
org.xdi.util.security.StringEncrypter$EncryptionException: javax.crypto.IllegalBlockSizeException: Input length must be multiple of 8 when decrypting with padded cipher
        at org.xdi.util.security.StringEncrypter.decrypt(StringEncrypter.java:214) ~[oxcore-util-3.1.0-SNAPSHOT.jar:?]
        at org.xdi.util.security.StringEncrypter.decrypt(StringEncrypter.java:228) ~[oxcore-util-3.1.0-SNAPSHOT.jar:?]
        at org.xdi.util.security.StringEncrypter$Proxy$_$$_WeldClientProxy.decrypt(Unknown Source) ~[oxcore-util-3.1.0-SNAPSHOT.jar:?]
        at org.gluu.oxtrust.ldap.service.EncryptionService.decrypt(EncryptionService.java:43) ~[classes/:?]
        at org.gluu.oxtrust.ldap.service.EncryptionService$Proxy$_$$_WeldSubclass.decrypt$$super(Unknown Source) ~[classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51) ~[weld-core-impl-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78) ~[weld-core-impl-3.0.0.Final.jar:3.0.0.Final]

**Comment by worm333** [comment]
This issue was fixed about 10 hours ago in [this commit](https://github.com/GluuFederation/oxTrust/commit/07ce59a40bfe63f37e0d36ff7aa01b736e6e72e3), most likely the build you tested did not contain these changes.

 Could you please confirm the fix, when a new build would be available?

**Comment by sahiliamsso** [comment]
it was verified in latest war file http://ox.gluu.org/maven/org/xdi/oxtrust-server/3.1.0-SNAPSHOT/oxtrust-server-3.1.0-SNAPSHOT.war

**Comment by yurem** [comment]
According to https://ox.gluu.org/jenkins/job/oxTrust/ ypu checked not latest build due to build failuer. I've fixed data in LDAP and last build was successful. Can you check latest war again?

**Comment by yurem** [comment]
Fixed

**Comment by zamilskhan** [comment]
Please see the stack trace available @ https://pastebin.com/hyabwRaQ when I click "Test Configuration"

**Comment by yurem** [comment]
Fixed

**Comment by yurem** [comment]
Try to deploy http://ox.gluu.org/maven/org/xdi/oxtrust-server/3.1.1-SNAPSHOT/oxtrust-server-3.1.1-SNAPSHOT.war to verify it.

**Comment by sahiliamsso** [comment]
same issue in latest build tol

**Comment by yurem** [comment]
I've checked SMTP settings again and tried to send registration confirmation e-mails
It work for me with Gluu and Google SMTP server. I use 587 TLS port.
