### ISSUE TITLE
User registration fails when "user_confirm_registration" is enabled

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#713]
Enable "user_confirm_registration" & "user_registration"
Go to registration URL -  https://host/identity/register  and provide valid inputs.
Registration fails.
PS: It works fine when "user_confirm_registration" is disabled.

![image](https://user-images.githubusercontent.com/21104811/30041437-a5f04376-9207-11e7-8f61-42eb8df917c7.png)

2017-09-05 01:27:47,278 ERROR [qtp985655350-13] [org.gluu.oxtrust.action.RegisterPersonAction] (RegisterPersonAction.java:279) - Failed to add new person @!FF12.C347.852C.425A!0001!2D69.7049!0000!9FE7.3F7B.D274.D2E5
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to persist entry: inum=@!FF12.C347.852C.425A!0001!2D69.7049!0000!9FE7.3F7B.D274.D2E5,ou=people,o=@!FF12.C347.852C.425A!0001!2D69.7049,o=gluu
        at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:99) ~[oxcore-ldap-3.1.0-SNAPSHOT.jar:?]
        at org.gluu.site.ldap.persistence.AbstractEntryManager.persist(AbstractEntryManager.java:90) ~[oxcore-ldap-3.1.0-SNAPSHOT.jar:?]
        at org.gluu.site.ldap.persistence.LdapEntryManager$Proxy$_$$_WeldClientProxy.persist(Unknown Source) ~[oxcore-ldap-3.1.0-SNAPSHOT.jar:?]
        at org.gluu.oxtrust.ldap.service.PersonService.addPerson(PersonService.java:103) ~[classes/:?]
        at org.gluu.oxtrust.action.RegisterPersonAction.registerImpl(RegisterPersonAction.java:269) [classes/:?]
        at org.gluu.oxtrust.action.RegisterPersonAction.register(RegisterPersonAction.java:196) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.apache.el.parser.AstValue.invoke(AstValue.java:247) [org.mortbay.jasper.apache-el-8.0.33.jar:8.0.33]
        at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267) [org.mortbay.jasper.apache-el-8.0.33.jar:8.0.33]
        at org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40) [weld-web-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50) [weld-web-3.0.0.Final.jar:3.0.0.Final]
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105) [jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87) [jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102) [jsf-impl-2.2.14.jar:2.2.14]
                                                       

        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: com.unboundid.ldap.sdk.LDAPException: attribute 'oxGuid' not allowed
        at com.unboundid.ldap.sdk.LDAPConnection.add(LDAPConnection.java:1959) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
        at com.unboundid.ldap.sdk.AbstractConnectionPool.add(AbstractConnectionPool.java:752) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
        at com.unboundid.ldap.sdk.AbstractConnectionPool.add(AbstractConnectionPool.java:683) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
        at org.gluu.site.ldap.OperationsFacade.addEntry(OperationsFacade.java:494) ~[oxcore-ldap-3.1.0-SNAPSHOT.jar:?]
        at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:94) ~[oxcore-ldap-3.1.0-SNAPSHOT.jar:?]
        ... 66 more
2017-09-05 01:27:47,279 ERROR [qtp985655350-13] [org.gluu.oxtrust.action.RegisterPersonAction] (RegisterPersonAction.java:202) - Failed to register new user. Please make sure you are not registering a duplicate account or try another username.

**Comment by shekhar16** [comment]
It seems like its an schema related issue.

**Comment by yurem** [comment]
@shekhar16 , yes, please add it

**Comment by sahiliamsso** [comment]
still getting same error in 3.1.1
017-09-21 01:45:11,961 ERROR [qtp985655350-19] [org.gluu.oxtrust.action.RegisterPersonAction] (RegisterPersonAction.java:286) - Failed to add new person @!3858.EEC1.E64C.B1C1!0001!21DC.ED59!0000!E04E.7825.C805.A32B
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to persist entry: inum=@!3858.EEC1.E64C.B1C1!0001!21DC.ED59!0000!E04E.7825.C805.A32B,ou=people,o=@!3858.EEC1.E64C.B1C1!0001!21DC.ED59,o=gluu
        at org.gluu.site.ldap.persistence.LdapEntryManager.persist(LdapEntryManager.java:101) ~[oxcore-ldap-3.1.1-SNAPSHOT.jar:?]
        at org.gluu.site.ldap.persistence.AbstractEntryManager.persist(AbstractEntryManager.java:90) ~[oxcore-ldap-3.1.1-SNAPSHOT.jar:?]
        at org.gluu.site.ldap.persistence.LdapEntryManager$Proxy$_$$_WeldClientProxy.persist(Unknown Source) ~[oxcore-ldap-3.1.1-SNAPSHOT.jar:?]
        at org.gluu.oxtrust.ldap.service.PersonService.addPerson(PersonService.java:103) ~[classes/:?]
        at org.gluu.oxtrust.action.RegisterPersonAction.registerImpl(RegisterPersonAction.java:272) [classes/:?]
        at org.gluu.oxtrust.action.RegisterPersonAction.register(RegisterPersonAction.java:196) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.apache.el.parser.AstValue.invoke(AstValue.java:247) [org.mortbay.jasper.apache-el-8.0.33.jar:8.0.33]
        at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267) [org.mortbay.jasper.apache-el-8.0.33.jar:8.0.33]
        at org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40) [weld-web-3.0.0.Final.jar:3.0.0.Final]
        at org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50) [weld-web-3.0.0.Final.jar:3.0.0.Final]
        at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105) [jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87) [jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102) [jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.component.UICommand.broadcast(UICommand.java:315) [jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790) [jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282) [jsf-api-2.2.14.jar:2.2]

**Comment by shekhar16** [comment]
@sahiliamsso  Can u please share the octrust_script.log .

**Comment by sahiliamsso** [comment]
oxtrust_script.log
2017-09-24 06:06:42,503 INFO  [oxTrustScheduler_Worker-4] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:208) - User registration. Initialization
2017-09-24 06:06:42,503 INFO  [oxTrustScheduler_Worker-4] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:208) - User registration. Initialized successfully
2017-09-24 06:07:27,332 INFO  [qtp985655350-13] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:208) - User registration. Init method
2017-09-24 06:07:27,333 INFO  [qtp985655350-13] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:208) - User registration. Init method
2017-09-24 06:08:13,755 INFO  [qtp985655350-16] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:208) - User registration. Pre method
2017-09-24 06:08:13,756 INFO  [qtp985655350-16] [org.xdi.service.PythonService$PythonLoggerOutputStream] (PythonService.java:208) - User registration. Pre method

**Comment by sahiliamsso** [comment]
Also, Please check when adding user attribute on registration screen, we get error 
![image](https://user-images.githubusercontent.com/21104811/30780012-bf46524a-a11e-11e7-8571-432a989502be.png)

![image](https://user-images.githubusercontent.com/21104811/30780013-c5db20ae-a11e-11e7-8c86-a76e3889d345.png)

2017-09-24 06:19:44,999 ERROR [qtp985655350-12] [org.gluu.oxtrust.exception.GlobalExceptionHandler] (GlobalExceptionHandler.java:54) - #{registerPersonAction.initPerson}: java.lang.NullPointerException
javax.faces.FacesException: #{registerPersonAction.initPerson}: java.lang.NullPointerException
        at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:89) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198) [jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658) [jsf-api-2.2.14.jar:2.2]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) [jetty-security-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]

**Comment by zamilskhan** [comment]
Fixed in package: gluu-server-3.1.1.x86_64 1-1.beta3.centos6
oxTrust Implementation-Build: faf1ea73603d158b89023af4b8c4038a8054a611

**Comment by sahiliamsso** [comment]
still failing when "user_confirm_registration" is enabled

**Comment by yurem** [comment]
Fixed
