### ISSUE TITLE
Error 503 when Shibboleth IDP is installed

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#726]
Install Gluu 3.1.1 with following components
Install oxAuth OAuth2 Authorization Server? [Yes] :
Install oxTrust Admin UI? [Yes] :
Install LDAP Server? [Yes] :
Install Apache HTTPD Server [Yes] :
Install Shibboleth SAML IDP? [No] : Yes
Install Asimba SAML Proxy? [No] : Yes
Install oxAuth RP? [No] : Yes
Install Passport? [No] : Yes
Install JCE 1.8? [Yes] :

UI throws error

HTTP ERROR: 503

Problem accessing /identity/home.htm. Reason:

    Service Unavailable

oxtrust logs

2017-09-21 22:59:19,964 INFO  [main] [org.gluu.oxtrust.ldap.service.ShibbolethInitializer] (ShibbolethInitializer.java:66) - No trust relationships exist in LDAP. Adding gluuSP
2017-09-21 22:59:20,241 ERROR [main] [org.apache.velocity.runtime.log.CommonsLogLogChute] (CommonsLogLogChute.java:96) - ResourceManager : unable to find resource 'sp-metadata.xml.vm' in any resource loader.
2017-09-21 22:59:20,242 ERROR [main] [org.gluu.oxtrust.ldap.service.TemplateService] (TemplateService.java:56) - Failed to load velocity template 'sp-metadata.xml'
org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'sp-metadata.xml.vm'
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.loadResource(ResourceManagerImpl.java:474) ~[velocity-1.7.jar:1.7]
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.getResource(ResourceManagerImpl.java:352) ~[velocity-1.7.jar:1.7]
        at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1533) ~[velocity-1.7.jar:1.7]
        at org.apache.velocity.runtime.RuntimeSingleton.getTemplate(RuntimeSingleton.java:317) ~[velocity-1.7.jar:1.7]
        at org.apache.velocity.app.Velocity.mergeTemplate(Velocity.java:328) ~[velocity-1.7.jar:1.7]
        at org.gluu.oxtrust.ldap.service.TemplateService.generateConfFile(TemplateService.java:54) [classes/:?]
        at org.gluu.oxtrust.ldap.service.TemplateService$Proxy$_$$_WeldClientProxy.generateConfFile(Unknown Source) [classes/:?]
        at org.gluu.oxtrust.ldap.service.Shibboleth3ConfService.generateSpMetadataFileContent(Shibboleth3ConfService.java:823) [classes/:?]
        at org.gluu.oxtrust.ldap.service.Shibboleth3ConfService.generateSpMetadataFile(Shibboleth3ConfService.java:806) [classes/:?]
        at org.gluu.oxtrust.ldap.service.Shibboleth3ConfService.addGluuSP(Shibboleth3ConfService.java:1449) [classes/:?]
        at org.gluu.oxtrust.ldap.service.ShibbolethInitializer.createShibbolethConfiguration(ShibbolethInitializer.java:70) [classes/:?]
        at org.gluu.oxtrust.ldap.service.ShibbolethInitializer$Proxy$_$$_WeldClientProxy.createShibbolethConfiguration(Unknown Source) [classes/:?]
        at org.gluu.oxtrust.ldap.service.AppInitializer.applicationInitialized(AppInitializer.java:221) [classes/:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]

**Comment by yurem** [comment]
Fixed in beta2
