### ISSUE TITLE
Cache Refresh Error on adding "Source attribute to destination attribute mapping"

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#727]
Go to Configuration > Cache Refresh, Click on "Source attribute to destination attribute mapping"

![image](https://user-images.githubusercontent.com/21104811/30727761-ff9851d6-9f70-11e7-861a-827d499f5e95.png)

![image](https://user-images.githubusercontent.com/21104811/30727787-1ef40958-9f71-11e7-9f62-c0aaabf01469.png)

2017-09-22 03:03:08,957 ERROR [qtp985655350-18] [com.sun.faces.application.view.FaceletViewHandlingStrategy] (FaceletViewHandlingStrategy.java:1235) - Error Rendering View[/organization/cacheRefresh.xhtml]
javax.el.PropertyNotFoundException: //opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-5306127024761619303.dir/webapp/resources/ox/simpleCustomPropertiesList.xhtml @67,332 rendered="#{(_property.hideValue eq false) or (cc.attrs.hideValue eq false)}": Property 'hideValue' not found on type org.xdi.model.SimpleCustomProperty
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:111) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponentBase.isRendered(UIComponentBase.java:458) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:297) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.renderkit.html_basic.GridRenderer.renderRow(GridRenderer.java:185) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.renderkit.html_basic.GridRenderer.encodeChildren(GridRenderer.java:129) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856) ~[jsf-api-2.2.14.jar:2.2]
        at org.richfaces.renderkit.html.RepeatRenderer$1.process(RepeatRenderer.java:57) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at org.ajax4jsf.model.SequenceDataModel.walk(SequenceDataModel.java:66) ~[richfaces-core-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.component.UIDataAdaptor.walk(UIDataAdaptor.java:817) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.renderkit.html.RepeatRenderer.encodeChildren(RepeatRenderer.java:70) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:309) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:582) ~[jsf-impl-2.2.14.jar:2.2.14]
        at org.richfaces.context.MetaComponentEncodingVisitCallback.visit(MetaComponentEncodingVisitCallback.java:83) ~[richfaces-core-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.context.BaseExtendedVisitContext.invokeVisitCallback(BaseExtendedVisitContext.java:103) ~[richfaces-core-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.context.ExtendedRenderVisitContext.invokeVisitCallback(ExtendedRenderVisitContext.java:65) ~[richfaces-core-4.5.17.Final.jar:4.5.17.Final]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1689) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700) ~[jsf-api-2.2.14.jar:2.2]

**Comment by shekhar16** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/15937500/30776663-105d7cdc-a0c8-11e7-990a-a62ebcb9b972.png)

**Comment by yurem** [comment]
@shekhar16 I fixed simpleCustomPropertiesList.xhtml and reverted CR changes

**Comment by mzico** [comment]
@shekhar16 @yurem @shekhar16 : Now the issue is... this button is not doing at all. 

oxtrust.log when I click on this button: 

```
2017-09-27 15:17:15,444 ERROR [qtp985655350-18] [org.gluu.oxtrust.exception.GlobalExceptionHandler] (GlobalExceptionHandler.java:54) - //opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-9147605995641204587.dir/webapp/resources/ox/simpleCustomPropertiesList.xhtml @73,89 value="#{_property.hideValue}": Property 'hideValue' not found on type org.xdi.model.SimpleCustomProperty
javax.el.PropertyNotFoundException: //opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-9147605995641204587.dir/webapp/resources/ox/simpleCustomPropertiesList.xhtml @73,89 value="#{_property.hideValue}": Property 'hideValue' not found on type org.xdi.model.SimpleCustomProperty
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:111) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:182) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIOutput.getValue(UIOutput.java:174) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIInput.getValue(UIInput.java:291) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.renderkit.html_basic.HtmlBasicInputRenderer.getValue(HtmlBasicInputRenderer.java:205) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.getCurrentValue(HtmlBasicRenderer.java:355) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeEnd(HtmlBasicRenderer.java:164) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:312) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.renderkit.html_basic.GridRenderer.renderRow(GridRenderer.java:185) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.renderkit.html_basic.GridRenderer.encodeChildren(GridRenderer.java:129) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856) ~[jsf-api-2.2.14.jar:2.2]
        at org.richfaces.renderkit.html.RepeatRenderer$1.process(RepeatRenderer.java:57) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at org.ajax4jsf.model.SequenceDataModel.walk(SequenceDataModel.java:66) ~[richfaces-core-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.component.UIDataAdaptor.walk(UIDataAdaptor.java:817) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.renderkit.html.RepeatRenderer.encodeChildren(RepeatRenderer.java:70) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:309) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.renderkit.html_basic.GroupRenderer.encodeChildren(GroupRenderer.java:114) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:582) ~[jsf-impl-2.2.14.jar:2.2.14]
        at org.richfaces.context.MetaComponentEncodingVisitCallback.visit(MetaComponentEncodingVisitCallback.java:83) ~[richfaces-core-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.context.BaseExtendedVisitContext.invokeVisitCallback(BaseExtendedVisitContext.java:103) ~[richfaces-core-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.context.ExtendedRenderVisitContext.invokeVisitCallback(ExtendedRenderVisitContext.java:65) ~[richfaces-core-4.5.17.Final.jar:4.5.17.Final]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1689) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UINamingContainer.visitTree(UINamingContainer.java:174) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIForm.visitTree(UIForm.java:371) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.visitTree(UIComponent.java:1700) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:403) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:322) ~[jsf-impl-2.2.14.jar:2.2.14]
        at org.richfaces.context.ExtendedPartialViewContext.processPartial(ExtendedPartialViewContext.java:264) ~[richfaces-core-4.5.17.Final.jar:4.5.17.Final]
        at javax.faces.context.PartialViewContextWrapper.processPartial(PartialViewContextWrapper.java:219) ~[jsf-api-2.2.14.jar:2.2]
        at org.omnifaces.context.OmniPartialViewContext.processPartial(OmniPartialViewContext.java:124) ~[omnifaces-2.6.3.jar:2.6.3]
        at javax.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1004) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:432) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:134) ~[jsf-impl-2.2.14.jar:2.2.14]
        at org.ocpsoft.rewrite.faces.RewriteViewHandler.renderView(RewriteViewHandler.java:196) ~[rewrite-integration-faces-3.4.1.Final.jar:3.4.1.Final]
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337) ~[jsf-api-2.2.14.jar:2.2]
        at org.omnifaces.viewhandler.OmniViewHandler.renderView(OmniViewHandler.java:121) ~[omnifaces-2.6.3.jar:2.6.3]
        at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219) [jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659) [jsf-api-2.2.14.jar:2.2]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) [jetty-security-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.ocpsoft.rewrite.servlet.impl.HttpRewriteResultHandler.handleResult(HttpRewriteResultHandler.java:42) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
        at org.ocpsoft.rewrite.servlet.RewriteFilter.rewrite(RewriteFilter.java:297) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
        at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:198) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.Server.handle(Server.java:534) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: javax.el.PropertyNotFoundException: Property 'hideValue' not found on type org.xdi.model.SimpleCustomProperty
        at javax.el.BeanELResolver$BeanProperties.get(BeanELResolver.java:268) ~[org.mortbay.jasper.apache-el-8.0.33.jar:8.0.33]
        at javax.el.BeanELResolver$BeanProperties.access$300(BeanELResolver.java:221) ~[org.mortbay.jasper.apache-el-8.0.33.jar:8.0.33]
        at javax.el.BeanELResolver.property(BeanELResolver.java:355) ~[org.mortbay.jasper.apache-el-8.0.33.jar:8.0.33]
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:95) ~[org.mortbay.jasper.apache-el-8.0.33.jar:8.0.33]
        at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203) ~[jsf-impl-2.2.14.jar:2.2.14]
        at org.apache.el.parser.AstValue.getValue(AstValue.java:169) ~[org.mortbay.jasper.apache-el-8.0.33.jar:8.0.33]
        at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184) ~[org.mortbay.jasper.apache-el-8.0.33.jar:8.0.33]
        at org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50) ~[weld-web-3.0.0.Final.jar:3.0.0.Final]
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109) ~[jsf-impl-2.2.14.jar:2.2.14]

```

**Comment by shekhar16** [comment]
Fixed.
![image](https://user-images.githubusercontent.com/15937500/30929052-f3c6dd1e-a3da-11e7-936c-80eb6a2c328a.png)

**Comment by shekhar16** [comment]
Please test it, with latest identity.war file.
