### ISSUE TITLE
User Registration tab not working

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#735]
Click Manage Custom Scripts > User Registration

![image](https://user-images.githubusercontent.com/21104811/30964713-3294be0e-a470-11e7-8d83-0df40b289720.png)

2017-09-28 11:39:47,720 ERROR [qtp985655350-16] [org.gluu.oxtrust.exception.GlobalExceptionHandler] (GlobalExceptionHandler.java:54) - javax.el.PropertyNotWritableException: //opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-687943990906516603.dir/webapp/resources/ox/simpleCustomPropertiesList.xhtml @73,138 value="#{_property.hideValue eq true}": Illegal Syntax for Set Operation
javax.faces.component.UpdateModelException: javax.el.PropertyNotWritableException: //opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-687943990906516603.dir/webapp/resources/ox/simpleCustomPropertiesList.xhtml @73,138 value="#{_property.hideValue eq true}": Illegal Syntax for Set Operation
        at javax.faces.component.UIInput.updateModel(UIInput.java:866) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIInput.processUpdates(UIInput.java:749) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1291) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1291) ~[jsf-api-2.2.14.jar:2.2]
        at org.richfaces.component.UIDataAdaptor$4.processComponent(UIDataAdaptor.java:135) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.component.UIDataAdaptor$ComponentVisitor.process(UIDataAdaptor.java:1442) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at org.ajax4jsf.model.SequenceDataModel.walk(SequenceDataModel.java:66) ~[richfaces-core-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.component.UIDataAdaptor.walk(UIDataAdaptor.java:817) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.component.UIDataAdaptor.iterate(UIDataAdaptor.java:791) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.component.UIDataAdaptor.processUpdatesChildren(UIDataAdaptor.java:875) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at org.richfaces.component.UIDataAdaptor.processUpdates(UIDataAdaptor.java:855) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
        at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1291) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1291) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1291) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1291) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1291) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1291) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1291) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1291) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponentBase.processUpdates(UIComponentBase.java:1291) ~[jsf-api-2.2.14.jar:2.2]

**Comment by zamilskhan** [comment]
Confirmed for CentOS package too.

**Comment by zamilskhan** [comment]
This is strange, in a fresh VM installation, I can access register panel from custom scripts.
Package: gluu-server-3.1.1.x86_64 1-1.beta2.centos6
oxTrust version: c53c988589e3edaa47ea06df843804e639cf17f4

**Comment by yurem** [comment]
Fixed
