### ISSUE TITLE
ArrayIndexOutOfBoundsException error for 2.2 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxTrust#74]
Though there is no visible problem producing for this error but then again it's coming periodically in oxtrust.log 

2015-05-24 08:09:18,789 ERROR [org.jboss.seam.async.AsynchronousExceptionHandler] Exception thrown whilst executing asynchronous call
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.gluu.oxtrust.ldap.service.StatusCheckerTimer.setCertificateExpiryAttributes(StatusCheckerTimer.java:165)
	at org.gluu.oxtrust.ldap.service.StatusCheckerTimer.process(StatusCheckerTimer.java:126)
	at org.gluu.oxtrust.ldap.service.StatusCheckerTimer.scheduleStatusChecking(StatusCheckerTimer.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
	at org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
	at org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	at org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	at org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	at org.jboss.seam.async.AsynchronousInterceptor.aroundInvoke(AsynchronousInterceptor.java:52)
	at org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	at org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
	at org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196)
	at org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114)
	at org.gluu.oxtrust.ldap.service.StatusCheckerTimer_$$_javassist_seam_7.scheduleStatusChecking(StatusCheckerTimer_$$_javassist_seam_7.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
	at org.jboss.seam.util.Reflections.invokeAndWrap(Reflections.java:144)
	at org.jboss.seam.async.AsynchronousInvocation$1.process(AsynchronousInvocation.java:62)
	at org.jboss.seam.async.Asynchronous$ContextualAsynchronousRequest.run(Asynchronous.java:80)
	at org.jboss.seam.async.AsynchronousInvocation.execute(AsynchronousInvocation.java:44)
	at org.jboss.seam.async.ThreadPoolDispatcher$RunnableAsynchronous.run(ThreadPoolDispatcher.java:142)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yurem** [comment]
I see the same on ce-dev.gluu.org 2.3.1

**Comment by iromli** [comment]
It also occurs in v2.3.2. In cluster usecase, the errors are thrown when oxTrust running `check_ssl` subprocess. Disabling `check_ssl` removes the errors above (but it throws different errors though).

**Comment by yurem** [comment]
https://github.com/GluuFederation/oxTrust/commit/7604c17ae453018945fe15e39bfc393ed5241192

**Comment by yurem** [comment]
We fixed this in 2.3 branch (https://github.com/GluuFederation/oxTrust/commit/be4a1938a56dd5b25e66dcd738cbcb7543b8a9fd) but not released because our next version should be 2.4.0.
You can replace identity.war in /opt/tomcat/webapps with latest oxTrust 2.3 build: http://ox.gluu.org/maven/org/xdi/oxtrust-server/2.3.3.Final/oxtrust-server-2.3.3.Final.war
