### ISSUE TITLE
Remote IDP's certificate (Asimba flows' settings) is not being imported

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#755]
Environment: Ubuntu 14.04,  gluu-server-3.1.1-1.8~trusty+Ub14.04 

Steps to reproduce:
1. Log in to web UI as admin user
2. Move to "SAML -> Asimba -> IDPs" page
3. Create a remote IDP entry there, providing metadata with url and a certificate through "Upload" UI control, while monitoring `/opt/gluu/jetty/identity/logs/oxtrust.log` at the same time

Result:
Certificate isn't added to `/etc/certs/asimbaIDP.jks` keystore and Java error trace is registered in the log (full text is [here](https://github.com/GluuFederation/oxTrust/files/1399288/asimba_remIDP_cert_trace.txt)):

```
2017-10-19 16:07:49,965 WARN  [qtp985655350-12] [org.gluu.oxtrust.service.asimba.AsimbaXMLConfigurationService] (AsimbaXMLConfigurationService.java:147) - Certificate parsing exception
java.lang.ClassCastException: org.bouncycastle.cert.X509CertificateHolder cannot be cast to java.security.cert.X509Certificate
	at org.gluu.oxtrust.ldap.service.SSLService.getPEMCertificateStatic(SSLService.java:128) ~[classes/:?]
	at org.gluu.oxtrust.ldap.service.SSLService.getPEMCertificate(SSLService.java:101) ~[classes/:?]
	at org.gluu.oxtrust.service.asimba.AsimbaXMLConfigurationService.addCertificateFile(AsimbaXMLConfigurationService.java:141) [classes/:?]

...

2017-10-19 16:07:49,977 ERROR [qtp985655350-12] [org.gluu.oxtrust.service.asimba.AsimbaXMLConfigurationService] (AsimbaXMLConfigurationService.java:173) - Add Certificate to keystore exception
java.lang.NullPointerException: null
	at java.security.Provider$ServiceKey.<init>(Provider.java:872) ~[?:1.8.0_112]
	at java.security.Provider$ServiceKey.<init>(Provider.java:865) ~[?:1.8.0_112]
	at java.security.Provider.getService(Provider.java:1039) ~[?:1.8.0_112]
```

Please note that there are 2 different errors: inability to parse the certificate, and then failing to add it to keystore. When I removed "BEGIN/END CERTIFICATE" tags from certificate file (as it solves similar issue for certificate used by Asimba auth script itself), the first error disappeared, yet the 2nd one still remained, so they may be 2 different issues.

**Comment by yurem** [comment]
@dmogn Can you take a look on this?

**Comment by dmogn** [comment]
Done.
