### ISSUE TITLE
Error page showing for Manage Authentication link

### ISSUE THREAD

**Issue by wasiqulhuq** [GluuFederation/oxTrust#886]
1. Login to Gluu
2. Click on Manage Authentication link in Configuration
3. Observe that an error page is showing

Check below screens for detail information,

![login](https://user-images.githubusercontent.com/36174217/37061356-72abfbcc-21bd-11e8-9218-1bcaa2c673fe.JPG)

![error1](https://user-images.githubusercontent.com/36174217/37061370-7cf0a34e-21bd-11e8-8546-657981f97d67.JPG)

![error](https://user-images.githubusercontent.com/36174217/37061376-87d6374c-21bd-11e8-9db6-703f93822261.JPG)

**Comment by yurem** [comment]
It looks like application can't render Configuration page. Without stack trace from log it's not easy cto understand the root case. Can you add it to this issue?

**Comment by mzico** [comment]
@yurem @wasiqulhuq : Here is the error: 

```
GLUU.root@wasiqul:/opt/gluu/jetty/identity/logs# tail -f 2018_03_06.stderrout.log

2018-03-07 06:00:50,209 INFO  [qtp985655350-13] [org.gluu.oxtrust.action.ManagePersonAuthenticationAction] (ManagePersonAuthenticationAction.java:149) - passport enabled value  : 'disabled'
2018-03-07 06:00:50,339 ERROR [qtp985655350-13] [org.gluu.oxtrust.exception.GlobalExceptionHandler] (GlobalExceptionHandler.java:54) - Error Parsing //opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-4769967873212809348.dir/webapp/resources/ox/simplePropertiesList.xhtml: Error Traced[line: 39] The element type "h:panelGroup" must be terminated by the matching end-tag "</h:panelGroup>".
javax.faces.view.facelets.FaceletException: Error Parsing //opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-4769967873212809348.dir/webapp/resources/ox/simplePropertiesList.xhtml: Error Traced[line: 39] The element type "h:panelGroup" must be terminated by the matching end-tag "</h:panelGroup>".
	at com.sun.faces.facelets.compiler.SAXCompiler.doCompile(SAXCompiler.java:466) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.compiler.SAXCompiler.doCompile(SAXCompiler.java:440) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.compiler.Compiler.compile(Compiler.java:124) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFaceletFactory.createFacelet(DefaultFaceletFactory.java:481) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFaceletFactory.access$100(DefaultFaceletFactory.java:106) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFaceletFactory$1.newInstance(DefaultFaceletFactory.java:199) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFaceletFactory$1.newInstance(DefaultFaceletFactory.java:197) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFaceletCache$1.newInstance(DefaultFaceletCache.java:86) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFaceletCache$1.newInstance(DefaultFaceletCache.java:81) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.util.ExpiringConcurrentCache$1.call(ExpiringConcurrentCache.java:99) ~[jsf-impl-2.2.14.jar:2.2.14]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_112]
	at com.sun.faces.util.ExpiringConcurrentCache.get(ExpiringConcurrentCache.java:114) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFaceletCache.getFacelet(DefaultFaceletCache.java:124) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFaceletCache.getFacelet(DefaultFaceletCache.java:63) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFaceletFactory.getFacelet(DefaultFaceletFactory.java:295) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.createComponentMetadata(FaceletViewHandlingStrategy.java:288) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.application.view.FaceletViewHandlingStrategy$2.newInstance(FaceletViewHandlingStrategy.java:1079) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.application.view.FaceletViewHandlingStrategy$2.newInstance(FaceletViewHandlingStrategy.java:1075) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.util.Cache.get(Cache.java:106) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.getComponentMetadata(FaceletViewHandlingStrategy.java:252) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.application.ApplicationImpl.createComponent(ApplicationImpl.java:949) ~[jsf-impl-2.2.14.jar:2.2.14]
	at javax.faces.application.ApplicationWrapper.createComponent(ApplicationWrapper.java:648) ~[jsf-api-2.2.14.jar:2.2]
	at javax.faces.application.ApplicationWrapper.createComponent(ApplicationWrapper.java:648) ~[jsf-api-2.2.14.jar:2.2]
	at com.sun.faces.facelets.tag.jsf.CompositeComponentTagHandler.createComponent(CompositeComponentTagHandler.java:161) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.createComponent(ComponentTagHandlerDelegateImpl.java:587) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:175) ~[jsf-impl-2.2.14.jar:2.2.14]
	at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120) ~[jsf-api-2.2.14.jar:2.2]
	at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95) ~[jsf-api-2.2.14.jar:2.2]
	at javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137) ~[jsf-api-2.2.14.jar:2.2]
	at org.richfaces.view.facelets.html.BehaviorsAddingComponentHandlerWrapper.applyNextHandler(BehaviorsAddingComponentHandlerWrapper.java:53) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
	at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202) ~[jsf-impl-2.2.14.jar:2.2.14]
	at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120) ~[jsf-api-2.2.14.jar:2.2]
	at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95) ~[jsf-api-2.2.14.jar:2.2]
	at javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137) ~[jsf-api-2.2.14.jar:2.2]
	at org.richfaces.view.facelets.html.BehaviorsAddingComponentHandlerWrapper.applyNextHandler(BehaviorsAddingComponentHandlerWrapper.java:53) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
	at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202) ~[jsf-impl-2.2.14.jar:2.2.14]
	at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120) ~[jsf-api-2.2.14.jar:2.2]
	at com.sun.faces.facelets.tag.composite.ImplementationHandler.apply(ImplementationHandler.java:81) ~[jsf-impl-2.2.14.jar:2.2.14]
	at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95) ~[jsf-api-2.2.14.jar:2.2]
	at com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:93) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:87) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:312) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:371) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFaceletContext.includeFacelet(DefaultFaceletContext.java:326) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.tag.jsf.CompositeComponentTagHandler.applyCompositeComponent(CompositeComponentTagHandler.java:387) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.tag.jsf.CompositeComponentTagHandler.applyNextHandler(CompositeComponentTagHandler.java:188) ~[jsf-impl-2.2.14.jar:2.2.14]
	at org.richfaces.view.facelets.html.BehaviorsAddingComponentHandlerWrapper.applyNextHandler(BehaviorsAddingComponentHandlerWrapper.java:53) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
	at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202) ~[jsf-impl-2.2.14.jar:2.2.14]
	at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120) ~[jsf-api-2.2.14.jar:2.2]
	at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95) ~[jsf-api-2.2.14.jar:2.2]
	at javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137) ~[jsf-api-2.2.14.jar:2.2]
	at org.richfaces.view.facelets.html.BehaviorsAddingComponentHandlerWrapper.applyNextHandler(BehaviorsAddingComponentHandlerWrapper.java:53) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
	at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202) ~[jsf-impl-2.2.14.jar:2.2.14]
	at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120) ~[jsf-api-2.2.14.jar:2.2]
	at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95) ~[jsf-api-2.2.14.jar:2.2]
	at javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137) ~[jsf-api-2.2.14.jar:2.2]
	at org.richfaces.view.facelets.html.BehaviorsAddingComponentHandlerWrapper.applyNextHandler(BehaviorsAddingComponentHandlerWrapper.java:53) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
	at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202) ~[jsf-impl-2.2.14.jar:2.2.14]
	at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120) ~[jsf-api-2.2.14.jar:2.2]
	at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95) ~[jsf-api-2.2.14.jar:2.2]
	at javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137) ~[jsf-api-2.2.14.jar:2.2]
	at org.richfaces.view.facelets.html.BehaviorsAddingComponentHandlerWrapper.applyNextHandler(BehaviorsAddingComponentHandlerWrapper.java:53) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
	at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202) ~[jsf-impl-2.2.14.jar:2.2.14]
	at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120) ~[jsf-api-2.2.14.jar:2.2]
	at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95) ~[jsf-api-2.2.14.jar:2.2]
	at com.sun.faces.facelets.tag.ui.CompositionHandler.apply(CompositionHandler.java:194) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:93) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:87) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:312) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:371) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:350) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFaceletContext.includeFacelet(DefaultFaceletContext.java:199) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.tag.ui.DecorateHandler.apply(DecorateHandler.java:153) ~[jsf-impl-2.2.14.jar:2.2.14]
	at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95) ~[jsf-api-2.2.14.jar:2.2]
	at com.sun.faces.facelets.tag.ui.DefineHandler.applyDefinition(DefineHandler.java:106) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.tag.ui.CompositionHandler.apply(CompositionHandler.java:206) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFaceletContext$TemplateManager.apply(DefaultFaceletContext.java:395) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFaceletContext.includeDefinition(DefaultFaceletContext.java:366) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.tag.ui.InsertHandler.apply(InsertHandler.java:111) ~[jsf-impl-2.2.14.jar:2.2.14]
	at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95) ~[jsf-api-2.2.14.jar:2.2]
	at javax.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:137) ~[jsf-api-2.2.14.jar:2.2]
	at org.richfaces.view.facelets.html.BehaviorsAddingComponentHandlerWrapper.applyNextHandler(BehaviorsAddingComponentHandlerWrapper.java:53) ~[richfaces-a4j-4.5.17.Final.jar:4.5.17.Final]
	at com.sun.faces.facelets.tag.jsf.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:202) ~[jsf-impl-2.2.14.jar:2.2.14]
	at javax.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:120) ~[jsf-api-2.2.14.jar:2.2]
	at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95) ~[jsf-api-2.2.14.jar:2.2]
	at com.sun.faces.facelets.tag.jsf.core.ViewHandler.apply(ViewHandler.java:225) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:93) ~[jsf-impl-2.2.14.jar:2.2.14]
	at javax.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:95) ~[jsf-api-2.2.14.jar:2.2]
	at com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:93) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:87) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:312) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:371) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:350) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFaceletContext.includeFacelet(DefaultFaceletContext.java:199) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.tag.ui.CompositionHandler.apply(CompositionHandler.java:174) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:93) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:87) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.facelets.impl.DefaultFacelet.apply(DefaultFacelet.java:161) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.buildView(FaceletViewHandlingStrategy.java:1006) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:99) ~[jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101) [jsf-impl-2.2.14.jar:2.2.14]
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219) [jsf-impl-2.2.14.jar:2.2.14]
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659) [jsf-api-2.2.14.jar:2.2]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:226) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:566) [jetty-security-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:199) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:74) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.ocpsoft.rewrite.servlet.impl.HttpRewriteResultHandler.handleResult(HttpRewriteResultHandler.java:42) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
	at org.ocpsoft.rewrite.servlet.RewriteFilter.rewrite(RewriteFilter.java:297) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:198) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [jetty-security-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.Server.handle(Server.java:534) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) [jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.15.v20161220.jar:9.3.15.v20161220]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

```

**Comment by yurem** [comment]
Can you retest it again on new build: http://ox.gluu.org/maven/org/xdi/oxtrust-server/3.1.3-SNAPSHOT/oxtrust-server-3.1.3-SNAPSHOT.war ?

**Comment by wasiqulhuq** [comment]
Issue retested and found fixed. Check below screen,

![retest_886](https://user-images.githubusercontent.com/36174217/37310142-3678ab6e-266d-11e8-8aa2-5682778f9db0.jpg)

**Comment by wasiqulhuq** [comment]
```
GLUU.[root@wasiqul_centos6 ~]# cat /opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-962026783387331337.dir/webapp/META-INF/MANIFEST.MF
Manifest-Version: 1.0
Implementation-Title: oxTrust Server
Implementation-Version: 3.1.3-SNAPSHOT
Archiver-Version: Plexus Archiver
Built-By: tomcat
Implementation-Build: 9fe922740002e5a7b49736f6acf2acac23b46731
Implementation-Vendor-Id: org.xdi
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_121
```
