### ISSUE TITLE
3.1.3 QA - Error in displaying UMA scope

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxTrust#898]
UMA > Scope > Click on "SCIM Access" or "Passport Access" to view scope.

![image](https://user-images.githubusercontent.com/21104811/37320009-af362606-2697-11e8-8829-35f28c26bb86.png)

![image](https://user-images.githubusercontent.com/21104811/37320019-bdad5e70-2697-11e8-9018-0a1c7b3e82e0.png)

Oxtrust Error logs

Caused by: javax.el.PropertyNotFoundException: Property 'clientList' not found on type org.gluu.oxtrust.action.uma.UpdateScopeDescriptionAction$Proxy$_$$_WeldSubclass
        at javax.el.BeanELResolver$BeanProperties.get(BeanELResolver.java:268) ~[org.mortbay.jasper.apache-el-8.0.33.jar:8.0.33]
        at javax.el.BeanELResolver$BeanProperties.access$300(BeanELResolver.java:221) ~[org.mortbay.jasper.apache-el-8.0.33.jar:8.0.33]
        at javax.el.BeanELResolver.property(BeanELResolver.java:355) ~[org.mortbay.jasper.apache-el-8.0.33.jar:8.0.33]
        at javax.el.BeanELResolver.getValue(BeanELResolver.java:95) ~[org.mortbay.jasper.apache-el-8.0.33.jar:8.0.33]
        at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176) ~[jsf-impl-2.2.14.jar:2.2.14]
        at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203) ~[jsf-impl-2.2.14.jar:2.2.14]
        at org.apache.el.parser.AstValue.getValue(AstValue.java:169) ~[org.mortbay.jasper.apache-el-8.0.33.jar:8.0.33]
        at org.apache.el.parser.AstNotEqual.getValue(AstNotEqual.java:37) ~[org.mortbay.jasper.apache-el-8.0.33.jar:8.0.33]
        at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184) ~[org.mortbay.jasper.apache-el-8.0.33.jar:8.0.33]
        at org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50) ~[weld-web-3.0.0.Final.jar:3.0.0.Final]
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109) ~[jsf-impl-2.2.14.jar:2.2.14]
        ... 67 more
2018-03-13 02:50:23,022 ERROR [qtp985655350-11] [org.gluu.oxtrust.exception.GlobalExceptionHandler] (GlobalExceptionHandler.java:61) - //opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-3430316937689533230.dir/webapp/uma/scope/modifyScopeDescription.xhtml @147,145 rendered="#{updateScopeDescriptionAction.clientList != null}": Property 'clientList' not found on type org.gluu.oxtrust.action.uma.UpdateScopeDescriptionAction$Proxy$_$$_WeldSubclass
javax.el.PropertyNotFoundException: //opt/jetty-9.3/temp/jetty-localhost-8082-identity.war-_identity-any-3430316937689533230.dir/webapp/uma/scope/modifyScopeDescription.xhtml @147,145 rendered="#{updateScopeDescriptionAction.clientList != null}": Property 'clientList' not found on type org.gluu.oxtrust.action.uma.UpdateScopeDescriptionAction$Proxy$_$$_WeldSubclass
        at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:111) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194) ~[jsf-api-2.2.14.jar:2.2]
        at javax.faces.component.UIComponentBase.isRendered(UIComponentBase.java:458) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.renderkit.html_basic.GridRenderer.encodeChildren(GridRenderer.java:117) ~[jsf-impl-2.2.14.jar:2.2.14]
        at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890) ~[jsf-api-2.2.14.jar:2.2]
        at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.encodeRecursive(HtmlBasicRenderer.java:304) ~[jsf-impl-2.2.14.jar:2.2.14]

**Comment by yurem** [comment]
It works well on new 3.1.3-SNAPSHOT binaries

**Comment by yurem** [comment]
```
javax.el.ELException: //opt/jetty-9.4/temp/jetty-localhost-8082-identity.war-_identity-any-7348040231584140301.dir/webapp/uma/resource/modifyResource.xhtml @165,99 value="#{gluufn:convertLdapTimeToDisplay(_resourceSet.authCreation)}": Problems calling function [gluufn:convertLdapTimeToDisplay]
```
```
Caused by: javax.el.PropertyNotFoundException: Property [authCreation] not found on type [org.xdi.oxauth.model.uma.persistence.UmaResource]
```

Actual property in UmaResource has another name and another type: https://github.com/GluuFederation/oxAuth/blob/master/Model/src/main/java/org/xdi/oxauth/model/uma/UmaResource.java#L61
