### ISSUE TITLE
User entry can't be removed if its "memberOf" attribute contains DN pointing to non-existing group

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxTrust#974]
Environment:
CentOS 6.8, gluu-server-3.1.3 RC6

Steps to reproduce:
1. Learn DN of any existing [expendable] user entry
2. Move into the container
3. Add "memberOf" attribute value containing a bogus DN (DN of group which doesn't exist in this instance) to the user entry; example LDIF is below:
```
dn: inum=@!EF68.9788.26BF.BCDB!0001!9EFA.5E25!0000!B64C.8EB8,ou=people,o=@!EF68.9788.26BF.BCDB!0001!9EFA.5E25,o=gluu
changetype: modify
add: memberOf
memberOf: cn=MYBOGUSDN,ou=MYBOGUSDN,dc=MYBOGUSDN,dc=net0
```
4. Log in to web UI as admin user and try to delete the user

Result:
Operation results in error, user is not deleted until all "memberOf" attributes pointing to non-existing groups are removed from it (can be done via web UI). Next entries appear in logs:
```
2018-04-27 10:02:50,916 ERROR [qtp1744347043-10] [org.gluu.oxtrust.action.UpdatePersonAction] (UpdatePersonAction.java:441) - Failed to remove person @!AFAD.59D9.B3A4.D921!0001!8052.A8D9!0000!B091.399C.D440.A1F4
org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to find entry: cn=MYBOGUSDN,ou=MYBOGUSDN,dc=MYBOGUSDN,dc=net0
	at org.gluu.site.ldap.persistence.LdapEntryManager.find(LdapEntryManager.java:306) ~[oxcore-ldap-3.1.3.Final.jar:?]
	at org.gluu.site.ldap.persistence.AbstractEntryManager.find(AbstractEntryManager.java:444) ~[oxcore-ldap-3.1.3.Final.jar:?]
	at org.gluu.site.ldap.persistence.AbstractEntryManager.find(AbstractEntryManager.java:381) ~[oxcore-ldap-3.1.3.Final.jar:?]
	at org.gluu.site.ldap.persistence.AbstractEntryManager.find(AbstractEntryManager.java:370) ~[oxcore-ldap-3.1.3.Final.jar:?]
	at org.gluu.site.ldap.persistence.LdapEntryManager$Proxy$_$$_WeldClientProxy.find(Unknown Source) ~[oxcore-ldap-3.1.3.Final.jar:?]
	at org.gluu.oxtrust.ldap.service.GroupService.getGroupByDn(GroupService.java:265) ~[classes/:?]

...

	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [jetty-io-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:319) [jetty-util-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:175) [jetty-util-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:133) [jetty-util-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754) [jetty-util-9.4.9.v20180320.jar:9.4.9.v20180320]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672) [jetty-util-9.4.9.v20180320.jar:9.4.9.v20180320]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

Expected result:
There shouldn't be such kind of limitation. Even if group to which user belonged doesn't exist any more (or never existed), there is little reason in forbidding administrator to delete an user, forcing him to resort to console commands instead. It's clear that this feature is intended to maintain consistency of backlinking for attribute pair "member"/"memberOf", but it should treat inconsistencies like described above more gracefully, still.

**Comment by yurem** [comment]
Fixed
